/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
  encodeQueryParam,
} from "make-api-request-js";
import * as z from "zod";

import { DispatchClient } from "api_ts/resources/workflows/dispatch";
import { InvokeClient } from "api_ts/resources/workflows/invoke";
import * as requests from "api_ts/resources/workflows/request-types";
import { RunsClient } from "api_ts/resources/workflows/runs";
import { VersionsClient } from "api_ts/resources/workflows/versions";
import * as types from "api_ts/types";
import { Schemas$WorkflowsCreateBody } from "api_ts/types/workflows-create-body";
import { Schemas$WorkflowsCreateResponse } from "api_ts/types/workflows-create-response";
import { Schemas$WorkflowsDeleteResponse } from "api_ts/types/workflows-delete-response";
import { Schemas$WorkflowsGetResponse } from "api_ts/types/workflows-get-response";
import { Schemas$WorkflowsListResponseItem } from "api_ts/types/workflows-list-response-item";
import { Schemas$WorkflowsPatchBody } from "api_ts/types/workflows-patch-body";
import { Schemas$WorkflowsPatchResponse } from "api_ts/types/workflows-patch-response";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class WorkflowsClient extends CoreResourceClient {
  private _versionsLazy?: VersionsClient; // lazy-loading cache
  private _runsLazy?: RunsClient; // lazy-loading cache
  private _invokeLazy?: InvokeClient; // lazy-loading cache
  private _dispatchLazy?: DispatchClient; // lazy-loading cache

  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
    if (this._opts.lazyLoad === false) {
      this.dispatch;
      this.invoke;
      this.runs;
      this.versions;
    }
  }

  get dispatch(): DispatchClient {
    return (
      this._dispatchLazy ??
      (this._dispatchLazy = new (require("./dispatch").DispatchClient)(
        this._client,
        this._opts,
      ))
    );
  }

  get invoke(): InvokeClient {
    return (
      this._invokeLazy ??
      (this._invokeLazy = new (require("./invoke").InvokeClient)(
        this._client,
        this._opts,
      ))
    );
  }

  get runs(): RunsClient {
    return (
      this._runsLazy ??
      (this._runsLazy = new (require("./runs").RunsClient)(
        this._client,
        this._opts,
      ))
    );
  }

  get versions(): VersionsClient {
    return (
      this._versionsLazy ??
      (this._versionsLazy = new (require("./versions").VersionsClient)(
        this._client,
        this._opts,
      ))
    );
  }

  /**
   * Delete a workflow
   *
   * Delete a workflow (workflow origin) and all its associated versions by the workflow origin ID.
   *
   * DELETE /workflows/{id}
   */
  delete(
    request: requests.DeleteRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowsDeleteResponse> {
    return this._client.makeRequest({
      method: "delete",
      path: `/workflows/${request.id}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$WorkflowsDeleteResponse.in,
      opts,
    });
  }

  /**
   * List workflows
   *
   * Retrieve a paginated list of workflows (workflow origins) for the authenticated user. Each workflow origin represents a collection of workflow versions.
   *
   * GET /workflows
   */
  list(
    request: requests.ListRequest = {},
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowsListResponseItem[]> {
    return this._client.makeRequest({
      method: "get",
      path: "/workflows",
      auth: ["ApiKeyAuth", "BearerAuth"],
      query: [
        encodeQueryParam({
          name: "limit",
          value: z.number().optional().parse(request.limit),
          style: "form",
          explode: true,
        }),
        encodeQueryParam({
          name: "page",
          value: z.number().optional().parse(request.page),
          style: "form",
          explode: true,
        }),
      ],
      responseSchema: z.array(Schemas$WorkflowsListResponseItem.in),
      opts,
    });
  }

  /**
   * Get a workflow
   *
   * Retrieve a single workflow (workflow origin) by its ID.
   *
   * GET /workflows/{id}
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowsGetResponse> {
    return this._client.makeRequest({
      method: "get",
      path: `/workflows/${request.id}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$WorkflowsGetResponse.in,
      opts,
    });
  }

  /**
   * Update a workflow
   *
   * Update an existing workflow (workflow origin) by its ID. Only the provided fields will be updated.
   *
   * PATCH /workflows/{id}
   */
  patch(
    request: requests.PatchRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowsPatchResponse> {
    return this._client.makeRequest({
      method: "patch",
      path: `/workflows/${request.id}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$WorkflowsPatchBody.out.parse(request),
      responseSchema: Schemas$WorkflowsPatchResponse.in,
      opts,
    });
  }

  /**
   * Create a workflow
   *
   * Create a new workflow (workflow origin). This creates the top-level workflow container that holds versioned workflow definitions.
   *
   * POST /workflows
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowsCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: "/workflows",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$WorkflowsCreateBody.out.parse(request),
      responseSchema: Schemas$WorkflowsCreateResponse.in,
      opts,
    });
  }
}
