/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";

import * as requests from "api_ts/resources/memory/tables/query/request-types";
import * as types from "api_ts/types";
import { Schemas$MemoryTablesQueryCreateBody } from "api_ts/types/memory-tables-query-create-body";
import { Schemas$MemoryTablesQueryCreateResponse } from "api_ts/types/memory-tables-query-create-response";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class QueryClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Query a memory table
   *
   * Execute a data query against a memory table. Supports filtering, sorting, and pagination via query modifiers.
   *
   * POST /memory/tables/query
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.MemoryTablesQueryCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: "/memory/tables/query",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$MemoryTablesQueryCreateBody.out.parse(request),
      responseSchema: Schemas$MemoryTablesQueryCreateResponse.in,
      opts,
    });
  }
}
