/**
 * Generated by Sideko (sideko.dev)
 **/

export { WorkspaceClient } from "./resource-client";
export * as variables from "./variables";
/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/
