/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";
import * as z from "zod";

import * as requests from "api_ts/resources/integrations/api/secrets/request-types";
import * as types from "api_ts/types";
import { Schemas$IntegrationsApiSecretsCreateBody } from "api_ts/types/integrations-api-secrets-create-body";
import { Schemas$IntegrationsApiSecretsCreateResponse } from "api_ts/types/integrations-api-secrets-create-response";
import { Schemas$IntegrationsApiSecretsDeleteResponse } from "api_ts/types/integrations-api-secrets-delete-response";
import { Schemas$IntegrationsApiSecretsListResponseItem } from "api_ts/types/integrations-api-secrets-list-response-item";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class SecretsClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Delete an API secret
   *
   * Delete an API secret from the specified API integration.
   *
   * DELETE /integrations/api/{id}/secrets/{secretId}
   */
  delete(
    request: requests.DeleteRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.IntegrationsApiSecretsDeleteResponse> {
    return this._client.makeRequest({
      method: "delete",
      path: `/integrations/api/${request.id}/secrets/${request.secretId}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$IntegrationsApiSecretsDeleteResponse.in,
      opts,
    });
  }

  /**
   * Get all API secrets for an API integration
   *
   * Retrieve all API secrets configured for the specified API integration.
   *
   * GET /integrations/api/{id}/secrets
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.IntegrationsApiSecretsListResponseItem[]> {
    return this._client.makeRequest({
      method: "get",
      path: `/integrations/api/${request.id}/secrets`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: z.array(
        Schemas$IntegrationsApiSecretsListResponseItem.in,
      ),
      opts,
    });
  }

  /**
   * Create a new API secret
   *
   * Create and encrypt a new API secret for the specified API integration.
   *
   * POST /integrations/api/{id}/secrets
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.IntegrationsApiSecretsCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: `/integrations/api/${request.id}/secrets`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: request.data
        ? Schemas$IntegrationsApiSecretsCreateBody.out.parse(request.data)
        : undefined,
      responseSchema: Schemas$IntegrationsApiSecretsCreateResponse.in,
      opts,
    });
  }
}
