/**
 * Generated by Sideko (sideko.dev)
 **/

import { Client, Environment } from "api_ts";

describe("tests client.agent.build.workflow.list", () => {
  test.concurrent(
    "GET /agent/build/workflow | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.agent.build.workflow.list().asResponse(),
        client.agent.build.workflow.list(),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
  test.concurrent(
    "GET /agent/build/workflow | testId: success_required_only | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.agent.build.workflow.list().asResponse(),
        client.agent.build.workflow.list(),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});

describe("tests client.agent.build.workflow.create", () => {
  test.concurrent(
    "POST /agent/build/workflow | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.agent.build.workflow
          .create({
            data: { message: "string", stream: true },
            feed: "string",
            chat: "string",
            workflow: "string",
          })
          .asResponse(),
        client.agent.build.workflow.create({
          data: { message: "string", stream: true },
          feed: "string",
          chat: "string",
          workflow: "string",
        }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
  test.concurrent(
    "POST /agent/build/workflow | testId: success_required_only | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.agent.build.workflow
          .create({ data: { message: "string", stream: true }, feed: "string" })
          .asResponse(),
        client.agent.build.workflow.create({
          data: { message: "string", stream: true },
          feed: "string",
        }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});
