/**
 * Generated by Sideko (sideko.dev)
 **/

import { Client, Environment } from "api_ts";

describe("tests client.chats.get", () => {
  test.concurrent(
    "GET /chats/{id} | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.chats.get({ id: "string" }).asResponse(),
        client.chats.get({ id: "string" }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});

describe("tests client.chats.patch", () => {
  test.concurrent(
    "PATCH /chats/{id} | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.chats
          .patch({
            data: { isWebSearchEnabled: true, query: "string" },
            id: "string",
          })
          .asResponse(),
        client.chats.patch({
          data: { isWebSearchEnabled: true, query: "string" },
          id: "string",
        }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});

describe("tests client.chats.create", () => {
  test.concurrent(
    "POST /chats/{id} | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.chats
          .create({
            data: {
              endDate: "string",
              feedId: "string",
              isWebSearchEnabled: true,
              query: "string",
              startDate: "string",
            },
            id: "string",
            query: "string",
          })
          .asResponse(),
        client.chats.create({
          data: {
            endDate: "string",
            feedId: "string",
            isWebSearchEnabled: true,
            query: "string",
            startDate: "string",
          },
          id: "string",
          query: "string",
        }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});
