/**
 * Generated by Sideko (sideko.dev)
 **/

import { Client, Environment } from "api_ts";

describe("tests client.feeds.vector.search.create", () => {
  test.concurrent(
    "POST /feeds/{id}/vector/search | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.feeds.vector.search
          .create({
            data: {
              endDate: "1970-01-01T00:00:00",
              includeOutputs: true,
              limit: 123,
              query: "string",
              startDate: "1970-01-01T00:00:00",
            },
            id: "123e4567-e89b-12d3-a456-426614174000",
          })
          .asResponse(),
        client.feeds.vector.search.create({
          data: {
            endDate: "1970-01-01T00:00:00",
            includeOutputs: true,
            limit: 123,
            query: "string",
            startDate: "1970-01-01T00:00:00",
          },
          id: "123e4567-e89b-12d3-a456-426614174000",
        }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});
