/**
 * Generated by Sideko (sideko.dev)
 **/

import { Client, Environment } from "api_ts";

describe("tests client.integrations.api.secrets.delete", () => {
  test.concurrent(
    "DELETE /integrations/api/{id}/secrets/{secretId} | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.integrations.api.secrets
          .delete({ id: "string", secretId: "string" })
          .asResponse(),
        client.integrations.api.secrets.delete({
          id: "string",
          secretId: "string",
        }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});

describe("tests client.integrations.api.secrets.list", () => {
  test.concurrent(
    "GET /integrations/api/{id}/secrets | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.integrations.api.secrets.list({ id: "string" }).asResponse(),
        client.integrations.api.secrets.list({ id: "string" }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});

describe("tests client.integrations.api.secrets.create", () => {
  test.concurrent(
    "POST /integrations/api/{id}/secrets | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.integrations.api.secrets
          .create({
            data: { header: "x-api-key", name: "string", value: "string" },
            id: "string",
          })
          .asResponse(),
        client.integrations.api.secrets.create({
          data: { header: "x-api-key", name: "string", value: "string" },
          id: "string",
        }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});
