/**
 * Generated by Sideko (sideko.dev)
 **/

import { Client, Environment } from "api_ts";

describe("tests client.memory.tables.query.create", () => {
  test.concurrent(
    "POST /memory/tables/query | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.memory.tables.query
          .create({ modifiers: {}, query: {}, tableId: "string" })
          .asResponse(),
        client.memory.tables.query.create({
          modifiers: {},
          query: {},
          tableId: "string",
        }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});
