/**
 * Generated by Sideko (sideko.dev)
 **/

import { Client, Environment } from "api_ts";

describe("tests client.subscriptions.events.delete", () => {
  test.concurrent(
    "DELETE /subscriptions/events/{id} | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.subscriptions.events.delete({ id: "string" }).asResponse(),
        client.subscriptions.events.delete({ id: "string" }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});

describe("tests client.subscriptions.events.list", () => {
  test.concurrent(
    "GET /subscriptions/events | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.subscriptions.events.list().asResponse(),
        client.subscriptions.events.list(),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
  test.concurrent(
    "GET /subscriptions/events | testId: success_required_only | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.subscriptions.events.list().asResponse(),
        client.subscriptions.events.list(),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});

describe("tests client.subscriptions.events.get", () => {
  test.concurrent(
    "GET /subscriptions/events/{id} | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.subscriptions.events.get({ id: "string" }).asResponse(),
        client.subscriptions.events.get({ id: "string" }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});

describe("tests client.subscriptions.events.create", () => {
  test.concurrent(
    "POST /subscriptions/events | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.subscriptions.events
          .create({
            consumerId: "string",
            consumerType: "workflow_origins",
            events: ["string"],
            producerId: "string",
            producerType: "feeds",
          })
          .asResponse(),
        client.subscriptions.events.create({
          consumerId: "string",
          consumerType: "workflow_origins",
          events: ["string"],
          producerId: "string",
          producerType: "feeds",
        }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});
