/**
 * Generated by Sideko (sideko.dev)
 **/

import Client, { Environment } from "api_ts";

describe("tests client.tools.structuredOutput.create", () => {
  test.concurrent(
    "POST /tools/structured_output | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.tools.structuredOutput
          .create({ input: "string", schema: {}, validate: true })
          .asResponse(),
        client.tools.structuredOutput.create({
          input: "string",
          schema: {},
          validate: true,
        }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});
