/**
 * Generated by Sideko (sideko.dev)
 **/

import Client, { Environment } from "api_ts";

describe("tests client.workflows.dispatch.create", () => {
  test.concurrent(
    "POST /workflows/{workflow_id}/dispatch | testId: success_all_params | Success test with response schema validation. Expects status code 200",
    async () => {
      const client = new Client({
        apiKey: "API_KEY",
        token: "API_TOKEN",
        environment: Environment.MockServer,
      });
      // Get both raw response for status and parsed response for data
      const [rawResponse, response] = await Promise.all([
        client.workflows.dispatch
          .create({ data: { input: {} }, workflowId: "string" })
          .asResponse(),
        client.workflows.dispatch.create({
          data: { input: {} },
          workflowId: "string",
        }),
      ]);
      expect(rawResponse.status).toBe(200); // Exact status code match
      // Response body automatically validated by Zod schema during deserialization
      expect(response).toBeDefined();
    },
  );
});
