/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  CoreClient,
  CoreResourceClient,
  ResourceClientOptions,
} from "make-api-request-js";

import { TriggerClient } from "api_ts/resources/workflow/run/trigger";

export class RunClient extends CoreResourceClient {
  private _triggerLazy?: TriggerClient; // lazy-loading cache

  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
    if (this._opts.lazyLoad === false) {
      this.trigger;
    }
  }

  get trigger(): TriggerClient {
    return (
      this._triggerLazy ??
      (this._triggerLazy = new (require("./trigger").TriggerClient)(
        this._client,
        this._opts,
      ))
    );
  }
}
