/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$WorkspaceVariablesCreateBody,
  Schemas$WorkspaceVariablesCreateBody,
  WorkspaceVariablesCreateBody,
} from "api_ts/types/workspace-variables-create-body";
import {
  External$WorkspaceVariablesDeleteBody,
  Schemas$WorkspaceVariablesDeleteBody,
  WorkspaceVariablesDeleteBody,
} from "api_ts/types/workspace-variables-delete-body";
import {
  External$WorkspaceVariablesPatchBody,
  Schemas$WorkspaceVariablesPatchBody,
  WorkspaceVariablesPatchBody,
} from "api_ts/types/workspace-variables-patch-body";

/**
 * DeleteRequest
 */
export type DeleteRequest = {
  data?: WorkspaceVariablesDeleteBody | undefined;
};

/**
 * @internal
 * DeleteRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$DeleteRequest = {
  data?: External$WorkspaceVariablesDeleteBody | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object DeleteRequest
 */
const SchemaIn$DeleteRequest: z.ZodType<
  DeleteRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    data: Schemas$WorkspaceVariablesDeleteBody.in.optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$DeleteRequest
 */
const SchemaOut$DeleteRequest: z.ZodType<
  External$DeleteRequest, // output type of this zod object
  z.ZodTypeDef,
  DeleteRequest // the object to be transformed
> = z
  .object({
    data: Schemas$WorkspaceVariablesDeleteBody.out.optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
    });
  });

export const Schemas$DeleteRequest = {
  in: SchemaIn$DeleteRequest,
  out: SchemaOut$DeleteRequest,
};

/**
 * ListRequest
 */
export type ListRequest = {
  /**
   * Filter by API ID
   */
  api?: string | undefined;
  limit?: number | undefined;
  /**
   * Filter by variable name (exact match)
   */
  name?: string | undefined;
  /**
   * Filter by origin ID
   */
  origin?: string | undefined;
  page?: number | undefined;
};

/**
 * @internal
 * ListRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ListRequest = {
  api?: string | undefined;
  limit?: number | undefined;
  name?: string | undefined;
  origin?: string | undefined;
  page?: number | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ListRequest
 */
const SchemaIn$ListRequest: z.ZodType<
  ListRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    api: z.string().optional(),
    limit: z.number().optional(),
    name: z.string().optional(),
    origin: z.string().optional(),
    page: z.number().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      api: "api",
      limit: "limit",
      name: "name",
      origin: "origin",
      page: "page",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ListRequest
 */
const SchemaOut$ListRequest: z.ZodType<
  External$ListRequest, // output type of this zod object
  z.ZodTypeDef,
  ListRequest // the object to be transformed
> = z
  .object({
    api: z.string().optional(),
    limit: z.number().optional(),
    name: z.string().optional(),
    origin: z.string().optional(),
    page: z.number().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      api: "api",
      limit: "limit",
      name: "name",
      origin: "origin",
      page: "page",
    });
  });

export const Schemas$ListRequest = {
  in: SchemaIn$ListRequest,
  out: SchemaOut$ListRequest,
};

/**
 * PatchRequest
 */
export type PatchRequest = {
  data?: WorkspaceVariablesPatchBody | undefined;
};

/**
 * @internal
 * PatchRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$PatchRequest = {
  data?: External$WorkspaceVariablesPatchBody | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object PatchRequest
 */
const SchemaIn$PatchRequest: z.ZodType<
  PatchRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    data: Schemas$WorkspaceVariablesPatchBody.in.optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$PatchRequest
 */
const SchemaOut$PatchRequest: z.ZodType<
  External$PatchRequest, // output type of this zod object
  z.ZodTypeDef,
  PatchRequest // the object to be transformed
> = z
  .object({
    data: Schemas$WorkspaceVariablesPatchBody.out.optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
    });
  });

export const Schemas$PatchRequest = {
  in: SchemaIn$PatchRequest,
  out: SchemaOut$PatchRequest,
};

/**
 * CreateRequest
 */
export type CreateRequest = {
  data?: WorkspaceVariablesCreateBody | undefined;
};

/**
 * @internal
 * CreateRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$CreateRequest = {
  data?: External$WorkspaceVariablesCreateBody | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object CreateRequest
 */
const SchemaIn$CreateRequest: z.ZodType<
  CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    data: Schemas$WorkspaceVariablesCreateBody.in.optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$CreateRequest
 */
const SchemaOut$CreateRequest: z.ZodType<
  External$CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  CreateRequest // the object to be transformed
> = z
  .object({
    data: Schemas$WorkspaceVariablesCreateBody.out.optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
    });
  });

export const Schemas$CreateRequest = {
  in: SchemaIn$CreateRequest,
  out: SchemaOut$CreateRequest,
};
