/**
 * Generated by Sideko (sideko.dev)
 **/

export * as mutate from "./mutate";
export * as query from "./query";
export {
  CreateRequest,
  DeleteRequest,
  GetRequest,
  ListRequest,
} from "./request-types";
export { TablesClient } from "./resource-client";
/**
 * Generated by Sideko (sideko.dev)
 **/
