/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
  encodeQueryParam,
} from "make-api-request-js";
import * as z from "zod";

import { MutateClient } from "api_ts/resources/memory/tables/mutate";
import { QueryClient } from "api_ts/resources/memory/tables/query";
import * as requests from "api_ts/resources/memory/tables/request-types";
import * as types from "api_ts/types";
import { Schemas$MemoryTablesCreateBody } from "api_ts/types/memory-tables-create-body";
import { Schemas$MemoryTablesCreateResponse } from "api_ts/types/memory-tables-create-response";
import { Schemas$MemoryTablesDeleteResponse } from "api_ts/types/memory-tables-delete-response";
import { Schemas$MemoryTablesGetResponse } from "api_ts/types/memory-tables-get-response";
import { Schemas$MemoryTablesListResponseItem } from "api_ts/types/memory-tables-list-response-item";

export class TablesClient extends CoreResourceClient {
  private _queryLazy?: QueryClient; // lazy-loading cache
  private _mutateLazy?: MutateClient; // lazy-loading cache

  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
    if (this._opts.lazyLoad === false) {
      this.mutate;
      this.query;
    }
  }

  get mutate(): MutateClient {
    return (
      this._mutateLazy ??
      (this._mutateLazy = new (require("./mutate").MutateClient)(
        this._client,
        this._opts,
      ))
    );
  }

  get query(): QueryClient {
    return (
      this._queryLazy ??
      (this._queryLazy = new (require("./query").QueryClient)(
        this._client,
        this._opts,
      ))
    );
  }

  /**
   * Delete a memory table
   *
   * Delete a memory table and all its rows by the table ID.
   *
   * DELETE /memory/tables/{id}
   */
  delete(
    request: requests.DeleteRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.MemoryTablesDeleteResponse> {
    return this._client.makeRequest({
      method: "delete",
      path: `/memory/tables/${request.id}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$MemoryTablesDeleteResponse.in,
      opts,
    });
  }

  /**
   * List memory tables
   *
   * Retrieve a paginated list of memory tables owned by the authenticated user.
   *
   * GET /memory/tables
   */
  list(
    request: requests.ListRequest = {},
    opts?: RequestOptions,
  ): ApiPromise<types.MemoryTablesListResponseItem[]> {
    return this._client.makeRequest({
      method: "get",
      path: "/memory/tables",
      auth: ["ApiKeyAuth", "BearerAuth"],
      query: [
        encodeQueryParam({
          name: "limit",
          value: z.number().optional().parse(request.limit),
          style: "form",
          explode: true,
        }),
        encodeQueryParam({
          name: "page",
          value: z.number().optional().parse(request.page),
          style: "form",
          explode: true,
        }),
      ],
      responseSchema: z.array(Schemas$MemoryTablesListResponseItem.in),
      opts,
    });
  }

  /**
   * Get a memory table
   *
   * Retrieve a single memory table by its ID, including its schema definition.
   *
   * GET /memory/tables/{id}
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.MemoryTablesGetResponse> {
    return this._client.makeRequest({
      method: "get",
      path: `/memory/tables/${request.id}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$MemoryTablesGetResponse.in,
      opts,
    });
  }

  /**
   * Create a memory table
   *
   * Create a new memory table with a name, description, and JSON Schema defining its row structure.
   *
   * POST /memory/tables
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.MemoryTablesCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: "/memory/tables",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$MemoryTablesCreateBody.out.parse(request),
      responseSchema: Schemas$MemoryTablesCreateResponse.in,
      opts,
    });
  }
}
