/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  CoreClient,
  CoreResourceClient,
  ResourceClientOptions,
} from "make-api-request-js";

import { TablesClient } from "api_ts/resources/memory/tables";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class MemoryClient extends CoreResourceClient {
  private _tablesLazy?: TablesClient; // lazy-loading cache

  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
    if (this._opts.lazyLoad === false) {
      this.tables;
    }
  }

  get tables(): TablesClient {
    return (
      this._tablesLazy ??
      (this._tablesLazy = new (require("./tables").TablesClient)(
        this._client,
        this._opts,
      ))
    );
  }
}
