/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";

import * as requests from "api_ts/resources/feeds/items/request-types";
import * as types from "api_ts/types";
import { Schemas$FeedsItemsCreateBody } from "api_ts/types/feeds-items-create-body";
import { Schemas$FeedsItemsCreateResponse } from "api_ts/types/feeds-items-create-response";
import { Schemas$FeedsItemsGetResponse } from "api_ts/types/feeds-items-get-response";

export class ItemsClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Get a specific feed item by ID
   *
   * GET /feeds/items/{id}
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.FeedsItemsGetResponse> {
    return this._client.makeRequest({
      method: "get",
      path: `/feeds/items/${request.id}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$FeedsItemsGetResponse.in,
      opts,
    });
  }

  /**
   * Create a new feed item for an API feed
   *
   * POST /feeds/items
   */
  create(
    request: requests.CreateRequest = {},
    opts?: RequestOptions,
  ): ApiPromise<types.FeedsItemsCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: "/feeds/items",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: request.data
        ? Schemas$FeedsItemsCreateBody.out.parse(request.data)
        : undefined,
      responseSchema: Schemas$FeedsItemsCreateResponse.in,
      opts,
    });
  }
}
