/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * DeleteRequest
 */
export type DeleteRequest = {
  /**
   * The workflow origin ID
   */
  originId: string;
  /**
   * The workflow version ID
   */
  versionId: string;
};

/**
 * @internal
 * DeleteRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$DeleteRequest = {
  origin_id: string;
  version_id: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object DeleteRequest
 */
const SchemaIn$DeleteRequest: z.ZodType<
  DeleteRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    origin_id: z.string(),
    version_id: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      origin_id: "originId",
      version_id: "versionId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$DeleteRequest
 */
const SchemaOut$DeleteRequest: z.ZodType<
  External$DeleteRequest, // output type of this zod object
  z.ZodTypeDef,
  DeleteRequest // the object to be transformed
> = z
  .object({
    originId: z.string(),
    versionId: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      originId: "origin_id",
      versionId: "version_id",
    });
  });

export const Schemas$DeleteRequest = {
  in: SchemaIn$DeleteRequest,
  out: SchemaOut$DeleteRequest,
};

/**
 * ListRequest
 */
export type ListRequest = {
  /**
   * The workflow origin ID
   */
  originId: string;
  /**
   * Number of items per page
   */
  limit?: number | undefined;
  /**
   * Page number (1-based)
   */
  page?: number | undefined;
};

/**
 * @internal
 * ListRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ListRequest = {
  origin_id: string;
  limit?: number | undefined;
  page?: number | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ListRequest
 */
const SchemaIn$ListRequest: z.ZodType<
  ListRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    origin_id: z.string(),
    limit: z.number().optional(),
    page: z.number().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      origin_id: "originId",
      limit: "limit",
      page: "page",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ListRequest
 */
const SchemaOut$ListRequest: z.ZodType<
  External$ListRequest, // output type of this zod object
  z.ZodTypeDef,
  ListRequest // the object to be transformed
> = z
  .object({
    originId: z.string(),
    limit: z.number().optional(),
    page: z.number().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      originId: "origin_id",
      limit: "limit",
      page: "page",
    });
  });

export const Schemas$ListRequest = {
  in: SchemaIn$ListRequest,
  out: SchemaOut$ListRequest,
};

/**
 * GetRequest
 */
export type GetRequest = {
  /**
   * The workflow origin ID
   */
  originId: string;
  /**
   * The workflow version ID
   */
  versionId: string;
};

/**
 * @internal
 * GetRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$GetRequest = {
  origin_id: string;
  version_id: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object GetRequest
 */
const SchemaIn$GetRequest: z.ZodType<
  GetRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    origin_id: z.string(),
    version_id: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      origin_id: "originId",
      version_id: "versionId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$GetRequest
 */
const SchemaOut$GetRequest: z.ZodType<
  External$GetRequest, // output type of this zod object
  z.ZodTypeDef,
  GetRequest // the object to be transformed
> = z
  .object({
    originId: z.string(),
    versionId: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      originId: "origin_id",
      versionId: "version_id",
    });
  });

export const Schemas$GetRequest = {
  in: SchemaIn$GetRequest,
  out: SchemaOut$GetRequest,
};

/**
 * PatchRequest
 */
export type PatchRequest = {
  /**
   * Updated access level
   */
  access?: string | undefined;
  /**
   * Updated active status
   */
  active?: boolean | undefined;
  /**
   * Updated description
   */
  description?: string | undefined;
  /**
   * Updated instructions
   */
  instructions?: string | null | undefined;
  /**
   * Updated name
   */
  name?: string | undefined;
  /**
   * The workflow origin ID
   */
  originId: string;
  /**
   * The workflow version ID
   */
  versionId: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (string | undefined)
    | (boolean | undefined)
    | (string | undefined)
    | (string | null | undefined)
    | (string | undefined)
    | string
    | string
    | any
    | null
    | undefined;
};

/**
 * @internal
 * PatchRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$PatchRequest = {
  access?: string | undefined;
  active?: boolean | undefined;
  description?: string | undefined;
  instructions?: string | null | undefined;
  name?: string | undefined;
  origin_id: string;
  version_id: string;

  [additionalProperty: string]:
    | (string | undefined)
    | (boolean | undefined)
    | (string | undefined)
    | (string | null | undefined)
    | (string | undefined)
    | string
    | string
    | External$PatchRequest
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object PatchRequest
 */
const SchemaIn$PatchRequest: z.ZodType<
  PatchRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    access: z.string().optional(),
    active: z.boolean().optional(),
    description: z.string().optional(),
    instructions: z.string().nullable().optional(),
    name: z.string().optional(),
    origin_id: z.string(),
    version_id: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      access: "access",
      active: "active",
      description: "description",
      instructions: "instructions",
      name: "name",
      origin_id: "originId",
      version_id: "versionId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$PatchRequest
 */
const SchemaOut$PatchRequest: z.ZodType<
  External$PatchRequest, // output type of this zod object
  z.ZodTypeDef,
  PatchRequest // the object to be transformed
> = z
  .object({
    access: z.string().optional(),
    active: z.boolean().optional(),
    description: z.string().optional(),
    instructions: z.string().nullable().optional(),
    name: z.string().optional(),
    originId: z.string(),
    versionId: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      access: "access",
      active: "active",
      description: "description",
      instructions: "instructions",
      name: "name",
      originId: "origin_id",
      versionId: "version_id",
    });
  });

export const Schemas$PatchRequest = {
  in: SchemaIn$PatchRequest,
  out: SchemaOut$PatchRequest,
};

/**
 * CreateRequest
 */
export type CreateRequest = {
  /**
   * Access level (e.g. PRIVATE, PUBLIC)
   */
  access?: string | undefined;
  /**
   * Whether this version is active
   */
  active?: boolean | undefined;
  /**
   * Description of the workflow version
   */
  description: string;
  /**
   * Optional instructions for the workflow
   */
  instructions?: string | null | undefined;
  /**
   * Name of the workflow version
   */
  name: string;
  /**
   * The workflow origin ID
   */
  originId: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (string | undefined)
    | (boolean | undefined)
    | string
    | (string | null | undefined)
    | string
    | string
    | any
    | null
    | undefined;
};

/**
 * @internal
 * CreateRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$CreateRequest = {
  access?: string | undefined;
  active?: boolean | undefined;
  description: string;
  instructions?: string | null | undefined;
  name: string;
  origin_id: string;

  [additionalProperty: string]:
    | (string | undefined)
    | (boolean | undefined)
    | string
    | (string | null | undefined)
    | string
    | string
    | External$CreateRequest
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object CreateRequest
 */
const SchemaIn$CreateRequest: z.ZodType<
  CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    access: z.string().optional(),
    active: z.boolean().optional(),
    description: z.string(),
    instructions: z.string().nullable().optional(),
    name: z.string(),
    origin_id: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      access: "access",
      active: "active",
      description: "description",
      instructions: "instructions",
      name: "name",
      origin_id: "originId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$CreateRequest
 */
const SchemaOut$CreateRequest: z.ZodType<
  External$CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  CreateRequest // the object to be transformed
> = z
  .object({
    access: z.string().optional(),
    active: z.boolean().optional(),
    description: z.string(),
    instructions: z.string().nullable().optional(),
    name: z.string(),
    originId: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      access: "access",
      active: "active",
      description: "description",
      instructions: "instructions",
      name: "name",
      originId: "origin_id",
    });
  });

export const Schemas$CreateRequest = {
  in: SchemaIn$CreateRequest,
  out: SchemaOut$CreateRequest,
};
