/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
  encodeQueryParam,
} from "make-api-request-js";
import * as z from "zod";

import * as requests from "api_ts/resources/datastore/items/request-types";
import * as types from "api_ts/types";
import { Schemas$DatastoreItemsCreateBody } from "api_ts/types/datastore-items-create-body";
import { Schemas$DatastoreItemsCreateResponse } from "api_ts/types/datastore-items-create-response";
import { Schemas$DatastoreItemsDeleteResponse } from "api_ts/types/datastore-items-delete-response";
import { Schemas$DatastoreItemsGetResponse } from "api_ts/types/datastore-items-get-response";
import { Schemas$DatastoreItemsListResponseItemObj0 } from "api_ts/types/datastore-items-list-response-item-obj0";
import { Schemas$DatastoreItemsListResponseItemObj1 } from "api_ts/types/datastore-items-list-response-item-obj1";

export class ItemsClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Delete a datastore item
   *
   * Delete a datastore item and its underlying storage objects.
   *
   * DELETE /datastore/items/{item_id}
   */
  delete(
    request: requests.DeleteRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.DatastoreItemsDeleteResponse> {
    return this._client.makeRequest({
      method: "delete",
      path: `/datastore/items/${request.itemId}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$DatastoreItemsDeleteResponse.in,
      opts,
    });
  }

  /**
   * Get a datastore item
   *
   * Retrieve a datastore item, including its raw data (FileStore returns base64-encoded bytes for binary content).
   *
   * GET /datastore/items/{item_id}
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.DatastoreItemsGetResponse> {
    return this._client.makeRequest({
      method: "get",
      path: `/datastore/items/${request.itemId}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$DatastoreItemsGetResponse.in,
      opts,
    });
  }

  /**
   * List datastore items
   *
   * List datastore items at the given prefix. Returns S3-style entries: nested prefixes (folders) and items at the prefix level.
   *
   * GET /datastore/{id}/items
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<
    (
      | types.DatastoreItemsListResponseItemObj0
      | types.DatastoreItemsListResponseItemObj1
    )[]
  > {
    return this._client.makeRequest({
      method: "get",
      path: `/datastore/${request.id}/items`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      query: [
        encodeQueryParam({
          name: "prefix",
          value: z.string().optional().parse(request.prefix),
          style: "form",
          explode: true,
        }),
      ],
      responseSchema: z.array(
        z.union([
          Schemas$DatastoreItemsListResponseItemObj0.in,
          Schemas$DatastoreItemsListResponseItemObj1.in,
        ]),
      ),
      opts,
    });
  }

  /**
   * Create a datastore item
   *
   * Create a new item in a FileStore or VectorStore datastore. For VectorStores the data must be embeddable text.
   *
   * POST /datastore/{id}/items
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.DatastoreItemsCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: `/datastore/${request.id}/items`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$DatastoreItemsCreateBody.out.parse(request),
      responseSchema: Schemas$DatastoreItemsCreateResponse.in,
      opts,
    });
  }
}
