/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";

import * as requests from "api_ts/resources/workflows/invoke/request-types";
import * as types from "api_ts/types";
import { Schemas$WorkflowsInvokeCreateBody } from "api_ts/types/workflows-invoke-create-body";
import { Schemas$WorkflowsInvokeCreateResponse } from "api_ts/types/workflows-invoke-create-response";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class InvokeClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Invoke a workflow
   *
   * Invoke a workflow run. This is a synchronous call that waits for the workflow run to complete and returns the result.
   *
   * POST /workflows/{workflow_id}/invoke
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowsInvokeCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: `/workflows/${request.workflowId}/invoke`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: request.data
        ? Schemas$WorkflowsInvokeCreateBody.out.parse(request.data)
        : undefined,
      responseSchema: Schemas$WorkflowsInvokeCreateResponse.in,
      opts,
    });
  }
}
