/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";
import * as z from "zod";

import * as requests from "api_ts/resources/tools/meta-tagger/request-types";
import * as types from "api_ts/types";
import { Schemas$ToolsMetaTaggerCreateBody } from "api_ts/types/tools-meta-tagger-create-body";
import { Schemas$ToolsMetaTaggerCreateResponseItem } from "api_ts/types/tools-meta-tagger-create-response-item";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class MetaTaggerClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Apply meta tags
   *
   * Apply the most relevant meta tags from the provided search groups to the input data.
   *
   * POST /tools/meta_tagger
   */
  create(
    request: requests.CreateRequest = {},
    opts?: RequestOptions,
  ): ApiPromise<types.ToolsMetaTaggerCreateResponseItem[]> {
    return this._client.makeRequest({
      method: "post",
      path: "/tools/meta_tagger",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: request.data
        ? Schemas$ToolsMetaTaggerCreateBody.out.parse(request.data)
        : undefined,
      responseSchema: z.array(Schemas$ToolsMetaTaggerCreateResponseItem.in),
      opts,
    });
  }
}
