/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  CoreClient,
  CoreResourceClient,
  ResourceClientOptions,
} from "make-api-request-js";

import { EventsClient } from "api_ts/resources/subscriptions/events";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class SubscriptionsClient extends CoreResourceClient {
  private _eventsLazy?: EventsClient; // lazy-loading cache

  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
    if (this._opts.lazyLoad === false) {
      this.events;
    }
  }

  get events(): EventsClient {
    return (
      this._eventsLazy ??
      (this._eventsLazy = new (require("./events").EventsClient)(
        this._client,
        this._opts,
      ))
    );
  }
}
