/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$ToolsInternetSearchCreateBodyMessagesItem,
  Schemas$ToolsInternetSearchCreateBodyMessagesItem,
  ToolsInternetSearchCreateBodyMessagesItem,
} from "api_ts/types/tools-internet-search-create-body-messages-item";

/**
 * CreateRequest
 */
export type CreateRequest = {
  /**
   * The maximum number of times the tool can be used
   */
  maxUses?: number | null | undefined;
  messages: ToolsInternetSearchCreateBodyMessagesItem[];
  system: string;
};

/**
 * @internal
 * CreateRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$CreateRequest = {
  max_uses?: number | null | undefined;
  messages: External$ToolsInternetSearchCreateBodyMessagesItem[];
  system: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object CreateRequest
 */
const SchemaIn$CreateRequest: z.ZodType<
  CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    max_uses: z.number().int().nullable().optional(),
    messages: z.array(Schemas$ToolsInternetSearchCreateBodyMessagesItem.in),
    system: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      max_uses: "maxUses",
      messages: "messages",
      system: "system",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$CreateRequest
 */
const SchemaOut$CreateRequest: z.ZodType<
  External$CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  CreateRequest // the object to be transformed
> = z
  .object({
    maxUses: z.number().int().nullable().optional(),
    messages: z.array(Schemas$ToolsInternetSearchCreateBodyMessagesItem.out),
    system: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      maxUses: "max_uses",
      messages: "messages",
      system: "system",
    });
  });

export const Schemas$CreateRequest = {
  in: SchemaIn$CreateRequest,
  out: SchemaOut$CreateRequest,
};
