/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";
import * as z from "zod";

import * as requests from "api_ts/resources/tools/internet-search/request-types";
import * as types from "api_ts/types";
import { Schemas$ToolsInternetSearchCreateBody } from "api_ts/types/tools-internet-search-create-body";
import { Schemas$ToolsInternetSearchCreateResponseItem } from "api_ts/types/tools-internet-search-create-response-item";

export class InternetSearchClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Internet search tool
   *
   * POST /tools/internet_search
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.ToolsInternetSearchCreateResponseItem[]> {
    return this._client.makeRequest({
      method: "post",
      path: "/tools/internet_search",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$ToolsInternetSearchCreateBody.out.parse(request),
      responseSchema: z.array(Schemas$ToolsInternetSearchCreateResponseItem.in),
      opts,
    });
  }
}
