/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";

import * as requests from "api_ts/resources/workflows/dispatch/request-types";
import * as types from "api_ts/types";
import { Schemas$WorkflowsDispatchCreateBody } from "api_ts/types/workflows-dispatch-create-body";
import { Schemas$WorkflowsDispatchCreateResponse } from "api_ts/types/workflows-dispatch-create-response";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class DispatchClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Dispatch a workflow
   *
   * Dispatch a new workflow run asynchronously. This call returns the workflow run ID so the caller can poll for the result.
   *
   * POST /workflows/{workflow_id}/dispatch
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowsDispatchCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: `/workflows/${request.workflowId}/dispatch`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: request.data
        ? Schemas$WorkflowsDispatchCreateBody.out.parse(request.data)
        : undefined,
      responseSchema: Schemas$WorkflowsDispatchCreateResponse.in,
      opts,
    });
  }
}
