/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$ToolsStandardLlmCreateBodyMessagesItem,
  Schemas$ToolsStandardLlmCreateBodyMessagesItem,
  ToolsStandardLlmCreateBodyMessagesItem,
} from "api_ts/types/tools-standard-llm-create-body-messages-item";

/**
 * CreateRequest
 */
export type CreateRequest = {
  messages: ToolsStandardLlmCreateBodyMessagesItem[];
  system: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | ToolsStandardLlmCreateBodyMessagesItem[]
    | string
    | any
    | null
    | undefined;
};

/**
 * @internal
 * CreateRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$CreateRequest = {
  messages: External$ToolsStandardLlmCreateBodyMessagesItem[];
  system: string;

  [additionalProperty: string]:
    | External$ToolsStandardLlmCreateBodyMessagesItem[]
    | string
    | External$CreateRequest
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object CreateRequest
 */
const SchemaIn$CreateRequest: z.ZodType<
  CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    messages: z.array(Schemas$ToolsStandardLlmCreateBodyMessagesItem.in),
    system: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      messages: "messages",
      system: "system",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$CreateRequest
 */
const SchemaOut$CreateRequest: z.ZodType<
  External$CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  CreateRequest // the object to be transformed
> = z
  .object({
    messages: z.array(Schemas$ToolsStandardLlmCreateBodyMessagesItem.out),
    system: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      messages: "messages",
      system: "system",
    });
  });

export const Schemas$CreateRequest = {
  in: SchemaIn$CreateRequest,
  out: SchemaOut$CreateRequest,
};
