/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";
import * as z from "zod";

import * as requests from "api_ts/resources/tools/standard-llm/request-types";
import * as types from "api_ts/types";
import { Schemas$ToolsStandardLlmCreateBody } from "api_ts/types/tools-standard-llm-create-body";
import { Schemas$ToolsStandardLlmCreateResponseItem } from "api_ts/types/tools-standard-llm-create-response-item";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class StandardLlmClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Run standard LLM
   *
   * Send a standard LLM request and return the model response content.
   *
   * POST /tools/standard_llm
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.ToolsStandardLlmCreateResponseItem[]> {
    return this._client.makeRequest({
      method: "post",
      path: "/tools/standard_llm",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$ToolsStandardLlmCreateBody.out.parse(request),
      responseSchema: z.array(Schemas$ToolsStandardLlmCreateResponseItem.in),
      opts,
    });
  }
}
