/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
  encodeQueryParam,
} from "make-api-request-js";
import * as z from "zod";

import * as requests from "api_ts/resources/subscriptions/events/request-types";
import * as types from "api_ts/types";
import { Schemas$SubscriptionsEventsCreateBody } from "api_ts/types/subscriptions-events-create-body";
import { Schemas$SubscriptionsEventsCreateResponse } from "api_ts/types/subscriptions-events-create-response";
import { Schemas$SubscriptionsEventsDeleteResponse } from "api_ts/types/subscriptions-events-delete-response";
import { Schemas$SubscriptionsEventsGetResponse } from "api_ts/types/subscriptions-events-get-response";
import { Schemas$SubscriptionsEventsListResponseItem } from "api_ts/types/subscriptions-events-list-response-item";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class EventsClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Delete an event subscription
   *
   * Delete an event subscription by its ID.
   *
   * DELETE /subscriptions/events/{id}
   */
  delete(
    request: requests.DeleteRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.SubscriptionsEventsDeleteResponse> {
    return this._client.makeRequest({
      method: "delete",
      path: `/subscriptions/events/${request.id}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$SubscriptionsEventsDeleteResponse.in,
      opts,
    });
  }

  /**
   * List event subscriptions
   *
   * Retrieve a paginated list of event subscriptions for the authenticated user.
   *
   * GET /subscriptions/events
   */
  list(
    request: requests.ListRequest = {},
    opts?: RequestOptions,
  ): ApiPromise<types.SubscriptionsEventsListResponseItem[]> {
    return this._client.makeRequest({
      method: "get",
      path: "/subscriptions/events",
      auth: ["ApiKeyAuth", "BearerAuth"],
      query: [
        encodeQueryParam({
          name: "limit",
          value: z.number().optional().parse(request.limit),
          style: "form",
          explode: true,
        }),
        encodeQueryParam({
          name: "page",
          value: z.number().optional().parse(request.page),
          style: "form",
          explode: true,
        }),
      ],
      responseSchema: z.array(Schemas$SubscriptionsEventsListResponseItem.in),
      opts,
    });
  }

  /**
   * Get an event subscription
   *
   * Retrieve a single event subscription by its ID.
   *
   * GET /subscriptions/events/{id}
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.SubscriptionsEventsGetResponse> {
    return this._client.makeRequest({
      method: "get",
      path: `/subscriptions/events/${request.id}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$SubscriptionsEventsGetResponse.in,
      opts,
    });
  }

  /**
   * Create an event subscription
   *
   * Create a new event subscription that links a producer to a consumer via event patterns.
   *
   * POST /subscriptions/events
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.SubscriptionsEventsCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: "/subscriptions/events",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$SubscriptionsEventsCreateBody.out.parse(request),
      responseSchema: Schemas$SubscriptionsEventsCreateResponse.in,
      opts,
    });
  }
}
