/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";

import * as requests from "api_ts/resources/workflows/versions/tasks/request-types";
import * as types from "api_ts/types";
import { Schemas$WorkflowsVersionsTasksCreateBody } from "api_ts/types/workflows-versions-tasks-create-body";
import { Schemas$WorkflowsVersionsTasksCreateResponse } from "api_ts/types/workflows-versions-tasks-create-response";
import { Schemas$WorkflowsVersionsTasksDeleteResponse } from "api_ts/types/workflows-versions-tasks-delete-response";
import { Schemas$WorkflowsVersionsTasksGetResponse } from "api_ts/types/workflows-versions-tasks-get-response";
import { Schemas$WorkflowsVersionsTasksPatchBody } from "api_ts/types/workflows-versions-tasks-patch-body";
import { Schemas$WorkflowsVersionsTasksPatchResponse } from "api_ts/types/workflows-versions-tasks-patch-response";

/**
 * Generated by Sideko (sideko.dev)
 **/

export class TasksClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Delete a workflow task
   *
   * Delete a specific workflow task by its ID.
   *
   * DELETE /workflows/versions/{version_id}/tasks/{task_id}
   */
  delete(
    request: requests.DeleteRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowsVersionsTasksDeleteResponse> {
    return this._client.makeRequest({
      method: "delete",
      path: `/workflows/versions/${request.versionId}/tasks/${request.taskId}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$WorkflowsVersionsTasksDeleteResponse.in,
      opts,
    });
  }

  /**
   * Get a workflow task
   *
   * Retrieve a single workflow task by its ID.
   *
   * GET /workflows/versions/{version_id}/tasks/{task_id}
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowsVersionsTasksGetResponse> {
    return this._client.makeRequest({
      method: "get",
      path: `/workflows/versions/${request.versionId}/tasks/${request.taskId}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$WorkflowsVersionsTasksGetResponse.in,
      opts,
    });
  }

  /**
   * Update a workflow task
   *
   * Update an existing workflow task. Only the provided fields will be updated.
   *
   * PATCH /workflows/versions/{version_id}/tasks/{task_id}
   */
  patch(
    request: requests.PatchRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowsVersionsTasksPatchResponse> {
    return this._client.makeRequest({
      method: "patch",
      path: `/workflows/versions/${request.versionId}/tasks/${request.taskId}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$WorkflowsVersionsTasksPatchBody.out.parse(request),
      responseSchema: Schemas$WorkflowsVersionsTasksPatchResponse.in,
      opts,
    });
  }

  /**
   * Create a workflow task
   *
   * Create a new task under a specific workflow version.
   *
   * POST /workflows/versions/{version_id}/tasks
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowsVersionsTasksCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: `/workflows/versions/${request.versionId}/tasks`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$WorkflowsVersionsTasksCreateBody.out.parse(request),
      responseSchema: Schemas$WorkflowsVersionsTasksCreateResponse.in,
      opts,
    });
  }
}
