/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed
 */
export type AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed = {
  accountId?: string | null | undefined;
  config: Record<string, any | undefined>;
  createdAt?: string | null | undefined;
  description: string;
  feedType: "API" | "CHRONJOB" | "EMAIL";
  id: string;
  name: string;
  schema?: Record<string, any | undefined> | null | undefined;
  userId?: string | null | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (string | null | undefined)
    | Record<string, any | undefined>
    | (string | null | undefined)
    | string
    | ("API" | "CHRONJOB" | "EMAIL")
    | string
    | string
    | (Record<string, any | undefined> | null | undefined)
    | (string | null | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed =
  {
    account_id?: string | null | undefined;
    config: Record<string, any | undefined>;
    created_at?: string | null | undefined;
    description: string;
    feed_type: "API" | "CHRONJOB" | "EMAIL";
    id: string;
    name: string;
    schema?: Record<string, any | undefined> | null | undefined;
    user_id?: string | null | undefined;

    [additionalProperty: string]:
      | (string | null | undefined)
      | Record<string, any | undefined>
      | (string | null | undefined)
      | string
      | ("API" | "CHRONJOB" | "EMAIL")
      | string
      | string
      | (Record<string, any | undefined> | null | undefined)
      | (string | null | undefined)
      | External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed
      | null
      | undefined;
  };

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed
 */
const SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed: z.ZodType<
  AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    account_id: z.string().nullable().optional(),
    config: z.record(z.string(), zodRequiredAny.optional()),
    created_at: z.string().nullable().optional(),
    description: z.string(),
    feed_type: z.enum(["API", "CHRONJOB", "EMAIL"]),
    id: z.string(),
    name: z.string(),
    schema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    user_id: z.string().nullable().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      account_id: "accountId",
      config: "config",
      created_at: "createdAt",
      description: "description",
      feed_type: "feedType",
      id: "id",
      name: "name",
      schema: "schema",
      user_id: "userId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed
 */
const SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed: z.ZodType<
  External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed // the object to be transformed
> = z
  .object({
    accountId: z.string().nullable().optional(),
    config: z.record(z.string(), zodRequiredAny.optional()),
    createdAt: z.string().nullable().optional(),
    description: z.string(),
    feedType: z.enum(["API", "CHRONJOB", "EMAIL"]),
    id: z.string(),
    name: z.string(),
    schema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    userId: z.string().nullable().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      accountId: "account_id",
      config: "config",
      createdAt: "created_at",
      description: "description",
      feedType: "feed_type",
      id: "id",
      name: "name",
      schema: "schema",
      userId: "user_id",
    });
  });

export const Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed =
  {
    in: SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed,
    out: SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed,
  };
