/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * AgentCreateResponseMessagesItem
 */
export type AgentCreateResponseMessagesItem = {
  content: any;
  role: "assistant" | "subcall" | "user";
};

/**
 * @internal
 * AgentCreateResponseMessagesItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentCreateResponseMessagesItem = {
  content: any;
  role: "assistant" | "subcall" | "user";
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentCreateResponseMessagesItem
 */
const SchemaIn$AgentCreateResponseMessagesItem: z.ZodType<
  AgentCreateResponseMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    content: zodRequiredAny,
    role: z.enum(["assistant", "subcall", "user"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      role: "role",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentCreateResponseMessagesItem
 */
const SchemaOut$AgentCreateResponseMessagesItem: z.ZodType<
  External$AgentCreateResponseMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  AgentCreateResponseMessagesItem // the object to be transformed
> = z
  .object({
    content: zodRequiredAny,
    role: z.enum(["assistant", "subcall", "user"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      role: "role",
    });
  });

export const Schemas$AgentCreateResponseMessagesItem = {
  in: SchemaIn$AgentCreateResponseMessagesItem,
  out: SchemaOut$AgentCreateResponseMessagesItem,
};
