/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem
 */
export type AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem = {
  text?: string | undefined;
  type?: string | undefined;
};

/**
 * @internal
 * AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem =
  {
    text?: string | undefined;
    type?: string | undefined;
  };

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem
 */
const SchemaIn$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem: z.ZodType<
  AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    text: z.string().optional(),
    type: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      text: "text",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem
 */
const SchemaOut$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem: z.ZodType<
  External$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem // the object to be transformed
> = z
  .object({
    text: z.string().optional(),
    type: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      text: "text",
      type: "type",
    });
  });

export const Schemas$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem =
  {
    in: SchemaIn$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem,
    out: SchemaOut$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem,
  };
