/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * AgentBuildWorkflowCreateResponseResponseObj1ContentChatStatusEnum
 */
export type AgentBuildWorkflowCreateResponseResponseObj1ContentChatStatusEnum =
  | "ERROR"
  | "PROCESSED"
  | "PROCESSING";
