/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  AgentBuildWorkflowCreateResponseResponseObj1Content,
  External$AgentBuildWorkflowCreateResponseResponseObj1Content,
  Schemas$AgentBuildWorkflowCreateResponseResponseObj1Content,
} from "./agent-build-workflow-create-response-response-obj1-content";

/**
 * AgentBuildWorkflowCreateResponseResponseObj1
 */
export type AgentBuildWorkflowCreateResponseResponseObj1 = {
  content: AgentBuildWorkflowCreateResponseResponseObj1Content;
  type: "CHAT";
};

/**
 * @internal
 * AgentBuildWorkflowCreateResponseResponseObj1 without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowCreateResponseResponseObj1 = {
  content: External$AgentBuildWorkflowCreateResponseResponseObj1Content;
  type: "CHAT";
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowCreateResponseResponseObj1
 */
const SchemaIn$AgentBuildWorkflowCreateResponseResponseObj1: z.ZodType<
  AgentBuildWorkflowCreateResponseResponseObj1, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    content: Schemas$AgentBuildWorkflowCreateResponseResponseObj1Content.in,
    type: z.enum(["CHAT"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowCreateResponseResponseObj1
 */
const SchemaOut$AgentBuildWorkflowCreateResponseResponseObj1: z.ZodType<
  External$AgentBuildWorkflowCreateResponseResponseObj1, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowCreateResponseResponseObj1 // the object to be transformed
> = z
  .object({
    content: Schemas$AgentBuildWorkflowCreateResponseResponseObj1Content.out,
    type: z.enum(["CHAT"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      type: "type",
    });
  });

export const Schemas$AgentBuildWorkflowCreateResponseResponseObj1 = {
  in: SchemaIn$AgentBuildWorkflowCreateResponseResponseObj1,
  out: SchemaOut$AgentBuildWorkflowCreateResponseResponseObj1,
};
