/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  AgentBuildWorkflowCreateResponseResponseObj0Content,
  External$AgentBuildWorkflowCreateResponseResponseObj0Content,
  Schemas$AgentBuildWorkflowCreateResponseResponseObj0Content,
} from "./agent-build-workflow-create-response-response-obj0-content";

/**
 * AgentBuildWorkflowCreateResponseResponseObj0
 */
export type AgentBuildWorkflowCreateResponseResponseObj0 = {
  content: AgentBuildWorkflowCreateResponseResponseObj0Content;
  type: "OUTPUT";
};

/**
 * @internal
 * AgentBuildWorkflowCreateResponseResponseObj0 without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowCreateResponseResponseObj0 = {
  content: External$AgentBuildWorkflowCreateResponseResponseObj0Content;
  type: "OUTPUT";
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowCreateResponseResponseObj0
 */
const SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0: z.ZodType<
  AgentBuildWorkflowCreateResponseResponseObj0, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    content: Schemas$AgentBuildWorkflowCreateResponseResponseObj0Content.in,
    type: z.enum(["OUTPUT"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowCreateResponseResponseObj0
 */
const SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0: z.ZodType<
  External$AgentBuildWorkflowCreateResponseResponseObj0, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowCreateResponseResponseObj0 // the object to be transformed
> = z
  .object({
    content: Schemas$AgentBuildWorkflowCreateResponseResponseObj0Content.out,
    type: z.enum(["OUTPUT"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      type: "type",
    });
  });

export const Schemas$AgentBuildWorkflowCreateResponseResponseObj0 = {
  in: SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0,
  out: SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0,
};
