/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * AgentBuildWorkflowCreateResponseResponseObj0ContentStatus
 */
export type AgentBuildWorkflowCreateResponseResponseObj0ContentStatus = {
  message?: string | undefined;
  success?: boolean | undefined;
};

/**
 * @internal
 * AgentBuildWorkflowCreateResponseResponseObj0ContentStatus without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowCreateResponseResponseObj0ContentStatus =
  {
    message?: string | undefined;
    success?: boolean | undefined;
  };

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowCreateResponseResponseObj0ContentStatus
 */
const SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0ContentStatus: z.ZodType<
  AgentBuildWorkflowCreateResponseResponseObj0ContentStatus, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    message: z.string().optional(),
    success: z.boolean().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      message: "message",
      success: "success",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowCreateResponseResponseObj0ContentStatus
 */
const SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0ContentStatus: z.ZodType<
  External$AgentBuildWorkflowCreateResponseResponseObj0ContentStatus, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowCreateResponseResponseObj0ContentStatus // the object to be transformed
> = z
  .object({
    message: z.string().optional(),
    success: z.boolean().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      message: "message",
      success: "success",
    });
  });

export const Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentStatus =
  {
    in: SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0ContentStatus,
    out: SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0ContentStatus,
  };
