/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem
 */
export type AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem =
  {
    createdAt: string;
    description?: string | null | undefined;
    id: string;
    name: string;
    type: string;
    userId: string;

    // Index types must also accommodate all defined properties if present (typescript limitation)
    // In reality all additional properties should only have type `any`
    // (there might be some duplication here)
    [additionalProperty: string]:
      | string
      | (string | null | undefined)
      | string
      | string
      | string
      | string
      | any
      | null
      | undefined;
  };

/**
 * @internal
 * AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem =
  {
    created_at: string;
    description?: string | null | undefined;
    id: string;
    name: string;
    type: string;
    user_id: string;

    [additionalProperty: string]:
      | string
      | (string | null | undefined)
      | string
      | string
      | string
      | string
      | External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem
      | null
      | undefined;
  };

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem
 */
const SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem: z.ZodType<
  AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string(),
    description: z.string().nullable().optional(),
    id: z.string(),
    name: z.string(),
    type: z.string(),
    user_id: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      description: "description",
      id: "id",
      name: "name",
      type: "type",
      user_id: "userId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem
 */
const SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem: z.ZodType<
  External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem // the object to be transformed
> = z
  .object({
    createdAt: z.string(),
    description: z.string().nullable().optional(),
    id: z.string(),
    name: z.string(),
    type: z.string(),
    userId: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      description: "description",
      id: "id",
      name: "name",
      type: "type",
      userId: "user_id",
    });
  });

export const Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem =
  {
    in: SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem,
    out: SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem,
  };
