/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * AgentBuildWorkflowCreateResponseResponseObj0ContentChatStatusEnum
 */
export type AgentBuildWorkflowCreateResponseResponseObj0ContentChatStatusEnum =
  | "ERROR"
  | "PROCESSED"
  | "PROCESSING";
