/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  AgentBuildWorkflowCreateResponseResponseObj0ContentChatMessagesItem,
  External$AgentBuildWorkflowCreateResponseResponseObj0ContentChatMessagesItem,
  Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentChatMessagesItem,
} from "./agent-build-workflow-create-response-response-obj0-content-chat-messages-item";

/**
 * AgentBuildWorkflowCreateResponseResponseObj0ContentChat
 */
export type AgentBuildWorkflowCreateResponseResponseObj0ContentChat = {
  createdAt: string;
  id: string;
  messages: AgentBuildWorkflowCreateResponseResponseObj0ContentChatMessagesItem[];
  name: string;
  status: "ERROR" | "PROCESSED" | "PROCESSING";
  type: "AGENT/BUILD/WORKFLOW" | "DEEP_RESEARCH" | "RAG";
  userId: string;
};

/**
 * @internal
 * AgentBuildWorkflowCreateResponseResponseObj0ContentChat without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowCreateResponseResponseObj0ContentChat = {
  created_at: string;
  id: string;
  messages: External$AgentBuildWorkflowCreateResponseResponseObj0ContentChatMessagesItem[];
  name: string;
  status: "ERROR" | "PROCESSED" | "PROCESSING";
  type: "AGENT/BUILD/WORKFLOW" | "DEEP_RESEARCH" | "RAG";
  user_id: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowCreateResponseResponseObj0ContentChat
 */
const SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0ContentChat: z.ZodType<
  AgentBuildWorkflowCreateResponseResponseObj0ContentChat, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string(),
    id: z.string(),
    messages: z.array(
      Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentChatMessagesItem.in,
    ),
    name: z.string(),
    status: z.enum(["ERROR", "PROCESSED", "PROCESSING"]),
    type: z.enum(["AGENT/BUILD/WORKFLOW", "DEEP_RESEARCH", "RAG"]),
    user_id: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      id: "id",
      messages: "messages",
      name: "name",
      status: "status",
      type: "type",
      user_id: "userId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowCreateResponseResponseObj0ContentChat
 */
const SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0ContentChat: z.ZodType<
  External$AgentBuildWorkflowCreateResponseResponseObj0ContentChat, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowCreateResponseResponseObj0ContentChat // the object to be transformed
> = z
  .object({
    createdAt: z.string(),
    id: z.string(),
    messages: z.array(
      Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentChatMessagesItem.out,
    ),
    name: z.string(),
    status: z.enum(["ERROR", "PROCESSED", "PROCESSING"]),
    type: z.enum(["AGENT/BUILD/WORKFLOW", "DEEP_RESEARCH", "RAG"]),
    userId: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      id: "id",
      messages: "messages",
      name: "name",
      status: "status",
      type: "type",
      userId: "user_id",
    });
  });

export const Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentChat = {
  in: SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0ContentChat,
  out: SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0ContentChat,
};
