/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  AgentBuildWorkflowListResponseChat,
  External$AgentBuildWorkflowListResponseChat,
  Schemas$AgentBuildWorkflowListResponseChat,
} from "./agent-build-workflow-list-response-chat";
import {
  AgentBuildWorkflowListResponseMessagesItem,
  External$AgentBuildWorkflowListResponseMessagesItem,
  Schemas$AgentBuildWorkflowListResponseMessagesItem,
} from "./agent-build-workflow-list-response-messages-item";

/**
 * AgentBuildWorkflowListResponse
 */
export type AgentBuildWorkflowListResponse = {
  chat: AgentBuildWorkflowListResponseChat;
  messages: AgentBuildWorkflowListResponseMessagesItem[];
  output: Record<string, any | undefined>;
};

/**
 * @internal
 * AgentBuildWorkflowListResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowListResponse = {
  chat: External$AgentBuildWorkflowListResponseChat;
  messages: External$AgentBuildWorkflowListResponseMessagesItem[];
  output: Record<string, any | undefined>;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowListResponse
 */
const SchemaIn$AgentBuildWorkflowListResponse: z.ZodType<
  AgentBuildWorkflowListResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    chat: Schemas$AgentBuildWorkflowListResponseChat.in,
    messages: z.array(Schemas$AgentBuildWorkflowListResponseMessagesItem.in),
    output: z.record(z.string(), zodRequiredAny.optional()),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      chat: "chat",
      messages: "messages",
      output: "output",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowListResponse
 */
const SchemaOut$AgentBuildWorkflowListResponse: z.ZodType<
  External$AgentBuildWorkflowListResponse, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowListResponse // the object to be transformed
> = z
  .object({
    chat: Schemas$AgentBuildWorkflowListResponseChat.out,
    messages: z.array(Schemas$AgentBuildWorkflowListResponseMessagesItem.out),
    output: z.record(z.string(), zodRequiredAny.optional()),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      chat: "chat",
      messages: "messages",
      output: "output",
    });
  });

export const Schemas$AgentBuildWorkflowListResponse = {
  in: SchemaIn$AgentBuildWorkflowListResponse,
  out: SchemaOut$AgentBuildWorkflowListResponse,
};
