/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed,
  External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed,
  Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed,
} from "./agent-build-workflow-create-response-response-obj0-content-output-feed";
import {
  AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem,
  External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem,
  Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem,
} from "./agent-build-workflow-create-response-response-obj0-content-output-search-groups-item";
import {
  AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflow,
  External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflow,
  Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflow,
} from "./agent-build-workflow-create-response-response-obj0-content-output-workflow";
import {
  AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflowTasksItem,
  External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflowTasksItem,
  Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflowTasksItem,
} from "./agent-build-workflow-create-response-response-obj0-content-output-workflow-tasks-item";

/**
 * AgentBuildWorkflowCreateResponseResponseObj0ContentOutput
 */
export type AgentBuildWorkflowCreateResponseResponseObj0ContentOutput = {
  feed?:
    | AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed
    | undefined;
  searchGroups?:
    | AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem[]
    | undefined;
  workflow?:
    | AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflow
    | undefined;
  workflowTasks?:
    | AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflowTasksItem[]
    | undefined;
};

/**
 * @internal
 * AgentBuildWorkflowCreateResponseResponseObj0ContentOutput without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutput =
  {
    feed?:
      | External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed
      | undefined;
    search_groups?:
      | External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem[]
      | undefined;
    workflow?:
      | External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflow
      | undefined;
    workflow_tasks?:
      | External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflowTasksItem[]
      | undefined;
  };

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowCreateResponseResponseObj0ContentOutput
 */
const SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0ContentOutput: z.ZodType<
  AgentBuildWorkflowCreateResponseResponseObj0ContentOutput, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    feed: Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed.in.optional(),
    search_groups: z
      .array(
        Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem.in,
      )
      .optional(),
    workflow:
      Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflow.in.optional(),
    workflow_tasks: z
      .array(
        Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflowTasksItem.in,
      )
      .optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      feed: "feed",
      search_groups: "searchGroups",
      workflow: "workflow",
      workflow_tasks: "workflowTasks",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutput
 */
const SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0ContentOutput: z.ZodType<
  External$AgentBuildWorkflowCreateResponseResponseObj0ContentOutput, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowCreateResponseResponseObj0ContentOutput // the object to be transformed
> = z
  .object({
    feed: Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputFeed.out.optional(),
    searchGroups: z
      .array(
        Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputSearchGroupsItem.out,
      )
      .optional(),
    workflow:
      Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflow.out.optional(),
    workflowTasks: z
      .array(
        Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutputWorkflowTasksItem.out,
      )
      .optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      feed: "feed",
      searchGroups: "search_groups",
      workflow: "workflow",
      workflowTasks: "workflow_tasks",
    });
  });

export const Schemas$AgentBuildWorkflowCreateResponseResponseObj0ContentOutput =
  {
    in: SchemaIn$AgentBuildWorkflowCreateResponseResponseObj0ContentOutput,
    out: SchemaOut$AgentBuildWorkflowCreateResponseResponseObj0ContentOutput,
  };
