/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * AgentBuildWorkflowCreateBody
 */
export type AgentBuildWorkflowCreateBody = {
  message: string;
  stream?: boolean | null | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | (boolean | null | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * AgentBuildWorkflowCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowCreateBody = {
  message: string;
  stream?: boolean | null | undefined;

  [additionalProperty: string]:
    | string
    | (boolean | null | undefined)
    | External$AgentBuildWorkflowCreateBody
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowCreateBody
 */
const SchemaIn$AgentBuildWorkflowCreateBody: z.ZodType<
  AgentBuildWorkflowCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    message: z.string(),
    stream: z.boolean().nullable().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      message: "message",
      stream: "stream",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowCreateBody
 */
const SchemaOut$AgentBuildWorkflowCreateBody: z.ZodType<
  External$AgentBuildWorkflowCreateBody, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowCreateBody // the object to be transformed
> = z
  .object({
    message: z.string(),
    stream: z.boolean().nullable().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      message: "message",
      stream: "stream",
    });
  });

export const Schemas$AgentBuildWorkflowCreateBody = {
  in: SchemaIn$AgentBuildWorkflowCreateBody,
  out: SchemaOut$AgentBuildWorkflowCreateBody,
};
