/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * AgentBuildWorkflowListResponseMessagesItem
 */
export type AgentBuildWorkflowListResponseMessagesItem = {
  text?: string | undefined;
  type?: string | undefined;
};

/**
 * @internal
 * AgentBuildWorkflowListResponseMessagesItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowListResponseMessagesItem = {
  text?: string | undefined;
  type?: string | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowListResponseMessagesItem
 */
const SchemaIn$AgentBuildWorkflowListResponseMessagesItem: z.ZodType<
  AgentBuildWorkflowListResponseMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    text: z.string().optional(),
    type: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      text: "text",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowListResponseMessagesItem
 */
const SchemaOut$AgentBuildWorkflowListResponseMessagesItem: z.ZodType<
  External$AgentBuildWorkflowListResponseMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowListResponseMessagesItem // the object to be transformed
> = z
  .object({
    text: z.string().optional(),
    type: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      text: "text",
      type: "type",
    });
  });

export const Schemas$AgentBuildWorkflowListResponseMessagesItem = {
  in: SchemaIn$AgentBuildWorkflowListResponseMessagesItem,
  out: SchemaOut$AgentBuildWorkflowListResponseMessagesItem,
};
