/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * AgentAbortCreateResponse
 */
export type AgentAbortCreateResponse = {
  chatId: string;
  success: boolean;
};

/**
 * @internal
 * AgentAbortCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentAbortCreateResponse = {
  chat_id: string;
  success: boolean;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentAbortCreateResponse
 */
const SchemaIn$AgentAbortCreateResponse: z.ZodType<
  AgentAbortCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    chat_id: z.string(),
    success: z.boolean(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      chat_id: "chatId",
      success: "success",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentAbortCreateResponse
 */
const SchemaOut$AgentAbortCreateResponse: z.ZodType<
  External$AgentAbortCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  AgentAbortCreateResponse // the object to be transformed
> = z
  .object({
    chatId: z.string(),
    success: z.boolean(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      chatId: "chat_id",
      success: "success",
    });
  });

export const Schemas$AgentAbortCreateResponse = {
  in: SchemaIn$AgentAbortCreateResponse,
  out: SchemaOut$AgentAbortCreateResponse,
};
