/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  AgentBuildWorkflowListResponseChatMessagesItem,
  External$AgentBuildWorkflowListResponseChatMessagesItem,
  Schemas$AgentBuildWorkflowListResponseChatMessagesItem,
} from "./agent-build-workflow-list-response-chat-messages-item";

/**
 * AgentBuildWorkflowListResponseChat
 */
export type AgentBuildWorkflowListResponseChat = {
  createdAt: string;
  id: string;
  messages: AgentBuildWorkflowListResponseChatMessagesItem[];
  name: string;
  status: "ERROR" | "PROCESSED" | "PROCESSING";
  type: "AGENT/BUILD/WORKFLOW" | "DEEP_RESEARCH" | "RAG";
  userId: string;
};

/**
 * @internal
 * AgentBuildWorkflowListResponseChat without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowListResponseChat = {
  created_at: string;
  id: string;
  messages: External$AgentBuildWorkflowListResponseChatMessagesItem[];
  name: string;
  status: "ERROR" | "PROCESSED" | "PROCESSING";
  type: "AGENT/BUILD/WORKFLOW" | "DEEP_RESEARCH" | "RAG";
  user_id: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowListResponseChat
 */
const SchemaIn$AgentBuildWorkflowListResponseChat: z.ZodType<
  AgentBuildWorkflowListResponseChat, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string(),
    id: z.string(),
    messages: z.array(
      Schemas$AgentBuildWorkflowListResponseChatMessagesItem.in,
    ),
    name: z.string(),
    status: z.enum(["ERROR", "PROCESSED", "PROCESSING"]),
    type: z.enum(["AGENT/BUILD/WORKFLOW", "DEEP_RESEARCH", "RAG"]),
    user_id: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      id: "id",
      messages: "messages",
      name: "name",
      status: "status",
      type: "type",
      user_id: "userId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowListResponseChat
 */
const SchemaOut$AgentBuildWorkflowListResponseChat: z.ZodType<
  External$AgentBuildWorkflowListResponseChat, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowListResponseChat // the object to be transformed
> = z
  .object({
    createdAt: z.string(),
    id: z.string(),
    messages: z.array(
      Schemas$AgentBuildWorkflowListResponseChatMessagesItem.out,
    ),
    name: z.string(),
    status: z.enum(["ERROR", "PROCESSED", "PROCESSING"]),
    type: z.enum(["AGENT/BUILD/WORKFLOW", "DEEP_RESEARCH", "RAG"]),
    userId: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      id: "id",
      messages: "messages",
      name: "name",
      status: "status",
      type: "type",
      userId: "user_id",
    });
  });

export const Schemas$AgentBuildWorkflowListResponseChat = {
  in: SchemaIn$AgentBuildWorkflowListResponseChat,
  out: SchemaOut$AgentBuildWorkflowListResponseChat,
};
