/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * AgentBuildWorkflowCreateResponseResponseObj1ContentChatTypeEnum
 */
export type AgentBuildWorkflowCreateResponseResponseObj1ContentChatTypeEnum =
  | "AGENT/BUILD/WORKFLOW"
  | "DEEP_RESEARCH"
  | "RAG";
