/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  AgentBuildWorkflowCreateResponseResponseObj1ContentChat,
  External$AgentBuildWorkflowCreateResponseResponseObj1ContentChat,
  Schemas$AgentBuildWorkflowCreateResponseResponseObj1ContentChat,
} from "./agent-build-workflow-create-response-response-obj1-content-chat";
import {
  AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem,
  External$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem,
  Schemas$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem,
} from "./agent-build-workflow-create-response-response-obj1-content-messages-item";

/**
 * AgentBuildWorkflowCreateResponseResponseObj1Content
 */
export type AgentBuildWorkflowCreateResponseResponseObj1Content = {
  chat?: AgentBuildWorkflowCreateResponseResponseObj1ContentChat | undefined;
  messages?:
    | AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem[]
    | undefined;
};

/**
 * @internal
 * AgentBuildWorkflowCreateResponseResponseObj1Content without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowCreateResponseResponseObj1Content = {
  chat?:
    | External$AgentBuildWorkflowCreateResponseResponseObj1ContentChat
    | undefined;
  messages?:
    | External$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem[]
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowCreateResponseResponseObj1Content
 */
const SchemaIn$AgentBuildWorkflowCreateResponseResponseObj1Content: z.ZodType<
  AgentBuildWorkflowCreateResponseResponseObj1Content, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    chat: Schemas$AgentBuildWorkflowCreateResponseResponseObj1ContentChat.in.optional(),
    messages: z
      .array(
        Schemas$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem.in,
      )
      .optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      chat: "chat",
      messages: "messages",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowCreateResponseResponseObj1Content
 */
const SchemaOut$AgentBuildWorkflowCreateResponseResponseObj1Content: z.ZodType<
  External$AgentBuildWorkflowCreateResponseResponseObj1Content, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowCreateResponseResponseObj1Content // the object to be transformed
> = z
  .object({
    chat: Schemas$AgentBuildWorkflowCreateResponseResponseObj1ContentChat.out.optional(),
    messages: z
      .array(
        Schemas$AgentBuildWorkflowCreateResponseResponseObj1ContentMessagesItem.out,
      )
      .optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      chat: "chat",
      messages: "messages",
    });
  });

export const Schemas$AgentBuildWorkflowCreateResponseResponseObj1Content = {
  in: SchemaIn$AgentBuildWorkflowCreateResponseResponseObj1Content,
  out: SchemaOut$AgentBuildWorkflowCreateResponseResponseObj1Content,
};
