/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * AgentBuildWorkflowListResponseChatTypeEnum
 */
export type AgentBuildWorkflowListResponseChatTypeEnum =
  | "AGENT/BUILD/WORKFLOW"
  | "DEEP_RESEARCH"
  | "RAG";
