/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  AgentBuildWorkflowCreateResponseResponseObj0,
  External$AgentBuildWorkflowCreateResponseResponseObj0,
  Schemas$AgentBuildWorkflowCreateResponseResponseObj0,
} from "./agent-build-workflow-create-response-response-obj0";
import {
  AgentBuildWorkflowCreateResponseResponseObj1,
  External$AgentBuildWorkflowCreateResponseResponseObj1,
  Schemas$AgentBuildWorkflowCreateResponseResponseObj1,
} from "./agent-build-workflow-create-response-response-obj1";

/**
 * AgentBuildWorkflowCreateResponse
 */
export type AgentBuildWorkflowCreateResponse = {
  response?:
    | (
        | AgentBuildWorkflowCreateResponseResponseObj0
        | AgentBuildWorkflowCreateResponseResponseObj1
      )
    | undefined;
};

/**
 * @internal
 * AgentBuildWorkflowCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AgentBuildWorkflowCreateResponse = {
  response?:
    | (
        | External$AgentBuildWorkflowCreateResponseResponseObj0
        | External$AgentBuildWorkflowCreateResponseResponseObj1
      )
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AgentBuildWorkflowCreateResponse
 */
const SchemaIn$AgentBuildWorkflowCreateResponse: z.ZodType<
  AgentBuildWorkflowCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    response: z
      .union([
        Schemas$AgentBuildWorkflowCreateResponseResponseObj0.in,
        Schemas$AgentBuildWorkflowCreateResponseResponseObj1.in,
      ])
      .optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      response: "response",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AgentBuildWorkflowCreateResponse
 */
const SchemaOut$AgentBuildWorkflowCreateResponse: z.ZodType<
  External$AgentBuildWorkflowCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  AgentBuildWorkflowCreateResponse // the object to be transformed
> = z
  .object({
    response: z
      .union([
        Schemas$AgentBuildWorkflowCreateResponseResponseObj0.out,
        Schemas$AgentBuildWorkflowCreateResponseResponseObj1.out,
      ])
      .optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      response: "response",
    });
  });

export const Schemas$AgentBuildWorkflowCreateResponse = {
  in: SchemaIn$AgentBuildWorkflowCreateResponse,
  out: SchemaOut$AgentBuildWorkflowCreateResponse,
};
