/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * AgentBuildWorkflowListResponseChatStatusEnum
 */
export type AgentBuildWorkflowListResponseChatStatusEnum =
  | "ERROR"
  | "PROCESSED"
  | "PROCESSING";
