/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * AuthRefreshCreateBody
 */
export type AuthRefreshCreateBody = {
  refreshToken: string;
};

/**
 * @internal
 * AuthRefreshCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AuthRefreshCreateBody = {
  refresh_token: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AuthRefreshCreateBody
 */
const SchemaIn$AuthRefreshCreateBody: z.ZodType<
  AuthRefreshCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    refresh_token: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      refresh_token: "refreshToken",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AuthRefreshCreateBody
 */
const SchemaOut$AuthRefreshCreateBody: z.ZodType<
  External$AuthRefreshCreateBody, // output type of this zod object
  z.ZodTypeDef,
  AuthRefreshCreateBody // the object to be transformed
> = z
  .object({
    refreshToken: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      refreshToken: "refresh_token",
    });
  });

export const Schemas$AuthRefreshCreateBody = {
  in: SchemaIn$AuthRefreshCreateBody,
  out: SchemaOut$AuthRefreshCreateBody,
};
