/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * AuthRefreshCreateResponse
 */
export type AuthRefreshCreateResponse = {
  accessToken: string;
  expiresIn: number;
  refreshToken: string;
};

/**
 * @internal
 * AuthRefreshCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AuthRefreshCreateResponse = {
  access_token: string;
  expires_in: number;
  refresh_token: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AuthRefreshCreateResponse
 */
const SchemaIn$AuthRefreshCreateResponse: z.ZodType<
  AuthRefreshCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    access_token: z.string(),
    expires_in: z.number(),
    refresh_token: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      access_token: "accessToken",
      expires_in: "expiresIn",
      refresh_token: "refreshToken",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AuthRefreshCreateResponse
 */
const SchemaOut$AuthRefreshCreateResponse: z.ZodType<
  External$AuthRefreshCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  AuthRefreshCreateResponse // the object to be transformed
> = z
  .object({
    accessToken: z.string(),
    expiresIn: z.number(),
    refreshToken: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      accessToken: "access_token",
      expiresIn: "expires_in",
      refreshToken: "refresh_token",
    });
  });

export const Schemas$AuthRefreshCreateResponse = {
  in: SchemaIn$AuthRefreshCreateResponse,
  out: SchemaOut$AuthRefreshCreateResponse,
};
