/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * AuthLoginCreateBody
 */
export type AuthLoginCreateBody = {
  email: string;
  password: string;
};

/**
 * @internal
 * AuthLoginCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$AuthLoginCreateBody = {
  email: string;
  password: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object AuthLoginCreateBody
 */
const SchemaIn$AuthLoginCreateBody: z.ZodType<
  AuthLoginCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    email: z.string(),
    password: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      email: "email",
      password: "password",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$AuthLoginCreateBody
 */
const SchemaOut$AuthLoginCreateBody: z.ZodType<
  External$AuthLoginCreateBody, // output type of this zod object
  z.ZodTypeDef,
  AuthLoginCreateBody // the object to be transformed
> = z
  .object({
    email: z.string(),
    password: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      email: "email",
      password: "password",
    });
  });

export const Schemas$AuthLoginCreateBody = {
  in: SchemaIn$AuthLoginCreateBody,
  out: SchemaOut$AuthLoginCreateBody,
};
