/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * ChatsCreateBody
 */
export type ChatsCreateBody = {
  endDate: string;
  feedId: string;
  isWebSearchEnabled?: boolean | null | undefined;
  query: string;
  startDate: string;
};

/**
 * @internal
 * ChatsCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ChatsCreateBody = {
  end_date: string;
  feed_id: string;
  is_web_search_enabled?: boolean | null | undefined;
  query: string;
  start_date: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ChatsCreateBody
 */
const SchemaIn$ChatsCreateBody: z.ZodType<
  ChatsCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    end_date: z.string(),
    feed_id: z.string(),
    is_web_search_enabled: z.boolean().nullable().optional(),
    query: z.string(),
    start_date: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      end_date: "endDate",
      feed_id: "feedId",
      is_web_search_enabled: "isWebSearchEnabled",
      query: "query",
      start_date: "startDate",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ChatsCreateBody
 */
const SchemaOut$ChatsCreateBody: z.ZodType<
  External$ChatsCreateBody, // output type of this zod object
  z.ZodTypeDef,
  ChatsCreateBody // the object to be transformed
> = z
  .object({
    endDate: z.string(),
    feedId: z.string(),
    isWebSearchEnabled: z.boolean().nullable().optional(),
    query: z.string(),
    startDate: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      endDate: "end_date",
      feedId: "feed_id",
      isWebSearchEnabled: "is_web_search_enabled",
      query: "query",
      startDate: "start_date",
    });
  });

export const Schemas$ChatsCreateBody = {
  in: SchemaIn$ChatsCreateBody,
  out: SchemaOut$ChatsCreateBody,
};
