/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  ChatsGetResponseMessagesItem,
  External$ChatsGetResponseMessagesItem,
  Schemas$ChatsGetResponseMessagesItem,
} from "./chats-get-response-messages-item";

/**
 * ChatsGetResponse
 */
export type ChatsGetResponse = {
  createdAt: string;
  id: string;
  messages: ChatsGetResponseMessagesItem[];
  name: string;
  status: "ERROR" | "PROCESSED" | "PROCESSING";
  type: "AGENT/BUILD/WORKFLOW" | "DEEP_RESEARCH" | "RAG";
  userId: string;
};

/**
 * @internal
 * ChatsGetResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ChatsGetResponse = {
  created_at: string;
  id: string;
  messages: External$ChatsGetResponseMessagesItem[];
  name: string;
  status: "ERROR" | "PROCESSED" | "PROCESSING";
  type: "AGENT/BUILD/WORKFLOW" | "DEEP_RESEARCH" | "RAG";
  user_id: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ChatsGetResponse
 */
const SchemaIn$ChatsGetResponse: z.ZodType<
  ChatsGetResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string(),
    id: z.string(),
    messages: z.array(Schemas$ChatsGetResponseMessagesItem.in),
    name: z.string(),
    status: z.enum(["ERROR", "PROCESSED", "PROCESSING"]),
    type: z.enum(["AGENT/BUILD/WORKFLOW", "DEEP_RESEARCH", "RAG"]),
    user_id: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      id: "id",
      messages: "messages",
      name: "name",
      status: "status",
      type: "type",
      user_id: "userId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ChatsGetResponse
 */
const SchemaOut$ChatsGetResponse: z.ZodType<
  External$ChatsGetResponse, // output type of this zod object
  z.ZodTypeDef,
  ChatsGetResponse // the object to be transformed
> = z
  .object({
    createdAt: z.string(),
    id: z.string(),
    messages: z.array(Schemas$ChatsGetResponseMessagesItem.out),
    name: z.string(),
    status: z.enum(["ERROR", "PROCESSED", "PROCESSING"]),
    type: z.enum(["AGENT/BUILD/WORKFLOW", "DEEP_RESEARCH", "RAG"]),
    userId: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      id: "id",
      messages: "messages",
      name: "name",
      status: "status",
      type: "type",
      userId: "user_id",
    });
  });

export const Schemas$ChatsGetResponse = {
  in: SchemaIn$ChatsGetResponse,
  out: SchemaOut$ChatsGetResponse,
};
