/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * ChatsPatchResponseMessagesItem
 */
export type ChatsPatchResponseMessagesItem = {
  content: string;
  role: "assistant" | "user";
};

/**
 * @internal
 * ChatsPatchResponseMessagesItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ChatsPatchResponseMessagesItem = {
  content: string;
  role: "assistant" | "user";
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ChatsPatchResponseMessagesItem
 */
const SchemaIn$ChatsPatchResponseMessagesItem: z.ZodType<
  ChatsPatchResponseMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    content: z.string(),
    role: z.enum(["assistant", "user"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      role: "role",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ChatsPatchResponseMessagesItem
 */
const SchemaOut$ChatsPatchResponseMessagesItem: z.ZodType<
  External$ChatsPatchResponseMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  ChatsPatchResponseMessagesItem // the object to be transformed
> = z
  .object({
    content: z.string(),
    role: z.enum(["assistant", "user"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      role: "role",
    });
  });

export const Schemas$ChatsPatchResponseMessagesItem = {
  in: SchemaIn$ChatsPatchResponseMessagesItem,
  out: SchemaOut$ChatsPatchResponseMessagesItem,
};
