/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * ChatsCreateResponseMessagesItem
 */
export type ChatsCreateResponseMessagesItem = {
  content: string;
  role: "assistant" | "user";
};

/**
 * @internal
 * ChatsCreateResponseMessagesItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ChatsCreateResponseMessagesItem = {
  content: string;
  role: "assistant" | "user";
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ChatsCreateResponseMessagesItem
 */
const SchemaIn$ChatsCreateResponseMessagesItem: z.ZodType<
  ChatsCreateResponseMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    content: z.string(),
    role: z.enum(["assistant", "user"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      role: "role",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ChatsCreateResponseMessagesItem
 */
const SchemaOut$ChatsCreateResponseMessagesItem: z.ZodType<
  External$ChatsCreateResponseMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  ChatsCreateResponseMessagesItem // the object to be transformed
> = z
  .object({
    content: z.string(),
    role: z.enum(["assistant", "user"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      role: "role",
    });
  });

export const Schemas$ChatsCreateResponseMessagesItem = {
  in: SchemaIn$ChatsCreateResponseMessagesItem,
  out: SchemaOut$ChatsCreateResponseMessagesItem,
};
