/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * DatastoreListResponseItemTypeEnum
 */
export type DatastoreListResponseItemTypeEnum =
  | "DATABASE_COLUMNAR"
  | "DATABASE_TRADITIONAL"
  | "FILE_STORE"
  | "VECTOR_STORE";
