/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * DatastoreGetResponse
 */
export type DatastoreGetResponse = {
  config?: Record<string, any | undefined> | null | undefined;
  createdAt: string;
  description?: string | null | undefined;
  id: string;
  name: string;
  /**
   * JSON Schema for DATABASE_* datastore types
   */
  schema?: Record<string, any | undefined> | null | undefined;
  type:
    | "DATABASE_COLUMNAR"
    | "DATABASE_TRADITIONAL"
    | "FILE_STORE"
    | "VECTOR_STORE";
  userId: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (Record<string, any | undefined> | null | undefined)
    | string
    | (string | null | undefined)
    | string
    | string
    | (Record<string, any | undefined> | null | undefined)
    | (
        | "DATABASE_COLUMNAR"
        | "DATABASE_TRADITIONAL"
        | "FILE_STORE"
        | "VECTOR_STORE"
      )
    | string
    | any
    | null
    | undefined;
};

/**
 * @internal
 * DatastoreGetResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$DatastoreGetResponse = {
  config?: Record<string, any | undefined> | null | undefined;
  created_at: string;
  description?: string | null | undefined;
  id: string;
  name: string;
  schema?: Record<string, any | undefined> | null | undefined;
  type:
    | "DATABASE_COLUMNAR"
    | "DATABASE_TRADITIONAL"
    | "FILE_STORE"
    | "VECTOR_STORE";
  user_id: string;

  [additionalProperty: string]:
    | (Record<string, any | undefined> | null | undefined)
    | string
    | (string | null | undefined)
    | string
    | string
    | (Record<string, any | undefined> | null | undefined)
    | (
        | "DATABASE_COLUMNAR"
        | "DATABASE_TRADITIONAL"
        | "FILE_STORE"
        | "VECTOR_STORE"
      )
    | string
    | External$DatastoreGetResponse
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object DatastoreGetResponse
 */
const SchemaIn$DatastoreGetResponse: z.ZodType<
  DatastoreGetResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    config: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    created_at: z.string(),
    description: z.string().nullable().optional(),
    id: z.string(),
    name: z.string(),
    schema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    type: z.enum([
      "DATABASE_COLUMNAR",
      "DATABASE_TRADITIONAL",
      "FILE_STORE",
      "VECTOR_STORE",
    ]),
    user_id: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      created_at: "createdAt",
      description: "description",
      id: "id",
      name: "name",
      schema: "schema",
      type: "type",
      user_id: "userId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$DatastoreGetResponse
 */
const SchemaOut$DatastoreGetResponse: z.ZodType<
  External$DatastoreGetResponse, // output type of this zod object
  z.ZodTypeDef,
  DatastoreGetResponse // the object to be transformed
> = z
  .object({
    config: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    createdAt: z.string(),
    description: z.string().nullable().optional(),
    id: z.string(),
    name: z.string(),
    schema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    type: z.enum([
      "DATABASE_COLUMNAR",
      "DATABASE_TRADITIONAL",
      "FILE_STORE",
      "VECTOR_STORE",
    ]),
    userId: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      createdAt: "created_at",
      description: "description",
      id: "id",
      name: "name",
      schema: "schema",
      type: "type",
      userId: "user_id",
    });
  });

export const Schemas$DatastoreGetResponse = {
  in: SchemaIn$DatastoreGetResponse,
  out: SchemaOut$DatastoreGetResponse,
};
