/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * DatastoreCreateBody
 */
export type DatastoreCreateBody = {
  /**
   * Optional config object
   */
  config?: Record<string, any | undefined> | null | undefined;
  /**
   * Description of the datastore
   */
  description: string;
  /**
   * Name of the datastore
   */
  name: string;
  /**
   * JSON Schema (required for DATABASE_* types)
   */
  schema?: Record<string, any | undefined> | null | undefined;
  /**
   * The datastore type
   */
  type:
    | "DATABASE_COLUMNAR"
    | "DATABASE_TRADITIONAL"
    | "FILE_STORE"
    | "VECTOR_STORE";

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (Record<string, any | undefined> | null | undefined)
    | string
    | string
    | (Record<string, any | undefined> | null | undefined)
    | (
        | "DATABASE_COLUMNAR"
        | "DATABASE_TRADITIONAL"
        | "FILE_STORE"
        | "VECTOR_STORE"
      )
    | any
    | null
    | undefined;
};

/**
 * @internal
 * DatastoreCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$DatastoreCreateBody = {
  config?: Record<string, any | undefined> | null | undefined;
  description: string;
  name: string;
  schema?: Record<string, any | undefined> | null | undefined;
  type:
    | "DATABASE_COLUMNAR"
    | "DATABASE_TRADITIONAL"
    | "FILE_STORE"
    | "VECTOR_STORE";

  [additionalProperty: string]:
    | (Record<string, any | undefined> | null | undefined)
    | string
    | string
    | (Record<string, any | undefined> | null | undefined)
    | (
        | "DATABASE_COLUMNAR"
        | "DATABASE_TRADITIONAL"
        | "FILE_STORE"
        | "VECTOR_STORE"
      )
    | External$DatastoreCreateBody
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object DatastoreCreateBody
 */
const SchemaIn$DatastoreCreateBody: z.ZodType<
  DatastoreCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    config: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    description: z.string(),
    name: z.string(),
    schema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    type: z.enum([
      "DATABASE_COLUMNAR",
      "DATABASE_TRADITIONAL",
      "FILE_STORE",
      "VECTOR_STORE",
    ]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      description: "description",
      name: "name",
      schema: "schema",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$DatastoreCreateBody
 */
const SchemaOut$DatastoreCreateBody: z.ZodType<
  External$DatastoreCreateBody, // output type of this zod object
  z.ZodTypeDef,
  DatastoreCreateBody // the object to be transformed
> = z
  .object({
    config: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    description: z.string(),
    name: z.string(),
    schema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    type: z.enum([
      "DATABASE_COLUMNAR",
      "DATABASE_TRADITIONAL",
      "FILE_STORE",
      "VECTOR_STORE",
    ]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      description: "description",
      name: "name",
      schema: "schema",
      type: "type",
    });
  });

export const Schemas$DatastoreCreateBody = {
  in: SchemaIn$DatastoreCreateBody,
  out: SchemaOut$DatastoreCreateBody,
};
