/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * DatastoreCreateResponseTypeEnum
 */
export type DatastoreCreateResponseTypeEnum =
  | "DATABASE_COLUMNAR"
  | "DATABASE_TRADITIONAL"
  | "FILE_STORE"
  | "VECTOR_STORE";
