/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * DatastoreQueryCreateResponse
 */
export type DatastoreQueryCreateResponse = {
  data: string | Record<string, any | undefined>[];

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (string | Record<string, any | undefined>[])
    | any
    | null
    | undefined;
};

/**
 * @internal
 * DatastoreQueryCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$DatastoreQueryCreateResponse = {
  data: string | Record<string, any | undefined>[];

  [additionalProperty: string]:
    | (string | Record<string, any | undefined>[])
    | External$DatastoreQueryCreateResponse
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object DatastoreQueryCreateResponse
 */
const SchemaIn$DatastoreQueryCreateResponse: z.ZodType<
  DatastoreQueryCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    data: z.union([
      z.string(),
      z.array(z.record(z.string(), zodRequiredAny.optional())),
    ]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$DatastoreQueryCreateResponse
 */
const SchemaOut$DatastoreQueryCreateResponse: z.ZodType<
  External$DatastoreQueryCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  DatastoreQueryCreateResponse // the object to be transformed
> = z
  .object({
    data: z.union([
      z.string(),
      z.array(z.record(z.string(), zodRequiredAny.optional())),
    ]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
    });
  });

export const Schemas$DatastoreQueryCreateResponse = {
  in: SchemaIn$DatastoreQueryCreateResponse,
  out: SchemaOut$DatastoreQueryCreateResponse,
};
