/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Encoding of the `data` field. Use `base64` to upload binary data via JSON.
 */
export type DatastoreItemsCreateBodyEncodingEnum = "base64" | "utf8";
