/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * A datastore item entry.
 */
export type DatastoreItemsListResponseItemObj1 = {
  createdAt: string;
  datastoreId: string;
  description?: string | null | undefined;
  id: string;
  metadata?: Record<string, any | undefined> | null | undefined;
  name: string;
  path?: string | null | undefined;
  type: "item";

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | string
    | (string | null | undefined)
    | string
    | (Record<string, any | undefined> | null | undefined)
    | string
    | (string | null | undefined)
    | "item"
    | any
    | null
    | undefined;
};

/**
 * @internal
 * DatastoreItemsListResponseItemObj1 without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$DatastoreItemsListResponseItemObj1 = {
  created_at: string;
  datastore_id: string;
  description?: string | null | undefined;
  id: string;
  metadata?: Record<string, any | undefined> | null | undefined;
  name: string;
  path?: string | null | undefined;
  type: "item";

  [additionalProperty: string]:
    | string
    | string
    | (string | null | undefined)
    | string
    | (Record<string, any | undefined> | null | undefined)
    | string
    | (string | null | undefined)
    | "item"
    | External$DatastoreItemsListResponseItemObj1
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object DatastoreItemsListResponseItemObj1
 */
const SchemaIn$DatastoreItemsListResponseItemObj1: z.ZodType<
  DatastoreItemsListResponseItemObj1, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string(),
    datastore_id: z.string(),
    description: z.string().nullable().optional(),
    id: z.string(),
    metadata: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    name: z.string(),
    path: z.string().nullable().optional(),
    type: z.enum(["item"]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      datastore_id: "datastoreId",
      description: "description",
      id: "id",
      metadata: "metadata",
      name: "name",
      path: "path",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$DatastoreItemsListResponseItemObj1
 */
const SchemaOut$DatastoreItemsListResponseItemObj1: z.ZodType<
  External$DatastoreItemsListResponseItemObj1, // output type of this zod object
  z.ZodTypeDef,
  DatastoreItemsListResponseItemObj1 // the object to be transformed
> = z
  .object({
    createdAt: z.string(),
    datastoreId: z.string(),
    description: z.string().nullable().optional(),
    id: z.string(),
    metadata: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    name: z.string(),
    path: z.string().nullable().optional(),
    type: z.enum(["item"]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      datastoreId: "datastore_id",
      description: "description",
      id: "id",
      metadata: "metadata",
      name: "name",
      path: "path",
      type: "type",
    });
  });

export const Schemas$DatastoreItemsListResponseItemObj1 = {
  in: SchemaIn$DatastoreItemsListResponseItemObj1,
  out: SchemaOut$DatastoreItemsListResponseItemObj1,
};
