/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * FeedsVectorSearchCreateResponseItem
 */
export type FeedsVectorSearchCreateResponseItem = {
  chunkIndex: number;
  content?: string | undefined;
  createdAt: string;
  id: string;
  resourceId: string;
  resourceType: "feed_handler_output" | "feed_item";
  similarity: number;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | number
    | (string | undefined)
    | string
    | string
    | string
    | ("feed_handler_output" | "feed_item")
    | number
    | any
    | null
    | undefined;
};

/**
 * @internal
 * FeedsVectorSearchCreateResponseItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$FeedsVectorSearchCreateResponseItem = {
  chunk_index: number;
  content?: string | undefined;
  created_at: string;
  id: string;
  resource_id: string;
  resource_type: "feed_handler_output" | "feed_item";
  similarity: number;

  [additionalProperty: string]:
    | number
    | (string | undefined)
    | string
    | string
    | string
    | ("feed_handler_output" | "feed_item")
    | number
    | External$FeedsVectorSearchCreateResponseItem
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object FeedsVectorSearchCreateResponseItem
 */
const SchemaIn$FeedsVectorSearchCreateResponseItem: z.ZodType<
  FeedsVectorSearchCreateResponseItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    chunk_index: z.number().int(),
    content: z.string().optional(),
    created_at: z.string(),
    id: z.string(),
    resource_id: z.string(),
    resource_type: z.enum(["feed_handler_output", "feed_item"]),
    similarity: z.number(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      chunk_index: "chunkIndex",
      content: "content",
      created_at: "createdAt",
      id: "id",
      resource_id: "resourceId",
      resource_type: "resourceType",
      similarity: "similarity",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$FeedsVectorSearchCreateResponseItem
 */
const SchemaOut$FeedsVectorSearchCreateResponseItem: z.ZodType<
  External$FeedsVectorSearchCreateResponseItem, // output type of this zod object
  z.ZodTypeDef,
  FeedsVectorSearchCreateResponseItem // the object to be transformed
> = z
  .object({
    chunkIndex: z.number().int(),
    content: z.string().optional(),
    createdAt: z.string(),
    id: z.string(),
    resourceId: z.string(),
    resourceType: z.enum(["feed_handler_output", "feed_item"]),
    similarity: z.number(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      chunkIndex: "chunk_index",
      content: "content",
      createdAt: "created_at",
      id: "id",
      resourceId: "resource_id",
      resourceType: "resource_type",
      similarity: "similarity",
    });
  });

export const Schemas$FeedsVectorSearchCreateResponseItem = {
  in: SchemaIn$FeedsVectorSearchCreateResponseItem,
  out: SchemaOut$FeedsVectorSearchCreateResponseItem,
};
