/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$FeedsItemsCreateBodyOptions,
  FeedsItemsCreateBodyOptions,
  Schemas$FeedsItemsCreateBodyOptions,
} from "./feeds-items-create-body-options";

/**
 * FeedsItemsCreateBody
 */
export type FeedsItemsCreateBody = {
  data: Record<string, any | undefined>;
  feedId: string;
  metadata: Record<string, any | undefined>;
  options?: FeedsItemsCreateBodyOptions | undefined;
};

/**
 * @internal
 * FeedsItemsCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$FeedsItemsCreateBody = {
  data: Record<string, any | undefined>;
  feed_id: string;
  metadata: Record<string, any | undefined>;
  options?: External$FeedsItemsCreateBodyOptions | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object FeedsItemsCreateBody
 */
const SchemaIn$FeedsItemsCreateBody: z.ZodType<
  FeedsItemsCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    data: z.record(z.string(), zodRequiredAny.optional()),
    feed_id: z.string(),
    metadata: z.record(z.string(), zodRequiredAny.optional()),
    options: Schemas$FeedsItemsCreateBodyOptions.in.optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
      feed_id: "feedId",
      metadata: "metadata",
      options: "options",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$FeedsItemsCreateBody
 */
const SchemaOut$FeedsItemsCreateBody: z.ZodType<
  External$FeedsItemsCreateBody, // output type of this zod object
  z.ZodTypeDef,
  FeedsItemsCreateBody // the object to be transformed
> = z
  .object({
    data: z.record(z.string(), zodRequiredAny.optional()),
    feedId: z.string(),
    metadata: z.record(z.string(), zodRequiredAny.optional()),
    options: Schemas$FeedsItemsCreateBodyOptions.out.optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
      feedId: "feed_id",
      metadata: "metadata",
      options: "options",
    });
  });

export const Schemas$FeedsItemsCreateBody = {
  in: SchemaIn$FeedsItemsCreateBody,
  out: SchemaOut$FeedsItemsCreateBody,
};
