/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$FeedsCreateBodyConfigObj0,
  FeedsCreateBodyConfigObj0,
  Schemas$FeedsCreateBodyConfigObj0,
} from "./feeds-create-body-config-obj0";
import {
  External$FeedsCreateBodyConfigObj2,
  FeedsCreateBodyConfigObj2,
  Schemas$FeedsCreateBodyConfigObj2,
} from "./feeds-create-body-config-obj2";

/**
 * FeedsCreateBody
 */
export type FeedsCreateBody = {
  config:
    | FeedsCreateBodyConfigObj0
    | Record<string, any | undefined>
    | FeedsCreateBodyConfigObj2;
  description: string;
  feedType: "API" | "CHRONJOB" | "EMAIL";
  name: string;
};

/**
 * @internal
 * FeedsCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$FeedsCreateBody = {
  config:
    | External$FeedsCreateBodyConfigObj0
    | Record<string, any | undefined>
    | External$FeedsCreateBodyConfigObj2;
  description: string;
  feed_type: "API" | "CHRONJOB" | "EMAIL";
  name: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object FeedsCreateBody
 */
const SchemaIn$FeedsCreateBody: z.ZodType<
  FeedsCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    config: z.union([
      Schemas$FeedsCreateBodyConfigObj0.in,
      z.record(z.string(), zodRequiredAny.optional()),
      Schemas$FeedsCreateBodyConfigObj2.in,
    ]),
    description: z.string(),
    feed_type: z.enum(["API", "CHRONJOB", "EMAIL"]),
    name: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      description: "description",
      feed_type: "feedType",
      name: "name",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$FeedsCreateBody
 */
const SchemaOut$FeedsCreateBody: z.ZodType<
  External$FeedsCreateBody, // output type of this zod object
  z.ZodTypeDef,
  FeedsCreateBody // the object to be transformed
> = z
  .object({
    config: z.union([
      Schemas$FeedsCreateBodyConfigObj0.out,
      z.record(z.string(), zodRequiredAny.optional()),
      Schemas$FeedsCreateBodyConfigObj2.out,
    ]),
    description: z.string(),
    feedType: z.enum(["API", "CHRONJOB", "EMAIL"]),
    name: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      description: "description",
      feedType: "feed_type",
      name: "name",
    });
  });

export const Schemas$FeedsCreateBody = {
  in: SchemaIn$FeedsCreateBody,
  out: SchemaOut$FeedsCreateBody,
};
