/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * FeedsItemsCreateResponseWorkflowRunsItem
 */
export type FeedsItemsCreateResponseWorkflowRunsItem = {
  createdAt?: string | undefined;
  id: string;
  workflowId: string;
};

/**
 * @internal
 * FeedsItemsCreateResponseWorkflowRunsItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$FeedsItemsCreateResponseWorkflowRunsItem = {
  created_at?: string | undefined;
  id: string;
  workflow_id: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object FeedsItemsCreateResponseWorkflowRunsItem
 */
const SchemaIn$FeedsItemsCreateResponseWorkflowRunsItem: z.ZodType<
  FeedsItemsCreateResponseWorkflowRunsItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string().optional(),
    id: z.string(),
    workflow_id: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      id: "id",
      workflow_id: "workflowId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$FeedsItemsCreateResponseWorkflowRunsItem
 */
const SchemaOut$FeedsItemsCreateResponseWorkflowRunsItem: z.ZodType<
  External$FeedsItemsCreateResponseWorkflowRunsItem, // output type of this zod object
  z.ZodTypeDef,
  FeedsItemsCreateResponseWorkflowRunsItem // the object to be transformed
> = z
  .object({
    createdAt: z.string().optional(),
    id: z.string(),
    workflowId: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      id: "id",
      workflowId: "workflow_id",
    });
  });

export const Schemas$FeedsItemsCreateResponseWorkflowRunsItem = {
  in: SchemaIn$FeedsItemsCreateResponseWorkflowRunsItem,
  out: SchemaOut$FeedsItemsCreateResponseWorkflowRunsItem,
};
