/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * The configuration for a CRONJOB feed
 */
export type FeedsCreateBodyConfigObj2 = {
  /**
   * The interval in minutes between each execution
   */
  interval: number;
  /**
   * The ID of the script to execute
   */
  scriptId: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]: number | string | any | null | undefined;
};

/**
 * @internal
 * FeedsCreateBodyConfigObj2 without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$FeedsCreateBodyConfigObj2 = {
  interval: number;
  script_id: string;

  [additionalProperty: string]:
    | number
    | string
    | External$FeedsCreateBodyConfigObj2
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object FeedsCreateBodyConfigObj2
 */
const SchemaIn$FeedsCreateBodyConfigObj2: z.ZodType<
  FeedsCreateBodyConfigObj2, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    interval: z.number(),
    script_id: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      interval: "interval",
      script_id: "scriptId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$FeedsCreateBodyConfigObj2
 */
const SchemaOut$FeedsCreateBodyConfigObj2: z.ZodType<
  External$FeedsCreateBodyConfigObj2, // output type of this zod object
  z.ZodTypeDef,
  FeedsCreateBodyConfigObj2 // the object to be transformed
> = z
  .object({
    interval: z.number(),
    scriptId: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      interval: "interval",
      scriptId: "script_id",
    });
  });

export const Schemas$FeedsCreateBodyConfigObj2 = {
  in: SchemaIn$FeedsCreateBodyConfigObj2,
  out: SchemaOut$FeedsCreateBodyConfigObj2,
};
