/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * FeedsItemsCreateBodyOptions
 */
export type FeedsItemsCreateBodyOptions = {
  /**
   * If true, no workflow runs will be created for the feed item.
   */
  disableWorkflowExecution?: boolean | undefined;
};

/**
 * @internal
 * FeedsItemsCreateBodyOptions without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$FeedsItemsCreateBodyOptions = {
  disable_workflow_execution?: boolean | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object FeedsItemsCreateBodyOptions
 */
const SchemaIn$FeedsItemsCreateBodyOptions: z.ZodType<
  FeedsItemsCreateBodyOptions, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    disable_workflow_execution: z.boolean().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      disable_workflow_execution: "disableWorkflowExecution",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$FeedsItemsCreateBodyOptions
 */
const SchemaOut$FeedsItemsCreateBodyOptions: z.ZodType<
  External$FeedsItemsCreateBodyOptions, // output type of this zod object
  z.ZodTypeDef,
  FeedsItemsCreateBodyOptions // the object to be transformed
> = z
  .object({
    disableWorkflowExecution: z.boolean().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      disableWorkflowExecution: "disable_workflow_execution",
    });
  });

export const Schemas$FeedsItemsCreateBodyOptions = {
  in: SchemaIn$FeedsItemsCreateBodyOptions,
  out: SchemaOut$FeedsItemsCreateBodyOptions,
};
