/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * FeedsVectorSearchCreateResponseItemResourceTypeEnum
 */
export type FeedsVectorSearchCreateResponseItemResourceTypeEnum =
  | "feed_handler_output"
  | "feed_item";
