/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * IntegrationsApiOperationsGetResponseMethodEnum
 */
export type IntegrationsApiOperationsGetResponseMethodEnum =
  | "DELETE"
  | "GET"
  | "HEAD"
  | "OPTIONS"
  | "PATCH"
  | "POST"
  | "PUT";
