/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * IntegrationsApiSecretsDeleteResponse
 */
export type IntegrationsApiSecretsDeleteResponse = {
  message?: string | undefined;
};

/**
 * @internal
 * IntegrationsApiSecretsDeleteResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$IntegrationsApiSecretsDeleteResponse = {
  message?: string | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object IntegrationsApiSecretsDeleteResponse
 */
const SchemaIn$IntegrationsApiSecretsDeleteResponse: z.ZodType<
  IntegrationsApiSecretsDeleteResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    message: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      message: "message",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$IntegrationsApiSecretsDeleteResponse
 */
const SchemaOut$IntegrationsApiSecretsDeleteResponse: z.ZodType<
  External$IntegrationsApiSecretsDeleteResponse, // output type of this zod object
  z.ZodTypeDef,
  IntegrationsApiSecretsDeleteResponse // the object to be transformed
> = z
  .object({
    message: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      message: "message",
    });
  });

export const Schemas$IntegrationsApiSecretsDeleteResponse = {
  in: SchemaIn$IntegrationsApiSecretsDeleteResponse,
  out: SchemaOut$IntegrationsApiSecretsDeleteResponse,
};
