/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * IntegrationsApiOperationsDeleteResponse
 */
export type IntegrationsApiOperationsDeleteResponse = {
  message?: string | undefined;
};

/**
 * @internal
 * IntegrationsApiOperationsDeleteResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$IntegrationsApiOperationsDeleteResponse = {
  message?: string | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object IntegrationsApiOperationsDeleteResponse
 */
const SchemaIn$IntegrationsApiOperationsDeleteResponse: z.ZodType<
  IntegrationsApiOperationsDeleteResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    message: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      message: "message",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$IntegrationsApiOperationsDeleteResponse
 */
const SchemaOut$IntegrationsApiOperationsDeleteResponse: z.ZodType<
  External$IntegrationsApiOperationsDeleteResponse, // output type of this zod object
  z.ZodTypeDef,
  IntegrationsApiOperationsDeleteResponse // the object to be transformed
> = z
  .object({
    message: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      message: "message",
    });
  });

export const Schemas$IntegrationsApiOperationsDeleteResponse = {
  in: SchemaIn$IntegrationsApiOperationsDeleteResponse,
  out: SchemaOut$IntegrationsApiOperationsDeleteResponse,
};
