/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * IntegrationsApiOperationsPatchBody
 */
export type IntegrationsApiOperationsPatchBody = {
  method?:
    | ("DELETE" | "GET" | "HEAD" | "OPTIONS" | "PATCH" | "POST" | "PUT")
    | undefined;
  path?: string | undefined;
  payloadSchema?: Record<string, any | undefined> | null | undefined;
};

/**
 * @internal
 * IntegrationsApiOperationsPatchBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$IntegrationsApiOperationsPatchBody = {
  method?:
    | ("DELETE" | "GET" | "HEAD" | "OPTIONS" | "PATCH" | "POST" | "PUT")
    | undefined;
  path?: string | undefined;
  payload_schema?: Record<string, any | undefined> | null | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object IntegrationsApiOperationsPatchBody
 */
const SchemaIn$IntegrationsApiOperationsPatchBody: z.ZodType<
  IntegrationsApiOperationsPatchBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    method: z
      .enum(["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"])
      .optional(),
    path: z.string().optional(),
    payload_schema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      method: "method",
      path: "path",
      payload_schema: "payloadSchema",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$IntegrationsApiOperationsPatchBody
 */
const SchemaOut$IntegrationsApiOperationsPatchBody: z.ZodType<
  External$IntegrationsApiOperationsPatchBody, // output type of this zod object
  z.ZodTypeDef,
  IntegrationsApiOperationsPatchBody // the object to be transformed
> = z
  .object({
    method: z
      .enum(["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"])
      .optional(),
    path: z.string().optional(),
    payloadSchema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      method: "method",
      path: "path",
      payloadSchema: "payload_schema",
    });
  });

export const Schemas$IntegrationsApiOperationsPatchBody = {
  in: SchemaIn$IntegrationsApiOperationsPatchBody,
  out: SchemaOut$IntegrationsApiOperationsPatchBody,
};
