/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * IntegrationsApiOperationsPatchResponseMethodEnum
 */
export type IntegrationsApiOperationsPatchResponseMethodEnum =
  | "DELETE"
  | "GET"
  | "HEAD"
  | "OPTIONS"
  | "PATCH"
  | "POST"
  | "PUT";
