/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * IntegrationsApiCreateResponse
 */
export type IntegrationsApiCreateResponse = {
  accountId?: string | undefined;
  baseUrl?: string | undefined;
  createdAt: string;
  description?: string | undefined;
  id: string;
  name?: string | undefined;
  userId?: string | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (string | undefined)
    | (string | undefined)
    | string
    | (string | undefined)
    | string
    | (string | undefined)
    | (string | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * IntegrationsApiCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$IntegrationsApiCreateResponse = {
  account_id?: string | undefined;
  base_url?: string | undefined;
  created_at: string;
  description?: string | undefined;
  id: string;
  name?: string | undefined;
  user_id?: string | undefined;

  [additionalProperty: string]:
    | (string | undefined)
    | (string | undefined)
    | string
    | (string | undefined)
    | string
    | (string | undefined)
    | (string | undefined)
    | External$IntegrationsApiCreateResponse
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object IntegrationsApiCreateResponse
 */
const SchemaIn$IntegrationsApiCreateResponse: z.ZodType<
  IntegrationsApiCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    account_id: z.string().optional(),
    base_url: z.string().optional(),
    created_at: z.string(),
    description: z.string().optional(),
    id: z.string(),
    name: z.string().optional(),
    user_id: z.string().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      account_id: "accountId",
      base_url: "baseUrl",
      created_at: "createdAt",
      description: "description",
      id: "id",
      name: "name",
      user_id: "userId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$IntegrationsApiCreateResponse
 */
const SchemaOut$IntegrationsApiCreateResponse: z.ZodType<
  External$IntegrationsApiCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  IntegrationsApiCreateResponse // the object to be transformed
> = z
  .object({
    accountId: z.string().optional(),
    baseUrl: z.string().optional(),
    createdAt: z.string(),
    description: z.string().optional(),
    id: z.string(),
    name: z.string().optional(),
    userId: z.string().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      accountId: "account_id",
      baseUrl: "base_url",
      createdAt: "created_at",
      description: "description",
      id: "id",
      name: "name",
      userId: "user_id",
    });
  });

export const Schemas$IntegrationsApiCreateResponse = {
  in: SchemaIn$IntegrationsApiCreateResponse,
  out: SchemaOut$IntegrationsApiCreateResponse,
};
