/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * IntegrationsApiOperationsCreateResponseMethodEnum
 */
export type IntegrationsApiOperationsCreateResponseMethodEnum =
  | "DELETE"
  | "GET"
  | "HEAD"
  | "OPTIONS"
  | "PATCH"
  | "POST"
  | "PUT";
