/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * The mutation to execute
 */
export type MemoryTablesMutateCreateBodyMutation = {
  /**
   * The data to insert, update, or upsert
   */
  data: Record<string, any | undefined>;
  /**
   * The type of the mutation
   */
  type: "create" | "delete" | "update" | "upsert";
  /**
   * The where clause to filter rows for update or delete
   */
  where?: Record<string, any | undefined> | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | Record<string, any | undefined>
    | ("create" | "delete" | "update" | "upsert")
    | (Record<string, any | undefined> | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * MemoryTablesMutateCreateBodyMutation without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$MemoryTablesMutateCreateBodyMutation = {
  data: Record<string, any | undefined>;
  type: "create" | "delete" | "update" | "upsert";
  where?: Record<string, any | undefined> | undefined;

  [additionalProperty: string]:
    | Record<string, any | undefined>
    | ("create" | "delete" | "update" | "upsert")
    | (Record<string, any | undefined> | undefined)
    | External$MemoryTablesMutateCreateBodyMutation
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object MemoryTablesMutateCreateBodyMutation
 */
const SchemaIn$MemoryTablesMutateCreateBodyMutation: z.ZodType<
  MemoryTablesMutateCreateBodyMutation, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    data: z.record(z.string(), zodRequiredAny.optional()),
    type: z.enum(["create", "delete", "update", "upsert"]),
    where: z.record(z.string(), zodRequiredAny.optional()).optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
      type: "type",
      where: "where",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$MemoryTablesMutateCreateBodyMutation
 */
const SchemaOut$MemoryTablesMutateCreateBodyMutation: z.ZodType<
  External$MemoryTablesMutateCreateBodyMutation, // output type of this zod object
  z.ZodTypeDef,
  MemoryTablesMutateCreateBodyMutation // the object to be transformed
> = z
  .object({
    data: z.record(z.string(), zodRequiredAny.optional()),
    type: z.enum(["create", "delete", "update", "upsert"]),
    where: z.record(z.string(), zodRequiredAny.optional()).optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
      type: "type",
      where: "where",
    });
  });

export const Schemas$MemoryTablesMutateCreateBodyMutation = {
  in: SchemaIn$MemoryTablesMutateCreateBodyMutation,
  out: SchemaOut$MemoryTablesMutateCreateBodyMutation,
};
