/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * MemoryTablesGetResponse
 */
export type MemoryTablesGetResponse = {
  createdAt: string;
  description: string;
  id: string;
  name: string;
  /**
   * JSON Schema defining the structure of rows in this table
   */
  schema: Record<string, any | undefined>;
  userId: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | string
    | string
    | string
    | Record<string, any | undefined>
    | string
    | any
    | null
    | undefined;
};

/**
 * @internal
 * MemoryTablesGetResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$MemoryTablesGetResponse = {
  created_at: string;
  description: string;
  id: string;
  name: string;
  schema: Record<string, any | undefined>;
  user_id: string;

  [additionalProperty: string]:
    | string
    | string
    | string
    | string
    | Record<string, any | undefined>
    | string
    | External$MemoryTablesGetResponse
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object MemoryTablesGetResponse
 */
const SchemaIn$MemoryTablesGetResponse: z.ZodType<
  MemoryTablesGetResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string(),
    description: z.string(),
    id: z.string(),
    name: z.string(),
    schema: z.record(z.string(), zodRequiredAny.optional()),
    user_id: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      description: "description",
      id: "id",
      name: "name",
      schema: "schema",
      user_id: "userId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$MemoryTablesGetResponse
 */
const SchemaOut$MemoryTablesGetResponse: z.ZodType<
  External$MemoryTablesGetResponse, // output type of this zod object
  z.ZodTypeDef,
  MemoryTablesGetResponse // the object to be transformed
> = z
  .object({
    createdAt: z.string(),
    description: z.string(),
    id: z.string(),
    name: z.string(),
    schema: z.record(z.string(), zodRequiredAny.optional()),
    userId: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      description: "description",
      id: "id",
      name: "name",
      schema: "schema",
      userId: "user_id",
    });
  });

export const Schemas$MemoryTablesGetResponse = {
  in: SchemaIn$MemoryTablesGetResponse,
  out: SchemaOut$MemoryTablesGetResponse,
};
