/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * MemoryTablesCreateBody
 */
export type MemoryTablesCreateBody = {
  /**
   * Description of the memory table
   */
  description: string;
  /**
   * Name of the memory table
   */
  name: string;
  /**
   * JSON Schema defining the structure of rows in this table
   */
  schema: Record<string, any | undefined>;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | string
    | Record<string, any | undefined>
    | any
    | null
    | undefined;
};

/**
 * @internal
 * MemoryTablesCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$MemoryTablesCreateBody = {
  description: string;
  name: string;
  schema: Record<string, any | undefined>;

  [additionalProperty: string]:
    | string
    | string
    | Record<string, any | undefined>
    | External$MemoryTablesCreateBody
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object MemoryTablesCreateBody
 */
const SchemaIn$MemoryTablesCreateBody: z.ZodType<
  MemoryTablesCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    description: z.string(),
    name: z.string(),
    schema: z.record(z.string(), zodRequiredAny.optional()),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      name: "name",
      schema: "schema",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$MemoryTablesCreateBody
 */
const SchemaOut$MemoryTablesCreateBody: z.ZodType<
  External$MemoryTablesCreateBody, // output type of this zod object
  z.ZodTypeDef,
  MemoryTablesCreateBody // the object to be transformed
> = z
  .object({
    description: z.string(),
    name: z.string(),
    schema: z.record(z.string(), zodRequiredAny.optional()),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      name: "name",
      schema: "schema",
    });
  });

export const Schemas$MemoryTablesCreateBody = {
  in: SchemaIn$MemoryTablesCreateBody,
  out: SchemaOut$MemoryTablesCreateBody,
};
