/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$MemoryTablesMutateCreateBodyMutation,
  MemoryTablesMutateCreateBodyMutation,
  Schemas$MemoryTablesMutateCreateBodyMutation,
} from "./memory-tables-mutate-create-body-mutation";

/**
 * MemoryTablesMutateCreateBody
 */
export type MemoryTablesMutateCreateBody = {
  /**
   * The mutation to execute
   */
  mutation: MemoryTablesMutateCreateBodyMutation;
  /**
   * The ID of the memory table to mutate
   */
  tableId: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | MemoryTablesMutateCreateBodyMutation
    | string
    | any
    | null
    | undefined;
};

/**
 * @internal
 * MemoryTablesMutateCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$MemoryTablesMutateCreateBody = {
  mutation: External$MemoryTablesMutateCreateBodyMutation;
  table_id: string;

  [additionalProperty: string]:
    | External$MemoryTablesMutateCreateBodyMutation
    | string
    | External$MemoryTablesMutateCreateBody
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object MemoryTablesMutateCreateBody
 */
const SchemaIn$MemoryTablesMutateCreateBody: z.ZodType<
  MemoryTablesMutateCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    mutation: Schemas$MemoryTablesMutateCreateBodyMutation.in,
    table_id: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      mutation: "mutation",
      table_id: "tableId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$MemoryTablesMutateCreateBody
 */
const SchemaOut$MemoryTablesMutateCreateBody: z.ZodType<
  External$MemoryTablesMutateCreateBody, // output type of this zod object
  z.ZodTypeDef,
  MemoryTablesMutateCreateBody // the object to be transformed
> = z
  .object({
    mutation: Schemas$MemoryTablesMutateCreateBodyMutation.out,
    tableId: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      mutation: "mutation",
      tableId: "table_id",
    });
  });

export const Schemas$MemoryTablesMutateCreateBody = {
  in: SchemaIn$MemoryTablesMutateCreateBody,
  out: SchemaOut$MemoryTablesMutateCreateBody,
};
