/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * MemoryTablesMutateCreateResponseErrorsItem
 */
export type MemoryTablesMutateCreateResponseErrorsItem = {
  data?: Record<string, any | undefined> | null | undefined;
  error?: string | undefined;
};

/**
 * @internal
 * MemoryTablesMutateCreateResponseErrorsItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$MemoryTablesMutateCreateResponseErrorsItem = {
  data?: Record<string, any | undefined> | null | undefined;
  error?: string | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object MemoryTablesMutateCreateResponseErrorsItem
 */
const SchemaIn$MemoryTablesMutateCreateResponseErrorsItem: z.ZodType<
  MemoryTablesMutateCreateResponseErrorsItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    data: z.record(z.string(), zodRequiredAny.optional()).nullable().optional(),
    error: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
      error: "error",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$MemoryTablesMutateCreateResponseErrorsItem
 */
const SchemaOut$MemoryTablesMutateCreateResponseErrorsItem: z.ZodType<
  External$MemoryTablesMutateCreateResponseErrorsItem, // output type of this zod object
  z.ZodTypeDef,
  MemoryTablesMutateCreateResponseErrorsItem // the object to be transformed
> = z
  .object({
    data: z.record(z.string(), zodRequiredAny.optional()).nullable().optional(),
    error: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      data: "data",
      error: "error",
    });
  });

export const Schemas$MemoryTablesMutateCreateResponseErrorsItem = {
  in: SchemaIn$MemoryTablesMutateCreateResponseErrorsItem,
  out: SchemaOut$MemoryTablesMutateCreateResponseErrorsItem,
};
