/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * MemoryTablesQueryCreateResponseRow
 */
export type MemoryTablesQueryCreateResponseRow = {
  /**
   * Expected to be an ISO 8601 formatted datetime string.
   */
  createdAt: string;
  id: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]: string | string | any | null | undefined;
};

/**
 * @internal
 * MemoryTablesQueryCreateResponseRow without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$MemoryTablesQueryCreateResponseRow = {
  created_at: string;
  id: string;

  [additionalProperty: string]:
    | string
    | string
    | External$MemoryTablesQueryCreateResponseRow
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object MemoryTablesQueryCreateResponseRow
 */
const SchemaIn$MemoryTablesQueryCreateResponseRow: z.ZodType<
  MemoryTablesQueryCreateResponseRow, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string(),
    id: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      id: "id",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$MemoryTablesQueryCreateResponseRow
 */
const SchemaOut$MemoryTablesQueryCreateResponseRow: z.ZodType<
  External$MemoryTablesQueryCreateResponseRow, // output type of this zod object
  z.ZodTypeDef,
  MemoryTablesQueryCreateResponseRow // the object to be transformed
> = z
  .object({
    createdAt: z.string(),
    id: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      id: "id",
    });
  });

export const Schemas$MemoryTablesQueryCreateResponseRow = {
  in: SchemaIn$MemoryTablesQueryCreateResponseRow,
  out: SchemaOut$MemoryTablesQueryCreateResponseRow,
};
