/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$MemoryTablesMutateCreateResponseDataItem,
  MemoryTablesMutateCreateResponseDataItem,
  Schemas$MemoryTablesMutateCreateResponseDataItem,
} from "./memory-tables-mutate-create-response-data-item";
import {
  External$MemoryTablesMutateCreateResponseErrorsItem,
  MemoryTablesMutateCreateResponseErrorsItem,
  Schemas$MemoryTablesMutateCreateResponseErrorsItem,
} from "./memory-tables-mutate-create-response-errors-item";

/**
 * MemoryTablesMutateCreateResponse
 */
export type MemoryTablesMutateCreateResponse = {
  /**
   * The number of affected rows
   */
  count: number;
  /**
   * The affected rows
   */
  data?: MemoryTablesMutateCreateResponseDataItem[] | undefined;
  /**
   * Any errors that occurred during the mutation
   */
  errors?: MemoryTablesMutateCreateResponseErrorsItem[] | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | number
    | (MemoryTablesMutateCreateResponseDataItem[] | undefined)
    | (MemoryTablesMutateCreateResponseErrorsItem[] | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * MemoryTablesMutateCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$MemoryTablesMutateCreateResponse = {
  count: number;
  data?: External$MemoryTablesMutateCreateResponseDataItem[] | undefined;
  errors?: External$MemoryTablesMutateCreateResponseErrorsItem[] | undefined;

  [additionalProperty: string]:
    | number
    | (External$MemoryTablesMutateCreateResponseDataItem[] | undefined)
    | (External$MemoryTablesMutateCreateResponseErrorsItem[] | undefined)
    | External$MemoryTablesMutateCreateResponse
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object MemoryTablesMutateCreateResponse
 */
const SchemaIn$MemoryTablesMutateCreateResponse: z.ZodType<
  MemoryTablesMutateCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    count: z.number(),
    data: z
      .array(Schemas$MemoryTablesMutateCreateResponseDataItem.in)
      .optional(),
    errors: z
      .array(Schemas$MemoryTablesMutateCreateResponseErrorsItem.in)
      .optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      count: "count",
      data: "data",
      errors: "errors",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$MemoryTablesMutateCreateResponse
 */
const SchemaOut$MemoryTablesMutateCreateResponse: z.ZodType<
  External$MemoryTablesMutateCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  MemoryTablesMutateCreateResponse // the object to be transformed
> = z
  .object({
    count: z.number(),
    data: z
      .array(Schemas$MemoryTablesMutateCreateResponseDataItem.out)
      .optional(),
    errors: z
      .array(Schemas$MemoryTablesMutateCreateResponseErrorsItem.out)
      .optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      count: "count",
      data: "data",
      errors: "errors",
    });
  });

export const Schemas$MemoryTablesMutateCreateResponse = {
  in: SchemaIn$MemoryTablesMutateCreateResponse,
  out: SchemaOut$MemoryTablesMutateCreateResponse,
};
