/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$MemoryTablesQueryCreateResponseRow,
  MemoryTablesQueryCreateResponseRow,
  Schemas$MemoryTablesQueryCreateResponseRow,
} from "./memory-tables-query-create-response-row";
import {
  External$MemoryTablesQueryCreateResponseRowsItem,
  MemoryTablesQueryCreateResponseRowsItem,
  Schemas$MemoryTablesQueryCreateResponseRowsItem,
} from "./memory-tables-query-create-response-rows-item";

/**
 * MemoryTablesQueryCreateResponse
 */
export type MemoryTablesQueryCreateResponse = {
  /**
   * The total count of matched items
   */
  count: number;
  row?: MemoryTablesQueryCreateResponseRow | undefined;
  /**
   * An array of matched record objects
   */
  rows?: MemoryTablesQueryCreateResponseRowsItem[] | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | number
    | (MemoryTablesQueryCreateResponseRow | undefined)
    | (MemoryTablesQueryCreateResponseRowsItem[] | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * MemoryTablesQueryCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$MemoryTablesQueryCreateResponse = {
  count: number;
  row?: External$MemoryTablesQueryCreateResponseRow | undefined;
  rows?: External$MemoryTablesQueryCreateResponseRowsItem[] | undefined;

  [additionalProperty: string]:
    | number
    | (External$MemoryTablesQueryCreateResponseRow | undefined)
    | (External$MemoryTablesQueryCreateResponseRowsItem[] | undefined)
    | External$MemoryTablesQueryCreateResponse
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object MemoryTablesQueryCreateResponse
 */
const SchemaIn$MemoryTablesQueryCreateResponse: z.ZodType<
  MemoryTablesQueryCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    count: z.number(),
    row: Schemas$MemoryTablesQueryCreateResponseRow.in.optional(),
    rows: z
      .array(Schemas$MemoryTablesQueryCreateResponseRowsItem.in)
      .optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      count: "count",
      row: "row",
      rows: "rows",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$MemoryTablesQueryCreateResponse
 */
const SchemaOut$MemoryTablesQueryCreateResponse: z.ZodType<
  External$MemoryTablesQueryCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  MemoryTablesQueryCreateResponse // the object to be transformed
> = z
  .object({
    count: z.number(),
    row: Schemas$MemoryTablesQueryCreateResponseRow.out.optional(),
    rows: z
      .array(Schemas$MemoryTablesQueryCreateResponseRowsItem.out)
      .optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      count: "count",
      row: "row",
      rows: "rows",
    });
  });

export const Schemas$MemoryTablesQueryCreateResponse = {
  in: SchemaIn$MemoryTablesQueryCreateResponse,
  out: SchemaOut$MemoryTablesQueryCreateResponse,
};
