/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * if search_group.type = META_TAGS
 */
export type SearchGroupsItemsCreateResponseUnion0Obj1 = {
  description: string;
  name: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]: string | string | any | null | undefined;
};

/**
 * @internal
 * SearchGroupsItemsCreateResponseUnion0Obj1 without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$SearchGroupsItemsCreateResponseUnion0Obj1 = {
  description: string;
  name: string;

  [additionalProperty: string]:
    | string
    | string
    | External$SearchGroupsItemsCreateResponseUnion0Obj1
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object SearchGroupsItemsCreateResponseUnion0Obj1
 */
const SchemaIn$SearchGroupsItemsCreateResponseUnion0Obj1: z.ZodType<
  SearchGroupsItemsCreateResponseUnion0Obj1, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    description: z.string(),
    name: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      name: "name",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$SearchGroupsItemsCreateResponseUnion0Obj1
 */
const SchemaOut$SearchGroupsItemsCreateResponseUnion0Obj1: z.ZodType<
  External$SearchGroupsItemsCreateResponseUnion0Obj1, // output type of this zod object
  z.ZodTypeDef,
  SearchGroupsItemsCreateResponseUnion0Obj1 // the object to be transformed
> = z
  .object({
    description: z.string(),
    name: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      name: "name",
    });
  });

export const Schemas$SearchGroupsItemsCreateResponseUnion0Obj1 = {
  in: SchemaIn$SearchGroupsItemsCreateResponseUnion0Obj1,
  out: SchemaOut$SearchGroupsItemsCreateResponseUnion0Obj1,
};
