/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$SearchGroupsItemsListResponseItemValueObj0,
  Schemas$SearchGroupsItemsListResponseItemValueObj0,
  SearchGroupsItemsListResponseItemValueObj0,
} from "./search-groups-items-list-response-item-value-obj0";
import {
  External$SearchGroupsItemsListResponseItemValueObj1,
  Schemas$SearchGroupsItemsListResponseItemValueObj1,
  SearchGroupsItemsListResponseItemValueObj1,
} from "./search-groups-items-list-response-item-value-obj1";

/**
 * SearchGroupsItemsListResponseItem
 */
export type SearchGroupsItemsListResponseItem = {
  createdAt: string;
  id: string;
  searchGroupId: string;
  value:
    | SearchGroupsItemsListResponseItemValueObj0
    | SearchGroupsItemsListResponseItemValueObj1
    | Record<string, any | undefined>;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | string
    | string
    | (
        | SearchGroupsItemsListResponseItemValueObj0
        | SearchGroupsItemsListResponseItemValueObj1
        | Record<string, any | undefined>
      )
    | any
    | null
    | undefined;
};

/**
 * @internal
 * SearchGroupsItemsListResponseItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$SearchGroupsItemsListResponseItem = {
  created_at: string;
  id: string;
  search_group_id: string;
  value:
    | External$SearchGroupsItemsListResponseItemValueObj0
    | External$SearchGroupsItemsListResponseItemValueObj1
    | Record<string, any | undefined>;

  [additionalProperty: string]:
    | string
    | string
    | string
    | (
        | External$SearchGroupsItemsListResponseItemValueObj0
        | External$SearchGroupsItemsListResponseItemValueObj1
        | Record<string, any | undefined>
      )
    | External$SearchGroupsItemsListResponseItem
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object SearchGroupsItemsListResponseItem
 */
const SchemaIn$SearchGroupsItemsListResponseItem: z.ZodType<
  SearchGroupsItemsListResponseItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string(),
    id: z.string(),
    search_group_id: z.string(),
    value: z.union([
      Schemas$SearchGroupsItemsListResponseItemValueObj0.in,
      Schemas$SearchGroupsItemsListResponseItemValueObj1.in,
      z.record(z.string(), zodRequiredAny.optional()),
    ]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      id: "id",
      search_group_id: "searchGroupId",
      value: "value",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$SearchGroupsItemsListResponseItem
 */
const SchemaOut$SearchGroupsItemsListResponseItem: z.ZodType<
  External$SearchGroupsItemsListResponseItem, // output type of this zod object
  z.ZodTypeDef,
  SearchGroupsItemsListResponseItem // the object to be transformed
> = z
  .object({
    createdAt: z.string(),
    id: z.string(),
    searchGroupId: z.string(),
    value: z.union([
      Schemas$SearchGroupsItemsListResponseItemValueObj0.out,
      Schemas$SearchGroupsItemsListResponseItemValueObj1.out,
      z.record(z.string(), zodRequiredAny.optional()),
    ]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      id: "id",
      searchGroupId: "search_group_id",
      value: "value",
    });
  });

export const Schemas$SearchGroupsItemsListResponseItem = {
  in: SchemaIn$SearchGroupsItemsListResponseItem,
  out: SchemaOut$SearchGroupsItemsListResponseItem,
};
