/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * if search_group.type = META_TAGS
 */
export type SearchGroupsItemsListResponseItemValueObj1 = {
  description: string;
  name: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]: string | string | any | null | undefined;
};

/**
 * @internal
 * SearchGroupsItemsListResponseItemValueObj1 without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$SearchGroupsItemsListResponseItemValueObj1 = {
  description: string;
  name: string;

  [additionalProperty: string]:
    | string
    | string
    | External$SearchGroupsItemsListResponseItemValueObj1
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object SearchGroupsItemsListResponseItemValueObj1
 */
const SchemaIn$SearchGroupsItemsListResponseItemValueObj1: z.ZodType<
  SearchGroupsItemsListResponseItemValueObj1, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    description: z.string(),
    name: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      name: "name",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$SearchGroupsItemsListResponseItemValueObj1
 */
const SchemaOut$SearchGroupsItemsListResponseItemValueObj1: z.ZodType<
  External$SearchGroupsItemsListResponseItemValueObj1, // output type of this zod object
  z.ZodTypeDef,
  SearchGroupsItemsListResponseItemValueObj1 // the object to be transformed
> = z
  .object({
    description: z.string(),
    name: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      name: "name",
    });
  });

export const Schemas$SearchGroupsItemsListResponseItemValueObj1 = {
  in: SchemaIn$SearchGroupsItemsListResponseItemValueObj1,
  out: SchemaOut$SearchGroupsItemsListResponseItemValueObj1,
};
