/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$SearchGroupsItemsGetResponseValueObj0,
  Schemas$SearchGroupsItemsGetResponseValueObj0,
  SearchGroupsItemsGetResponseValueObj0,
} from "./search-groups-items-get-response-value-obj0";
import {
  External$SearchGroupsItemsGetResponseValueObj1,
  Schemas$SearchGroupsItemsGetResponseValueObj1,
  SearchGroupsItemsGetResponseValueObj1,
} from "./search-groups-items-get-response-value-obj1";

/**
 * SearchGroupsItemsGetResponse
 */
export type SearchGroupsItemsGetResponse = {
  createdAt: string;
  id: string;
  searchGroupId: string;
  value:
    | SearchGroupsItemsGetResponseValueObj0
    | SearchGroupsItemsGetResponseValueObj1
    | Record<string, any | undefined>;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | string
    | string
    | (
        | SearchGroupsItemsGetResponseValueObj0
        | SearchGroupsItemsGetResponseValueObj1
        | Record<string, any | undefined>
      )
    | any
    | null
    | undefined;
};

/**
 * @internal
 * SearchGroupsItemsGetResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$SearchGroupsItemsGetResponse = {
  created_at: string;
  id: string;
  search_group_id: string;
  value:
    | External$SearchGroupsItemsGetResponseValueObj0
    | External$SearchGroupsItemsGetResponseValueObj1
    | Record<string, any | undefined>;

  [additionalProperty: string]:
    | string
    | string
    | string
    | (
        | External$SearchGroupsItemsGetResponseValueObj0
        | External$SearchGroupsItemsGetResponseValueObj1
        | Record<string, any | undefined>
      )
    | External$SearchGroupsItemsGetResponse
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object SearchGroupsItemsGetResponse
 */
const SchemaIn$SearchGroupsItemsGetResponse: z.ZodType<
  SearchGroupsItemsGetResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string(),
    id: z.string(),
    search_group_id: z.string(),
    value: z.union([
      Schemas$SearchGroupsItemsGetResponseValueObj0.in,
      Schemas$SearchGroupsItemsGetResponseValueObj1.in,
      z.record(z.string(), zodRequiredAny.optional()),
    ]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      id: "id",
      search_group_id: "searchGroupId",
      value: "value",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$SearchGroupsItemsGetResponse
 */
const SchemaOut$SearchGroupsItemsGetResponse: z.ZodType<
  External$SearchGroupsItemsGetResponse, // output type of this zod object
  z.ZodTypeDef,
  SearchGroupsItemsGetResponse // the object to be transformed
> = z
  .object({
    createdAt: z.string(),
    id: z.string(),
    searchGroupId: z.string(),
    value: z.union([
      Schemas$SearchGroupsItemsGetResponseValueObj0.out,
      Schemas$SearchGroupsItemsGetResponseValueObj1.out,
      z.record(z.string(), zodRequiredAny.optional()),
    ]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      id: "id",
      searchGroupId: "search_group_id",
      value: "value",
    });
  });

export const Schemas$SearchGroupsItemsGetResponse = {
  in: SchemaIn$SearchGroupsItemsGetResponse,
  out: SchemaOut$SearchGroupsItemsGetResponse,
};
