/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * if search_group.type = DICTIONARY
 */
export type SearchGroupsItemsCreateResponseUnion0Obj0 = {
  aliases: string[];
  key: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]: string[] | string | any | null | undefined;
};

/**
 * @internal
 * SearchGroupsItemsCreateResponseUnion0Obj0 without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$SearchGroupsItemsCreateResponseUnion0Obj0 = {
  aliases: string[];
  key: string;

  [additionalProperty: string]:
    | string[]
    | string
    | External$SearchGroupsItemsCreateResponseUnion0Obj0
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object SearchGroupsItemsCreateResponseUnion0Obj0
 */
const SchemaIn$SearchGroupsItemsCreateResponseUnion0Obj0: z.ZodType<
  SearchGroupsItemsCreateResponseUnion0Obj0, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    aliases: z.array(z.string()),
    key: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      aliases: "aliases",
      key: "key",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$SearchGroupsItemsCreateResponseUnion0Obj0
 */
const SchemaOut$SearchGroupsItemsCreateResponseUnion0Obj0: z.ZodType<
  External$SearchGroupsItemsCreateResponseUnion0Obj0, // output type of this zod object
  z.ZodTypeDef,
  SearchGroupsItemsCreateResponseUnion0Obj0 // the object to be transformed
> = z
  .object({
    aliases: z.array(z.string()),
    key: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      aliases: "aliases",
      key: "key",
    });
  });

export const Schemas$SearchGroupsItemsCreateResponseUnion0Obj0 = {
  in: SchemaIn$SearchGroupsItemsCreateResponseUnion0Obj0,
  out: SchemaOut$SearchGroupsItemsCreateResponseUnion0Obj0,
};
