/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * SearchGroupsCreateBody
 */
export type SearchGroupsCreateBody = {
  description: string | null;
  name: string;
  type: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (string | null)
    | string
    | string
    | any
    | null
    | undefined;
};

/**
 * @internal
 * SearchGroupsCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$SearchGroupsCreateBody = {
  description: string | null;
  name: string;
  type: string;

  [additionalProperty: string]:
    | (string | null)
    | string
    | string
    | External$SearchGroupsCreateBody
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object SearchGroupsCreateBody
 */
const SchemaIn$SearchGroupsCreateBody: z.ZodType<
  SearchGroupsCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    description: z.string().nullable(),
    name: z.string(),
    type: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      name: "name",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$SearchGroupsCreateBody
 */
const SchemaOut$SearchGroupsCreateBody: z.ZodType<
  External$SearchGroupsCreateBody, // output type of this zod object
  z.ZodTypeDef,
  SearchGroupsCreateBody // the object to be transformed
> = z
  .object({
    description: z.string().nullable(),
    name: z.string(),
    type: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      name: "name",
      type: "type",
    });
  });

export const Schemas$SearchGroupsCreateBody = {
  in: SchemaIn$SearchGroupsCreateBody,
  out: SchemaOut$SearchGroupsCreateBody,
};
