/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * SubscriptionsEventsGetResponse
 */
export type SubscriptionsEventsGetResponse = {
  /**
   * The ID of the consumer resource
   */
  consumerId: string;
  /**
   * The type of the consumer resource
   */
  consumerType: "workflow_origins" | "workflows";
  createdAt: string;
  /**
   * Array of event patterns to subscribe to (e.g. ['feed_items', 'create'])
   */
  events: string[];
  id: string;
  /**
   * The ID of the producer resource
   */
  producerId: string;
  /**
   * The type of the producer resource
   */
  producerType: "feeds" | "workflows";

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | ("workflow_origins" | "workflows")
    | string
    | string[]
    | string
    | string
    | ("feeds" | "workflows")
    | any
    | null
    | undefined;
};

/**
 * @internal
 * SubscriptionsEventsGetResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$SubscriptionsEventsGetResponse = {
  consumer_id: string;
  consumer_type: "workflow_origins" | "workflows";
  created_at: string;
  events: string[];
  id: string;
  producer_id: string;
  producer_type: "feeds" | "workflows";

  [additionalProperty: string]:
    | string
    | ("workflow_origins" | "workflows")
    | string
    | string[]
    | string
    | string
    | ("feeds" | "workflows")
    | External$SubscriptionsEventsGetResponse
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object SubscriptionsEventsGetResponse
 */
const SchemaIn$SubscriptionsEventsGetResponse: z.ZodType<
  SubscriptionsEventsGetResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    consumer_id: z.string(),
    consumer_type: z.enum(["workflow_origins", "workflows"]),
    created_at: z.string(),
    events: z.array(z.string()),
    id: z.string(),
    producer_id: z.string(),
    producer_type: z.enum(["feeds", "workflows"]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      consumer_id: "consumerId",
      consumer_type: "consumerType",
      created_at: "createdAt",
      events: "events",
      id: "id",
      producer_id: "producerId",
      producer_type: "producerType",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$SubscriptionsEventsGetResponse
 */
const SchemaOut$SubscriptionsEventsGetResponse: z.ZodType<
  External$SubscriptionsEventsGetResponse, // output type of this zod object
  z.ZodTypeDef,
  SubscriptionsEventsGetResponse // the object to be transformed
> = z
  .object({
    consumerId: z.string(),
    consumerType: z.enum(["workflow_origins", "workflows"]),
    createdAt: z.string(),
    events: z.array(z.string()),
    id: z.string(),
    producerId: z.string(),
    producerType: z.enum(["feeds", "workflows"]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      consumerId: "consumer_id",
      consumerType: "consumer_type",
      createdAt: "created_at",
      events: "events",
      id: "id",
      producerId: "producer_id",
      producerType: "producer_type",
    });
  });

export const Schemas$SubscriptionsEventsGetResponse = {
  in: SchemaIn$SubscriptionsEventsGetResponse,
  out: SchemaOut$SubscriptionsEventsGetResponse,
};
