/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * SubscriptionsEventsCreateBody
 */
export type SubscriptionsEventsCreateBody = {
  /**
   * The ID of the consumer resource
   */
  consumerId: string;
  /**
   * The type of the consumer resource
   */
  consumerType: "workflow_origins" | "workflows";
  /**
   * Array of event patterns to subscribe to (e.g. ["feed_items", "create"])
   */
  events: string[];
  /**
   * The ID of the producer resource
   */
  producerId: string;
  /**
   * The type of the producer resource
   */
  producerType: "feeds" | "workflows";

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | ("workflow_origins" | "workflows")
    | string[]
    | string
    | ("feeds" | "workflows")
    | any
    | null
    | undefined;
};

/**
 * @internal
 * SubscriptionsEventsCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$SubscriptionsEventsCreateBody = {
  consumer_id: string;
  consumer_type: "workflow_origins" | "workflows";
  events: string[];
  producer_id: string;
  producer_type: "feeds" | "workflows";

  [additionalProperty: string]:
    | string
    | ("workflow_origins" | "workflows")
    | string[]
    | string
    | ("feeds" | "workflows")
    | External$SubscriptionsEventsCreateBody
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object SubscriptionsEventsCreateBody
 */
const SchemaIn$SubscriptionsEventsCreateBody: z.ZodType<
  SubscriptionsEventsCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    consumer_id: z.string(),
    consumer_type: z.enum(["workflow_origins", "workflows"]),
    events: z.array(z.string()),
    producer_id: z.string(),
    producer_type: z.enum(["feeds", "workflows"]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      consumer_id: "consumerId",
      consumer_type: "consumerType",
      events: "events",
      producer_id: "producerId",
      producer_type: "producerType",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$SubscriptionsEventsCreateBody
 */
const SchemaOut$SubscriptionsEventsCreateBody: z.ZodType<
  External$SubscriptionsEventsCreateBody, // output type of this zod object
  z.ZodTypeDef,
  SubscriptionsEventsCreateBody // the object to be transformed
> = z
  .object({
    consumerId: z.string(),
    consumerType: z.enum(["workflow_origins", "workflows"]),
    events: z.array(z.string()),
    producerId: z.string(),
    producerType: z.enum(["feeds", "workflows"]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      consumerId: "consumer_id",
      consumerType: "consumer_type",
      events: "events",
      producerId: "producer_id",
      producerType: "producer_type",
    });
  });

export const Schemas$SubscriptionsEventsCreateBody = {
  in: SchemaIn$SubscriptionsEventsCreateBody,
  out: SchemaOut$SubscriptionsEventsCreateBody,
};
