/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * ToolsFormatCreateBody
 */
export type ToolsFormatCreateBody = {
  /**
   * Desired output format
   */
  format: "html" | "markdown";
  /**
   * Input to format
   */
  input: string;
  /**
   * Instructions for the formatter
   */
  instructions: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | ("html" | "markdown")
    | string
    | string
    | any
    | null
    | undefined;
};

/**
 * @internal
 * ToolsFormatCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsFormatCreateBody = {
  format: "html" | "markdown";
  input: string;
  instructions: string;

  [additionalProperty: string]:
    | ("html" | "markdown")
    | string
    | string
    | External$ToolsFormatCreateBody
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsFormatCreateBody
 */
const SchemaIn$ToolsFormatCreateBody: z.ZodType<
  ToolsFormatCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    format: z.enum(["html", "markdown"]),
    input: z.string(),
    instructions: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      format: "format",
      input: "input",
      instructions: "instructions",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsFormatCreateBody
 */
const SchemaOut$ToolsFormatCreateBody: z.ZodType<
  External$ToolsFormatCreateBody, // output type of this zod object
  z.ZodTypeDef,
  ToolsFormatCreateBody // the object to be transformed
> = z
  .object({
    format: z.enum(["html", "markdown"]),
    input: z.string(),
    instructions: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      format: "format",
      input: "input",
      instructions: "instructions",
    });
  });

export const Schemas$ToolsFormatCreateBody = {
  in: SchemaIn$ToolsFormatCreateBody,
  out: SchemaOut$ToolsFormatCreateBody,
};
