/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * ToolsFormatCreateResponseItem
 */
export type ToolsFormatCreateResponseItem = {
  text?: string | undefined;
  type?: string | undefined;
};

/**
 * @internal
 * ToolsFormatCreateResponseItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsFormatCreateResponseItem = {
  text?: string | undefined;
  type?: string | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsFormatCreateResponseItem
 */
const SchemaIn$ToolsFormatCreateResponseItem: z.ZodType<
  ToolsFormatCreateResponseItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    text: z.string().optional(),
    type: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      text: "text",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsFormatCreateResponseItem
 */
const SchemaOut$ToolsFormatCreateResponseItem: z.ZodType<
  External$ToolsFormatCreateResponseItem, // output type of this zod object
  z.ZodTypeDef,
  ToolsFormatCreateResponseItem // the object to be transformed
> = z
  .object({
    text: z.string().optional(),
    type: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      text: "text",
      type: "type",
    });
  });

export const Schemas$ToolsFormatCreateResponseItem = {
  in: SchemaIn$ToolsFormatCreateResponseItem,
  out: SchemaOut$ToolsFormatCreateResponseItem,
};
