/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * ToolsInternetSearchCreateResponseItem
 */
export type ToolsInternetSearchCreateResponseItem = {
  citations?: any[] | null | undefined;
  text: string;
  type: string;
};

/**
 * @internal
 * ToolsInternetSearchCreateResponseItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsInternetSearchCreateResponseItem = {
  citations?: any[] | null | undefined;
  text: string;
  type: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsInternetSearchCreateResponseItem
 */
const SchemaIn$ToolsInternetSearchCreateResponseItem: z.ZodType<
  ToolsInternetSearchCreateResponseItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    citations: z.array(zodRequiredAny).nullable().optional(),
    text: z.string(),
    type: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      citations: "citations",
      text: "text",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsInternetSearchCreateResponseItem
 */
const SchemaOut$ToolsInternetSearchCreateResponseItem: z.ZodType<
  External$ToolsInternetSearchCreateResponseItem, // output type of this zod object
  z.ZodTypeDef,
  ToolsInternetSearchCreateResponseItem // the object to be transformed
> = z
  .object({
    citations: z.array(zodRequiredAny).nullable().optional(),
    text: z.string(),
    type: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      citations: "citations",
      text: "text",
      type: "type",
    });
  });

export const Schemas$ToolsInternetSearchCreateResponseItem = {
  in: SchemaIn$ToolsInternetSearchCreateResponseItem,
  out: SchemaOut$ToolsInternetSearchCreateResponseItem,
};
