/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * ToolsFormatCreateBodyParams
 */
export type ToolsFormatCreateBodyParams = {
  /**
   * The maximum number of tokens to generate
   */
  maxTokens?: number | null | undefined;
  /**
   * The name of the model to use for the LLM
   */
  model?: string | null | undefined;
  /**
   * The stop sequences to use for the LLM
   */
  stopSequences?: string[] | null | undefined;
  /**
   * The temperature to use for the LLM
   */
  temperature?: number | null | undefined;
  /**
   * The top k to use for the LLM
   */
  topK?: number | null | undefined;
  /**
   * The top p to use for the LLM
   */
  topP?: number | null | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (number | null | undefined)
    | (string | null | undefined)
    | (string[] | null | undefined)
    | (number | null | undefined)
    | (number | null | undefined)
    | (number | null | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * ToolsFormatCreateBodyParams without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsFormatCreateBodyParams = {
  max_tokens?: number | null | undefined;
  model?: string | null | undefined;
  stop_sequences?: string[] | null | undefined;
  temperature?: number | null | undefined;
  top_k?: number | null | undefined;
  top_p?: number | null | undefined;

  [additionalProperty: string]:
    | (number | null | undefined)
    | (string | null | undefined)
    | (string[] | null | undefined)
    | (number | null | undefined)
    | (number | null | undefined)
    | (number | null | undefined)
    | External$ToolsFormatCreateBodyParams
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsFormatCreateBodyParams
 */
const SchemaIn$ToolsFormatCreateBodyParams: z.ZodType<
  ToolsFormatCreateBodyParams, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    max_tokens: z.number().int().nullable().optional(),
    model: z.string().nullable().optional(),
    stop_sequences: z.array(z.string()).nullable().optional(),
    temperature: z.number().nullable().optional(),
    top_k: z.number().int().nullable().optional(),
    top_p: z.number().nullable().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      max_tokens: "maxTokens",
      model: "model",
      stop_sequences: "stopSequences",
      temperature: "temperature",
      top_k: "topK",
      top_p: "topP",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsFormatCreateBodyParams
 */
const SchemaOut$ToolsFormatCreateBodyParams: z.ZodType<
  External$ToolsFormatCreateBodyParams, // output type of this zod object
  z.ZodTypeDef,
  ToolsFormatCreateBodyParams // the object to be transformed
> = z
  .object({
    maxTokens: z.number().int().nullable().optional(),
    model: z.string().nullable().optional(),
    stopSequences: z.array(z.string()).nullable().optional(),
    temperature: z.number().nullable().optional(),
    topK: z.number().int().nullable().optional(),
    topP: z.number().nullable().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      maxTokens: "max_tokens",
      model: "model",
      stopSequences: "stop_sequences",
      temperature: "temperature",
      topK: "top_k",
      topP: "top_p",
    });
  });

export const Schemas$ToolsFormatCreateBodyParams = {
  in: SchemaIn$ToolsFormatCreateBodyParams,
  out: SchemaOut$ToolsFormatCreateBodyParams,
};
