/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * ToolsInternetSearchCreateBodyMessagesItem
 */
export type ToolsInternetSearchCreateBodyMessagesItem = {
  content: string;
  role: "assistant" | "user";
};

/**
 * @internal
 * ToolsInternetSearchCreateBodyMessagesItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsInternetSearchCreateBodyMessagesItem = {
  content: string;
  role: "assistant" | "user";
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsInternetSearchCreateBodyMessagesItem
 */
const SchemaIn$ToolsInternetSearchCreateBodyMessagesItem: z.ZodType<
  ToolsInternetSearchCreateBodyMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    content: z.string(),
    role: z.enum(["assistant", "user"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      role: "role",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsInternetSearchCreateBodyMessagesItem
 */
const SchemaOut$ToolsInternetSearchCreateBodyMessagesItem: z.ZodType<
  External$ToolsInternetSearchCreateBodyMessagesItem, // output type of this zod object
  z.ZodTypeDef,
  ToolsInternetSearchCreateBodyMessagesItem // the object to be transformed
> = z
  .object({
    content: z.string(),
    role: z.enum(["assistant", "user"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      content: "content",
      role: "role",
    });
  });

export const Schemas$ToolsInternetSearchCreateBodyMessagesItem = {
  in: SchemaIn$ToolsInternetSearchCreateBodyMessagesItem,
  out: SchemaOut$ToolsInternetSearchCreateBodyMessagesItem,
};
