/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * ToolsMemoryQueryCreateBodyObj0Input
 */
export type ToolsMemoryQueryCreateBodyObj0Input = {
  /**
   * An optional data source used to replace refs in the query
   */
  attrSource?: Record<string, any | undefined> | undefined;
  /**
   * Optional query modifiers
   */
  modifiers?: Record<string, any | undefined> | undefined;
  /**
   * The data query to execute
   */
  query: Record<string, any | undefined>;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (Record<string, any | undefined> | undefined)
    | (Record<string, any | undefined> | undefined)
    | Record<string, any | undefined>
    | any
    | null
    | undefined;
};

/**
 * @internal
 * ToolsMemoryQueryCreateBodyObj0Input without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsMemoryQueryCreateBodyObj0Input = {
  $source?: Record<string, any | undefined> | undefined;
  modifiers?: Record<string, any | undefined> | undefined;
  query: Record<string, any | undefined>;

  [additionalProperty: string]:
    | (Record<string, any | undefined> | undefined)
    | (Record<string, any | undefined> | undefined)
    | Record<string, any | undefined>
    | External$ToolsMemoryQueryCreateBodyObj0Input
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsMemoryQueryCreateBodyObj0Input
 */
const SchemaIn$ToolsMemoryQueryCreateBodyObj0Input: z.ZodType<
  ToolsMemoryQueryCreateBodyObj0Input, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    $source: z.record(z.string(), zodRequiredAny.optional()).optional(),
    modifiers: z.record(z.string(), zodRequiredAny.optional()).optional(),
    query: z.record(z.string(), zodRequiredAny.optional()),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      $source: "attrSource",
      modifiers: "modifiers",
      query: "query",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsMemoryQueryCreateBodyObj0Input
 */
const SchemaOut$ToolsMemoryQueryCreateBodyObj0Input: z.ZodType<
  External$ToolsMemoryQueryCreateBodyObj0Input, // output type of this zod object
  z.ZodTypeDef,
  ToolsMemoryQueryCreateBodyObj0Input // the object to be transformed
> = z
  .object({
    attrSource: z.record(z.string(), zodRequiredAny.optional()).optional(),
    modifiers: z.record(z.string(), zodRequiredAny.optional()).optional(),
    query: z.record(z.string(), zodRequiredAny.optional()),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      attrSource: "$source",
      modifiers: "modifiers",
      query: "query",
    });
  });

export const Schemas$ToolsMemoryQueryCreateBodyObj0Input = {
  in: SchemaIn$ToolsMemoryQueryCreateBodyObj0Input,
  out: SchemaOut$ToolsMemoryQueryCreateBodyObj0Input,
};
