/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * ToolsInternetSearchCreateResponse
 */
export type ToolsInternetSearchCreateResponse = {
  markdown: string;
};

/**
 * @internal
 * ToolsInternetSearchCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsInternetSearchCreateResponse = {
  markdown: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsInternetSearchCreateResponse
 */
const SchemaIn$ToolsInternetSearchCreateResponse: z.ZodType<
  ToolsInternetSearchCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    markdown: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      markdown: "markdown",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsInternetSearchCreateResponse
 */
const SchemaOut$ToolsInternetSearchCreateResponse: z.ZodType<
  External$ToolsInternetSearchCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  ToolsInternetSearchCreateResponse // the object to be transformed
> = z
  .object({
    markdown: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      markdown: "markdown",
    });
  });

export const Schemas$ToolsInternetSearchCreateResponse = {
  in: SchemaIn$ToolsInternetSearchCreateResponse,
  out: SchemaOut$ToolsInternetSearchCreateResponse,
};
