/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$ToolsMemoryQueryCreateResponseRow,
  Schemas$ToolsMemoryQueryCreateResponseRow,
  ToolsMemoryQueryCreateResponseRow,
} from "./tools-memory-query-create-response-row";
import {
  External$ToolsMemoryQueryCreateResponseRowsItem,
  Schemas$ToolsMemoryQueryCreateResponseRowsItem,
  ToolsMemoryQueryCreateResponseRowsItem,
} from "./tools-memory-query-create-response-rows-item";

/**
 * ToolsMemoryQueryCreateResponse
 */
export type ToolsMemoryQueryCreateResponse = {
  /**
   * The total count of items, or null.
   */
  count: number;
  row?: ToolsMemoryQueryCreateResponseRow | undefined;
  /**
   * An array of record objects or null.
   */
  rows?: ToolsMemoryQueryCreateResponseRowsItem[] | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | number
    | (ToolsMemoryQueryCreateResponseRow | undefined)
    | (ToolsMemoryQueryCreateResponseRowsItem[] | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * ToolsMemoryQueryCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsMemoryQueryCreateResponse = {
  count: number;
  row?: External$ToolsMemoryQueryCreateResponseRow | undefined;
  rows?: External$ToolsMemoryQueryCreateResponseRowsItem[] | undefined;

  [additionalProperty: string]:
    | number
    | (External$ToolsMemoryQueryCreateResponseRow | undefined)
    | (External$ToolsMemoryQueryCreateResponseRowsItem[] | undefined)
    | External$ToolsMemoryQueryCreateResponse
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsMemoryQueryCreateResponse
 */
const SchemaIn$ToolsMemoryQueryCreateResponse: z.ZodType<
  ToolsMemoryQueryCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    count: z.number(),
    row: Schemas$ToolsMemoryQueryCreateResponseRow.in.optional(),
    rows: z.array(Schemas$ToolsMemoryQueryCreateResponseRowsItem.in).optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      count: "count",
      row: "row",
      rows: "rows",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsMemoryQueryCreateResponse
 */
const SchemaOut$ToolsMemoryQueryCreateResponse: z.ZodType<
  External$ToolsMemoryQueryCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  ToolsMemoryQueryCreateResponse // the object to be transformed
> = z
  .object({
    count: z.number(),
    row: Schemas$ToolsMemoryQueryCreateResponseRow.out.optional(),
    rows: z
      .array(Schemas$ToolsMemoryQueryCreateResponseRowsItem.out)
      .optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      count: "count",
      row: "row",
      rows: "rows",
    });
  });

export const Schemas$ToolsMemoryQueryCreateResponse = {
  in: SchemaIn$ToolsMemoryQueryCreateResponse,
  out: SchemaOut$ToolsMemoryQueryCreateResponse,
};
