/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * The mutation to execute
 */
export type ToolsMemoryQueryCreateBodyObj1Input = {
  /**
   * An optional data source used to replace refs in the mutation
   */
  attrSource?: Record<string, any | undefined> | undefined;
  /**
   * The data to insert, update, or delete
   */
  data: Record<string, any | undefined>;
  /**
   * The type of the mutation
   */
  type: "create" | "delete" | "update" | "upsert";
  /**
   * The where clause to filter the data to update or delete
   */
  where: Record<string, any | undefined>;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (Record<string, any | undefined> | undefined)
    | Record<string, any | undefined>
    | ("create" | "delete" | "update" | "upsert")
    | Record<string, any | undefined>
    | any
    | null
    | undefined;
};

/**
 * @internal
 * ToolsMemoryQueryCreateBodyObj1Input without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsMemoryQueryCreateBodyObj1Input = {
  $source?: Record<string, any | undefined> | undefined;
  data: Record<string, any | undefined>;
  type: "create" | "delete" | "update" | "upsert";
  where: Record<string, any | undefined>;

  [additionalProperty: string]:
    | (Record<string, any | undefined> | undefined)
    | Record<string, any | undefined>
    | ("create" | "delete" | "update" | "upsert")
    | Record<string, any | undefined>
    | External$ToolsMemoryQueryCreateBodyObj1Input
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsMemoryQueryCreateBodyObj1Input
 */
const SchemaIn$ToolsMemoryQueryCreateBodyObj1Input: z.ZodType<
  ToolsMemoryQueryCreateBodyObj1Input, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    $source: z.record(z.string(), zodRequiredAny.optional()).optional(),
    data: z.record(z.string(), zodRequiredAny.optional()),
    type: z.enum(["create", "delete", "update", "upsert"]),
    where: z.record(z.string(), zodRequiredAny.optional()),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      $source: "attrSource",
      data: "data",
      type: "type",
      where: "where",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsMemoryQueryCreateBodyObj1Input
 */
const SchemaOut$ToolsMemoryQueryCreateBodyObj1Input: z.ZodType<
  External$ToolsMemoryQueryCreateBodyObj1Input, // output type of this zod object
  z.ZodTypeDef,
  ToolsMemoryQueryCreateBodyObj1Input // the object to be transformed
> = z
  .object({
    attrSource: z.record(z.string(), zodRequiredAny.optional()).optional(),
    data: z.record(z.string(), zodRequiredAny.optional()),
    type: z.enum(["create", "delete", "update", "upsert"]),
    where: z.record(z.string(), zodRequiredAny.optional()),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      attrSource: "$source",
      data: "data",
      type: "type",
      where: "where",
    });
  });

export const Schemas$ToolsMemoryQueryCreateBodyObj1Input = {
  in: SchemaIn$ToolsMemoryQueryCreateBodyObj1Input,
  out: SchemaOut$ToolsMemoryQueryCreateBodyObj1Input,
};
