/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$ToolsStructuredOutputCreateBodyParams,
  Schemas$ToolsStructuredOutputCreateBodyParams,
  ToolsStructuredOutputCreateBodyParams,
} from "./tools-structured-output-create-body-params";

/**
 * ToolsStructuredOutputCreateBody
 */
export type ToolsStructuredOutputCreateBody = {
  /**
   * the unstructured data to format
   */
  input: string;
  params?: ToolsStructuredOutputCreateBodyParams | undefined;
  schema: Record<string, any | undefined> | any[];
  /**
   * Whether to validate the schema against the input
   */
  validate?: boolean | undefined;
};

/**
 * @internal
 * ToolsStructuredOutputCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsStructuredOutputCreateBody = {
  input: string;
  params?: External$ToolsStructuredOutputCreateBodyParams | undefined;
  schema: Record<string, any | undefined> | any[];
  validate?: boolean | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsStructuredOutputCreateBody
 */
const SchemaIn$ToolsStructuredOutputCreateBody: z.ZodType<
  ToolsStructuredOutputCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    input: z.string(),
    params: Schemas$ToolsStructuredOutputCreateBodyParams.in.optional(),
    schema: z.union([
      z.record(z.string(), zodRequiredAny.optional()),
      z.array(zodRequiredAny),
    ]),
    validate: z.boolean().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      input: "input",
      params: "params",
      schema: "schema",
      validate: "validate",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsStructuredOutputCreateBody
 */
const SchemaOut$ToolsStructuredOutputCreateBody: z.ZodType<
  External$ToolsStructuredOutputCreateBody, // output type of this zod object
  z.ZodTypeDef,
  ToolsStructuredOutputCreateBody // the object to be transformed
> = z
  .object({
    input: z.string(),
    params: Schemas$ToolsStructuredOutputCreateBodyParams.out.optional(),
    schema: z.union([
      z.record(z.string(), zodRequiredAny.optional()),
      z.array(zodRequiredAny),
    ]),
    validate: z.boolean().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      input: "input",
      params: "params",
      schema: "schema",
      validate: "validate",
    });
  });

export const Schemas$ToolsStructuredOutputCreateBody = {
  in: SchemaIn$ToolsStructuredOutputCreateBody,
  out: SchemaOut$ToolsStructuredOutputCreateBody,
};
