/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$ToolsMemoryQueryCreateBodyObj0Input,
  Schemas$ToolsMemoryQueryCreateBodyObj0Input,
  ToolsMemoryQueryCreateBodyObj0Input,
} from "./tools-memory-query-create-body-obj0-input";

/**
 * ToolsMemoryQueryCreateBodyObj0
 */
export type ToolsMemoryQueryCreateBodyObj0 = {
  input: ToolsMemoryQueryCreateBodyObj0Input;
  /**
   * The id of the memory table to search for
   */
  tableId: string;
  /**
   * The type of the query
   */
  type: "QUERY";

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | ToolsMemoryQueryCreateBodyObj0Input
    | string
    | "QUERY"
    | any
    | null
    | undefined;
};

/**
 * @internal
 * ToolsMemoryQueryCreateBodyObj0 without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsMemoryQueryCreateBodyObj0 = {
  input: External$ToolsMemoryQueryCreateBodyObj0Input;
  table_id: string;
  type: "QUERY";

  [additionalProperty: string]:
    | External$ToolsMemoryQueryCreateBodyObj0Input
    | string
    | "QUERY"
    | External$ToolsMemoryQueryCreateBodyObj0
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsMemoryQueryCreateBodyObj0
 */
const SchemaIn$ToolsMemoryQueryCreateBodyObj0: z.ZodType<
  ToolsMemoryQueryCreateBodyObj0, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    input: Schemas$ToolsMemoryQueryCreateBodyObj0Input.in,
    table_id: z.string(),
    type: z.enum(["QUERY"]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      input: "input",
      table_id: "tableId",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsMemoryQueryCreateBodyObj0
 */
const SchemaOut$ToolsMemoryQueryCreateBodyObj0: z.ZodType<
  External$ToolsMemoryQueryCreateBodyObj0, // output type of this zod object
  z.ZodTypeDef,
  ToolsMemoryQueryCreateBodyObj0 // the object to be transformed
> = z
  .object({
    input: Schemas$ToolsMemoryQueryCreateBodyObj0Input.out,
    tableId: z.string(),
    type: z.enum(["QUERY"]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      input: "input",
      tableId: "table_id",
      type: "type",
    });
  });

export const Schemas$ToolsMemoryQueryCreateBodyObj0 = {
  in: SchemaIn$ToolsMemoryQueryCreateBodyObj0,
  out: SchemaOut$ToolsMemoryQueryCreateBodyObj0,
};
