/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$ToolsInternetSearchCreateBodyMessagesItem,
  Schemas$ToolsInternetSearchCreateBodyMessagesItem,
  ToolsInternetSearchCreateBodyMessagesItem,
} from "./tools-internet-search-create-body-messages-item";

/**
 * ToolsInternetSearchCreateBody
 */
export type ToolsInternetSearchCreateBody = {
  /**
   * The maximum number of tokens to generate
   */
  maxTokens?: number | null | undefined;
  /**
   * The maximum number of times the tool can be used
   */
  maxUses?: number | null | undefined;
  messages: ToolsInternetSearchCreateBodyMessagesItem[];
  /**
   * The name of the model to use for the LLM
   */
  model?: string | null | undefined;
  /**
   * The stop sequences to use for the LLM
   */
  stopSequences?: string[] | null | undefined;
  system: string;
  /**
   * The temperature to use for the LLM
   */
  temperature?: number | null | undefined;
  /**
   * The top k to use for the LLM
   */
  topK?: number | null | undefined;
  /**
   * The top p to use for the LLM
   */
  topP?: number | null | undefined;
};

/**
 * @internal
 * ToolsInternetSearchCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ToolsInternetSearchCreateBody = {
  max_tokens?: number | null | undefined;
  max_uses?: number | null | undefined;
  messages: External$ToolsInternetSearchCreateBodyMessagesItem[];
  model?: string | null | undefined;
  stop_sequences?: string[] | null | undefined;
  system: string;
  temperature?: number | null | undefined;
  top_k?: number | null | undefined;
  top_p?: number | null | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ToolsInternetSearchCreateBody
 */
const SchemaIn$ToolsInternetSearchCreateBody: z.ZodType<
  ToolsInternetSearchCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    max_tokens: z.number().int().nullable().optional(),
    max_uses: z.number().int().nullable().optional(),
    messages: z.array(Schemas$ToolsInternetSearchCreateBodyMessagesItem.in),
    model: z.string().nullable().optional(),
    stop_sequences: z.array(z.string()).nullable().optional(),
    system: z.string(),
    temperature: z.number().nullable().optional(),
    top_k: z.number().int().nullable().optional(),
    top_p: z.number().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      max_tokens: "maxTokens",
      max_uses: "maxUses",
      messages: "messages",
      model: "model",
      stop_sequences: "stopSequences",
      system: "system",
      temperature: "temperature",
      top_k: "topK",
      top_p: "topP",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ToolsInternetSearchCreateBody
 */
const SchemaOut$ToolsInternetSearchCreateBody: z.ZodType<
  External$ToolsInternetSearchCreateBody, // output type of this zod object
  z.ZodTypeDef,
  ToolsInternetSearchCreateBody // the object to be transformed
> = z
  .object({
    maxTokens: z.number().int().nullable().optional(),
    maxUses: z.number().int().nullable().optional(),
    messages: z.array(Schemas$ToolsInternetSearchCreateBodyMessagesItem.out),
    model: z.string().nullable().optional(),
    stopSequences: z.array(z.string()).nullable().optional(),
    system: z.string(),
    temperature: z.number().nullable().optional(),
    topK: z.number().int().nullable().optional(),
    topP: z.number().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      maxTokens: "max_tokens",
      maxUses: "max_uses",
      messages: "messages",
      model: "model",
      stopSequences: "stop_sequences",
      system: "system",
      temperature: "temperature",
      topK: "top_k",
      topP: "top_p",
    });
  });

export const Schemas$ToolsInternetSearchCreateBody = {
  in: SchemaIn$ToolsInternetSearchCreateBody,
  out: SchemaOut$ToolsInternetSearchCreateBody,
};
