/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkflowsVersionsTasksCreateBody
 */
export type WorkflowsVersionsTasksCreateBody = {
  /**
   * Arbitrary JSON config object
   */
  config: Record<string, any | undefined> | null;
  /**
   * Description of the task
   */
  description: string | null;
  /**
   * Name of the task
   */
  name: string;
  /**
   * Output schema as JSON
   */
  outputSchema: Record<string, any | undefined> | null;
  /**
   * Parent tasks as a JSON object. {<task_id>: {dependent: true, conditions:<condition_set>}}
   */
  parentTasks: Record<string, any | undefined>;
  /**
   * Name of the tool to create the task for. e.g "Code Execution"
   */
  toolName: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (Record<string, any | undefined> | null)
    | (string | null)
    | string
    | (Record<string, any | undefined> | null)
    | Record<string, any | undefined>
    | string
    | any
    | null
    | undefined;
};

/**
 * @internal
 * WorkflowsVersionsTasksCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsVersionsTasksCreateBody = {
  config: Record<string, any | undefined> | null;
  description: string | null;
  name: string;
  output_schema: Record<string, any | undefined> | null;
  parent_tasks: Record<string, any | undefined>;
  tool_name: string;

  [additionalProperty: string]:
    | (Record<string, any | undefined> | null)
    | (string | null)
    | string
    | (Record<string, any | undefined> | null)
    | Record<string, any | undefined>
    | string
    | External$WorkflowsVersionsTasksCreateBody
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsVersionsTasksCreateBody
 */
const SchemaIn$WorkflowsVersionsTasksCreateBody: z.ZodType<
  WorkflowsVersionsTasksCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    config: z.record(z.string(), zodRequiredAny.optional()).nullable(),
    description: z.string().nullable(),
    name: z.string(),
    output_schema: z.record(z.string(), zodRequiredAny.optional()).nullable(),
    parent_tasks: z.record(z.string(), zodRequiredAny.optional()),
    tool_name: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      description: "description",
      name: "name",
      output_schema: "outputSchema",
      parent_tasks: "parentTasks",
      tool_name: "toolName",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsVersionsTasksCreateBody
 */
const SchemaOut$WorkflowsVersionsTasksCreateBody: z.ZodType<
  External$WorkflowsVersionsTasksCreateBody, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsVersionsTasksCreateBody // the object to be transformed
> = z
  .object({
    config: z.record(z.string(), zodRequiredAny.optional()).nullable(),
    description: z.string().nullable(),
    name: z.string(),
    outputSchema: z.record(z.string(), zodRequiredAny.optional()).nullable(),
    parentTasks: z.record(z.string(), zodRequiredAny.optional()),
    toolName: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      description: "description",
      name: "name",
      outputSchema: "output_schema",
      parentTasks: "parent_tasks",
      toolName: "tool_name",
    });
  });

export const Schemas$WorkflowsVersionsTasksCreateBody = {
  in: SchemaIn$WorkflowsVersionsTasksCreateBody,
  out: SchemaOut$WorkflowsVersionsTasksCreateBody,
};
