/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$WorkflowsInvokeCreateResponseWorkflow,
  Schemas$WorkflowsInvokeCreateResponseWorkflow,
  WorkflowsInvokeCreateResponseWorkflow,
} from "./workflows-invoke-create-response-workflow";

/**
 * WorkflowsInvokeCreateResponse
 */
export type WorkflowsInvokeCreateResponse = {
  id: string;
  outputs?: Record<string, any | undefined> | null | undefined;
  status: string;
  workflow: WorkflowsInvokeCreateResponseWorkflow;
};

/**
 * @internal
 * WorkflowsInvokeCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsInvokeCreateResponse = {
  id: string;
  outputs?: Record<string, any | undefined> | null | undefined;
  status: string;
  workflow: External$WorkflowsInvokeCreateResponseWorkflow;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsInvokeCreateResponse
 */
const SchemaIn$WorkflowsInvokeCreateResponse: z.ZodType<
  WorkflowsInvokeCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    id: z.string(),
    outputs: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    status: z.string(),
    workflow: Schemas$WorkflowsInvokeCreateResponseWorkflow.in,
  })
  .transform((obj) => {
    return zodTransform(obj, {
      id: "id",
      outputs: "outputs",
      status: "status",
      workflow: "workflow",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsInvokeCreateResponse
 */
const SchemaOut$WorkflowsInvokeCreateResponse: z.ZodType<
  External$WorkflowsInvokeCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsInvokeCreateResponse // the object to be transformed
> = z
  .object({
    id: z.string(),
    outputs: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    status: z.string(),
    workflow: Schemas$WorkflowsInvokeCreateResponseWorkflow.out,
  })
  .transform((obj) => {
    return zodTransform(obj, {
      id: "id",
      outputs: "outputs",
      status: "status",
      workflow: "workflow",
    });
  });

export const Schemas$WorkflowsInvokeCreateResponse = {
  in: SchemaIn$WorkflowsInvokeCreateResponse,
  out: SchemaOut$WorkflowsInvokeCreateResponse,
};
