/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkflowsVersionsGetResponse
 */
export type WorkflowsVersionsGetResponse = {
  /**
   * Access level for the workflow (e.g., PRIVATE or PUBLIC)
   */
  access: string;
  /**
   * Whether the workflow is active or not
   */
  active: boolean;
  /**
   * Creation timestamp for the workflow
   */
  createdAt: string;
  /**
   * Description of the workflow
   */
  description: string;
  /**
   * Associated feed identifier
   */
  feedId: string;
  /**
   * Unique identifier for the workflow
   */
  id: string;
  /**
   * Optional workflow instructions
   */
  instructions?: string | undefined;
  /**
   * Name of the workflow
   */
  name: string;
  /**
   * User identifier that owns or created the workflow
   */
  userId: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | boolean
    | string
    | string
    | string
    | string
    | (string | undefined)
    | string
    | string
    | any
    | null
    | undefined;
};

/**
 * @internal
 * WorkflowsVersionsGetResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsVersionsGetResponse = {
  access: string;
  active: boolean;
  created_at: string;
  description: string;
  feed_id: string;
  id: string;
  instructions?: string | undefined;
  name: string;
  user_id: string;

  [additionalProperty: string]:
    | string
    | boolean
    | string
    | string
    | string
    | string
    | (string | undefined)
    | string
    | string
    | External$WorkflowsVersionsGetResponse
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsVersionsGetResponse
 */
const SchemaIn$WorkflowsVersionsGetResponse: z.ZodType<
  WorkflowsVersionsGetResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    access: z.string(),
    active: z.boolean(),
    created_at: z.string(),
    description: z.string(),
    feed_id: z.string(),
    id: z.string(),
    instructions: z.string().optional(),
    name: z.string(),
    user_id: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      access: "access",
      active: "active",
      created_at: "createdAt",
      description: "description",
      feed_id: "feedId",
      id: "id",
      instructions: "instructions",
      name: "name",
      user_id: "userId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsVersionsGetResponse
 */
const SchemaOut$WorkflowsVersionsGetResponse: z.ZodType<
  External$WorkflowsVersionsGetResponse, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsVersionsGetResponse // the object to be transformed
> = z
  .object({
    access: z.string(),
    active: z.boolean(),
    createdAt: z.string(),
    description: z.string(),
    feedId: z.string(),
    id: z.string(),
    instructions: z.string().optional(),
    name: z.string(),
    userId: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      access: "access",
      active: "active",
      createdAt: "created_at",
      description: "description",
      feedId: "feed_id",
      id: "id",
      instructions: "instructions",
      name: "name",
      userId: "user_id",
    });
  });

export const Schemas$WorkflowsVersionsGetResponse = {
  in: SchemaIn$WorkflowsVersionsGetResponse,
  out: SchemaOut$WorkflowsVersionsGetResponse,
};
