/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkspaceVariablesDeleteResponse
 */
export type WorkspaceVariablesDeleteResponse = {
  deleted?: boolean | undefined;
  id?: string | undefined;
  name?: string | undefined;
};

/**
 * @internal
 * WorkspaceVariablesDeleteResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkspaceVariablesDeleteResponse = {
  deleted?: boolean | undefined;
  id?: string | undefined;
  name?: string | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkspaceVariablesDeleteResponse
 */
const SchemaIn$WorkspaceVariablesDeleteResponse: z.ZodType<
  WorkspaceVariablesDeleteResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    deleted: z.boolean().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      deleted: "deleted",
      id: "id",
      name: "name",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkspaceVariablesDeleteResponse
 */
const SchemaOut$WorkspaceVariablesDeleteResponse: z.ZodType<
  External$WorkspaceVariablesDeleteResponse, // output type of this zod object
  z.ZodTypeDef,
  WorkspaceVariablesDeleteResponse // the object to be transformed
> = z
  .object({
    deleted: z.boolean().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      deleted: "deleted",
      id: "id",
      name: "name",
    });
  });

export const Schemas$WorkspaceVariablesDeleteResponse = {
  in: SchemaIn$WorkspaceVariablesDeleteResponse,
  out: SchemaOut$WorkspaceVariablesDeleteResponse,
};
