/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkspaceVariablesCreateResponse
 */
export type WorkspaceVariablesCreateResponse = {
  apiId?: string | null | undefined;
  createdAt?: string | undefined;
  description?: string | null | undefined;
  id?: string | undefined;
  isSecret?: boolean | undefined;
  name?: string | undefined;
  originId?: string | null | undefined;
  userId?: string | null | undefined;
  value?: string | null | undefined;
};

/**
 * @internal
 * WorkspaceVariablesCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkspaceVariablesCreateResponse = {
  api_id?: string | null | undefined;
  created_at?: string | undefined;
  description?: string | null | undefined;
  id?: string | undefined;
  is_secret?: boolean | undefined;
  name?: string | undefined;
  origin_id?: string | null | undefined;
  user_id?: string | null | undefined;
  value?: string | null | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkspaceVariablesCreateResponse
 */
const SchemaIn$WorkspaceVariablesCreateResponse: z.ZodType<
  WorkspaceVariablesCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    api_id: z.string().nullable().optional(),
    created_at: z.string().optional(),
    description: z.string().nullable().optional(),
    id: z.string().optional(),
    is_secret: z.boolean().optional(),
    name: z.string().optional(),
    origin_id: z.string().nullable().optional(),
    user_id: z.string().nullable().optional(),
    value: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      api_id: "apiId",
      created_at: "createdAt",
      description: "description",
      id: "id",
      is_secret: "isSecret",
      name: "name",
      origin_id: "originId",
      user_id: "userId",
      value: "value",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkspaceVariablesCreateResponse
 */
const SchemaOut$WorkspaceVariablesCreateResponse: z.ZodType<
  External$WorkspaceVariablesCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  WorkspaceVariablesCreateResponse // the object to be transformed
> = z
  .object({
    apiId: z.string().nullable().optional(),
    createdAt: z.string().optional(),
    description: z.string().nullable().optional(),
    id: z.string().optional(),
    isSecret: z.boolean().optional(),
    name: z.string().optional(),
    originId: z.string().nullable().optional(),
    userId: z.string().nullable().optional(),
    value: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      apiId: "api_id",
      createdAt: "created_at",
      description: "description",
      id: "id",
      isSecret: "is_secret",
      name: "name",
      originId: "origin_id",
      userId: "user_id",
      value: "value",
    });
  });

export const Schemas$WorkspaceVariablesCreateResponse = {
  in: SchemaIn$WorkspaceVariablesCreateResponse,
  out: SchemaOut$WorkspaceVariablesCreateResponse,
};
