/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkflowsRunsDeleteResponse
 */
export type WorkflowsRunsDeleteResponse = {
  createdAt?: string | undefined;
  id: string;
  status?: ("EXITED" | "FAILED" | "FINISHED" | "IDLE" | "PENDING") | undefined;
  workflowId: string;
};

/**
 * @internal
 * WorkflowsRunsDeleteResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsRunsDeleteResponse = {
  created_at?: string | undefined;
  id: string;
  status?: ("EXITED" | "FAILED" | "FINISHED" | "IDLE" | "PENDING") | undefined;
  workflow_id: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsRunsDeleteResponse
 */
const SchemaIn$WorkflowsRunsDeleteResponse: z.ZodType<
  WorkflowsRunsDeleteResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string().optional(),
    id: z.string(),
    status: z
      .enum(["EXITED", "FAILED", "FINISHED", "IDLE", "PENDING"])
      .optional(),
    workflow_id: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      id: "id",
      status: "status",
      workflow_id: "workflowId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsRunsDeleteResponse
 */
const SchemaOut$WorkflowsRunsDeleteResponse: z.ZodType<
  External$WorkflowsRunsDeleteResponse, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsRunsDeleteResponse // the object to be transformed
> = z
  .object({
    createdAt: z.string().optional(),
    id: z.string(),
    status: z
      .enum(["EXITED", "FAILED", "FINISHED", "IDLE", "PENDING"])
      .optional(),
    workflowId: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      id: "id",
      status: "status",
      workflowId: "workflow_id",
    });
  });

export const Schemas$WorkflowsRunsDeleteResponse = {
  in: SchemaIn$WorkflowsRunsDeleteResponse,
  out: SchemaOut$WorkflowsRunsDeleteResponse,
};
