/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkflowsDeleteResponse
 */
export type WorkflowsDeleteResponse = {
  /**
   * Creation timestamp
   */
  createdAt: string;
  /**
   * Description of the workflow
   */
  description: string;
  /**
   * Unique identifier for the workflow origin
   */
  id: string;
  /**
   * Name of the workflow
   */
  name: string;
  /**
   * Parent origin ID if this is a fork
   */
  originId?: string | null | undefined;
  /**
   * Last update timestamp
   */
  updatedAt: string;
  /**
   * User ID of the owner
   */
  userId: string;
  /**
   * The ID of the current active workflow version
   */
  workflowId: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | string
    | string
    | string
    | (string | null | undefined)
    | string
    | string
    | string
    | any
    | null
    | undefined;
};

/**
 * @internal
 * WorkflowsDeleteResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsDeleteResponse = {
  created_at: string;
  description: string;
  id: string;
  name: string;
  origin_id?: string | null | undefined;
  updated_at: string;
  user_id: string;
  workflow_id: string;

  [additionalProperty: string]:
    | string
    | string
    | string
    | string
    | (string | null | undefined)
    | string
    | string
    | string
    | External$WorkflowsDeleteResponse
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsDeleteResponse
 */
const SchemaIn$WorkflowsDeleteResponse: z.ZodType<
  WorkflowsDeleteResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string(),
    description: z.string(),
    id: z.string(),
    name: z.string(),
    origin_id: z.string().nullable().optional(),
    updated_at: z.string(),
    user_id: z.string(),
    workflow_id: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      description: "description",
      id: "id",
      name: "name",
      origin_id: "originId",
      updated_at: "updatedAt",
      user_id: "userId",
      workflow_id: "workflowId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsDeleteResponse
 */
const SchemaOut$WorkflowsDeleteResponse: z.ZodType<
  External$WorkflowsDeleteResponse, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsDeleteResponse // the object to be transformed
> = z
  .object({
    createdAt: z.string(),
    description: z.string(),
    id: z.string(),
    name: z.string(),
    originId: z.string().nullable().optional(),
    updatedAt: z.string(),
    userId: z.string(),
    workflowId: z.string(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      description: "description",
      id: "id",
      name: "name",
      originId: "origin_id",
      updatedAt: "updated_at",
      userId: "user_id",
      workflowId: "workflow_id",
    });
  });

export const Schemas$WorkflowsDeleteResponse = {
  in: SchemaIn$WorkflowsDeleteResponse,
  out: SchemaOut$WorkflowsDeleteResponse,
};
