/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$WorkflowsCreateResponseVersionsItem,
  Schemas$WorkflowsCreateResponseVersionsItem,
  WorkflowsCreateResponseVersionsItem,
} from "./workflows-create-response-versions-item";

/**
 * WorkflowsCreateResponse
 */
export type WorkflowsCreateResponse = {
  /**
   * Creation timestamp
   */
  createdAt?: string | undefined;
  /**
   * Description of the workflow
   */
  description?: string | undefined;
  /**
   * Unique identifier for the workflow origin
   */
  id?: string | undefined;
  /**
   * Name of the workflow
   */
  name?: string | undefined;
  /**
   * Parent origin ID if this is a fork
   */
  originId?: string | null | undefined;
  /**
   * Last update timestamp
   */
  updatedAt?: string | undefined;
  /**
   * User ID of the owner
   */
  userId?: string | undefined;
  versions?: WorkflowsCreateResponseVersionsItem[] | undefined;
  /**
   * The ID of the current active workflow version
   */
  workflowId?: string | undefined;
};

/**
 * @internal
 * WorkflowsCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsCreateResponse = {
  created_at?: string | undefined;
  description?: string | undefined;
  id?: string | undefined;
  name?: string | undefined;
  origin_id?: string | null | undefined;
  updated_at?: string | undefined;
  user_id?: string | undefined;
  versions?: External$WorkflowsCreateResponseVersionsItem[] | undefined;
  workflow_id?: string | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsCreateResponse
 */
const SchemaIn$WorkflowsCreateResponse: z.ZodType<
  WorkflowsCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    created_at: z.string().optional(),
    description: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    origin_id: z.string().nullable().optional(),
    updated_at: z.string().optional(),
    user_id: z.string().optional(),
    versions: z
      .array(Schemas$WorkflowsCreateResponseVersionsItem.in)
      .optional(),
    workflow_id: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      created_at: "createdAt",
      description: "description",
      id: "id",
      name: "name",
      origin_id: "originId",
      updated_at: "updatedAt",
      user_id: "userId",
      versions: "versions",
      workflow_id: "workflowId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsCreateResponse
 */
const SchemaOut$WorkflowsCreateResponse: z.ZodType<
  External$WorkflowsCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsCreateResponse // the object to be transformed
> = z
  .object({
    createdAt: z.string().optional(),
    description: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    originId: z.string().nullable().optional(),
    updatedAt: z.string().optional(),
    userId: z.string().optional(),
    versions: z
      .array(Schemas$WorkflowsCreateResponseVersionsItem.out)
      .optional(),
    workflowId: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      createdAt: "created_at",
      description: "description",
      id: "id",
      name: "name",
      originId: "origin_id",
      updatedAt: "updated_at",
      userId: "user_id",
      versions: "versions",
      workflowId: "workflow_id",
    });
  });

export const Schemas$WorkflowsCreateResponse = {
  in: SchemaIn$WorkflowsCreateResponse,
  out: SchemaOut$WorkflowsCreateResponse,
};
