/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkflowsVersionsGetResponseTasksItemTool
 */
export type WorkflowsVersionsGetResponseTasksItemTool = {
  description: string;
  id: string;
  name: string;
};

/**
 * @internal
 * WorkflowsVersionsGetResponseTasksItemTool without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsVersionsGetResponseTasksItemTool = {
  description: string;
  id: string;
  name: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsVersionsGetResponseTasksItemTool
 */
const SchemaIn$WorkflowsVersionsGetResponseTasksItemTool: z.ZodType<
  WorkflowsVersionsGetResponseTasksItemTool, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    description: z.string(),
    id: z.string(),
    name: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      id: "id",
      name: "name",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsVersionsGetResponseTasksItemTool
 */
const SchemaOut$WorkflowsVersionsGetResponseTasksItemTool: z.ZodType<
  External$WorkflowsVersionsGetResponseTasksItemTool, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsVersionsGetResponseTasksItemTool // the object to be transformed
> = z
  .object({
    description: z.string(),
    id: z.string(),
    name: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      id: "id",
      name: "name",
    });
  });

export const Schemas$WorkflowsVersionsGetResponseTasksItemTool = {
  in: SchemaIn$WorkflowsVersionsGetResponseTasksItemTool,
  out: SchemaOut$WorkflowsVersionsGetResponseTasksItemTool,
};
