/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkflowsVersionsPatchBody
 */
export type WorkflowsVersionsPatchBody = {
  /**
   * Updated active status
   */
  active?: boolean | undefined;
  /**
   * Updated description
   */
  description?: string | undefined;
  /**
   * Updated name
   */
  name?: string | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (boolean | undefined)
    | (string | undefined)
    | (string | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * WorkflowsVersionsPatchBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsVersionsPatchBody = {
  active?: boolean | undefined;
  description?: string | undefined;
  name?: string | undefined;

  [additionalProperty: string]:
    | (boolean | undefined)
    | (string | undefined)
    | (string | undefined)
    | External$WorkflowsVersionsPatchBody
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsVersionsPatchBody
 */
const SchemaIn$WorkflowsVersionsPatchBody: z.ZodType<
  WorkflowsVersionsPatchBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    active: z.boolean().optional(),
    description: z.string().optional(),
    name: z.string().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      active: "active",
      description: "description",
      name: "name",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsVersionsPatchBody
 */
const SchemaOut$WorkflowsVersionsPatchBody: z.ZodType<
  External$WorkflowsVersionsPatchBody, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsVersionsPatchBody // the object to be transformed
> = z
  .object({
    active: z.boolean().optional(),
    description: z.string().optional(),
    name: z.string().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      active: "active",
      description: "description",
      name: "name",
    });
  });

export const Schemas$WorkflowsVersionsPatchBody = {
  in: SchemaIn$WorkflowsVersionsPatchBody,
  out: SchemaOut$WorkflowsVersionsPatchBody,
};
