/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkspaceVariablesCreateBody
 */
export type WorkspaceVariablesCreateBody = {
  apiId?: string | null | undefined;
  description?: string | null | undefined;
  isSecret?: boolean | undefined;
  name: string;
  originId?: string | null | undefined;
  value?: string | null | undefined;
};

/**
 * @internal
 * WorkspaceVariablesCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkspaceVariablesCreateBody = {
  api_id?: string | null | undefined;
  description?: string | null | undefined;
  is_secret?: boolean | undefined;
  name: string;
  origin_id?: string | null | undefined;
  value?: string | null | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkspaceVariablesCreateBody
 */
const SchemaIn$WorkspaceVariablesCreateBody: z.ZodType<
  WorkspaceVariablesCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    api_id: z.string().nullable().optional(),
    description: z.string().nullable().optional(),
    is_secret: z.boolean().optional(),
    name: z.string(),
    origin_id: z.string().nullable().optional(),
    value: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      api_id: "apiId",
      description: "description",
      is_secret: "isSecret",
      name: "name",
      origin_id: "originId",
      value: "value",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkspaceVariablesCreateBody
 */
const SchemaOut$WorkspaceVariablesCreateBody: z.ZodType<
  External$WorkspaceVariablesCreateBody, // output type of this zod object
  z.ZodTypeDef,
  WorkspaceVariablesCreateBody // the object to be transformed
> = z
  .object({
    apiId: z.string().nullable().optional(),
    description: z.string().nullable().optional(),
    isSecret: z.boolean().optional(),
    name: z.string(),
    originId: z.string().nullable().optional(),
    value: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      apiId: "api_id",
      description: "description",
      isSecret: "is_secret",
      name: "name",
      originId: "origin_id",
      value: "value",
    });
  });

export const Schemas$WorkspaceVariablesCreateBody = {
  in: SchemaIn$WorkspaceVariablesCreateBody,
  out: SchemaOut$WorkspaceVariablesCreateBody,
};
