/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$WorkflowsVersionsGetResponseOrigin,
  Schemas$WorkflowsVersionsGetResponseOrigin,
  WorkflowsVersionsGetResponseOrigin,
} from "./workflows-versions-get-response-origin";
import {
  External$WorkflowsVersionsGetResponseTasksItem,
  Schemas$WorkflowsVersionsGetResponseTasksItem,
  WorkflowsVersionsGetResponseTasksItem,
} from "./workflows-versions-get-response-tasks-item";

/**
 * WorkflowsVersionsGetResponse
 */
export type WorkflowsVersionsGetResponse = {
  /**
   * Access level for the workflow (e.g., PRIVATE or PUBLIC)
   */
  access?: string | undefined;
  /**
   * Whether the workflow is active or not
   */
  active?: boolean | undefined;
  /**
   * Creation timestamp for the workflow
   */
  createdAt?: string | undefined;
  /**
   * Description of the workflow
   */
  description?: string | undefined;
  /**
   * Associated feed identifier
   */
  feedId?: string | undefined;
  /**
   * Unique identifier for the workflow
   */
  id?: string | undefined;
  /**
   * Optional workflow instructions
   */
  instructions?: string | undefined;
  /**
   * Name of the workflow
   */
  name?: string | undefined;
  origin?: WorkflowsVersionsGetResponseOrigin | undefined;
  /**
   * Tasks for the workflow version
   */
  tasks?: WorkflowsVersionsGetResponseTasksItem[] | undefined;
  /**
   * User identifier that owns or created the workflow
   */
  userId?: string | undefined;
};

/**
 * @internal
 * WorkflowsVersionsGetResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsVersionsGetResponse = {
  access?: string | undefined;
  active?: boolean | undefined;
  created_at?: string | undefined;
  description?: string | undefined;
  feed_id?: string | undefined;
  id?: string | undefined;
  instructions?: string | undefined;
  name?: string | undefined;
  origin?: External$WorkflowsVersionsGetResponseOrigin | undefined;
  tasks?: External$WorkflowsVersionsGetResponseTasksItem[] | undefined;
  user_id?: string | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsVersionsGetResponse
 */
const SchemaIn$WorkflowsVersionsGetResponse: z.ZodType<
  WorkflowsVersionsGetResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    access: z.string().optional(),
    active: z.boolean().optional(),
    created_at: z.string().optional(),
    description: z.string().optional(),
    feed_id: z.string().optional(),
    id: z.string().optional(),
    instructions: z.string().optional(),
    name: z.string().optional(),
    origin: Schemas$WorkflowsVersionsGetResponseOrigin.in.optional(),
    tasks: z.array(Schemas$WorkflowsVersionsGetResponseTasksItem.in).optional(),
    user_id: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      access: "access",
      active: "active",
      created_at: "createdAt",
      description: "description",
      feed_id: "feedId",
      id: "id",
      instructions: "instructions",
      name: "name",
      origin: "origin",
      tasks: "tasks",
      user_id: "userId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsVersionsGetResponse
 */
const SchemaOut$WorkflowsVersionsGetResponse: z.ZodType<
  External$WorkflowsVersionsGetResponse, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsVersionsGetResponse // the object to be transformed
> = z
  .object({
    access: z.string().optional(),
    active: z.boolean().optional(),
    createdAt: z.string().optional(),
    description: z.string().optional(),
    feedId: z.string().optional(),
    id: z.string().optional(),
    instructions: z.string().optional(),
    name: z.string().optional(),
    origin: Schemas$WorkflowsVersionsGetResponseOrigin.out.optional(),
    tasks: z
      .array(Schemas$WorkflowsVersionsGetResponseTasksItem.out)
      .optional(),
    userId: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      access: "access",
      active: "active",
      createdAt: "created_at",
      description: "description",
      feedId: "feed_id",
      id: "id",
      instructions: "instructions",
      name: "name",
      origin: "origin",
      tasks: "tasks",
      userId: "user_id",
    });
  });

export const Schemas$WorkflowsVersionsGetResponse = {
  in: SchemaIn$WorkflowsVersionsGetResponse,
  out: SchemaOut$WorkflowsVersionsGetResponse,
};
