/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$WorkflowsVersionsGetResponseTasksItemTool,
  Schemas$WorkflowsVersionsGetResponseTasksItemTool,
  WorkflowsVersionsGetResponseTasksItemTool,
} from "./workflows-versions-get-response-tasks-item-tool";

/**
 * WorkflowsVersionsGetResponseTasksItem
 */
export type WorkflowsVersionsGetResponseTasksItem = {
  /**
   * Arbitrary JSON config object or null
   */
  config?: Record<string, any | undefined> | null | undefined;
  /**
   * Creation timestamp or null
   */
  createdAt?: string | null | undefined;
  /**
   * Description of the workflow task or null
   */
  description?: string | null | undefined;
  /**
   * Unique identifier for the workflow task
   */
  id?: string | undefined;
  /**
   * Name of the workflow task
   */
  name?: string | undefined;
  /**
   * Output schema as JSON or null
   */
  outputSchema?: Record<string, any | undefined> | null | undefined;
  /**
   * Parent tasks as a JSON object
   */
  parentTasks?: Record<string, any | undefined> | undefined;
  tool?: WorkflowsVersionsGetResponseTasksItemTool | undefined;
  /**
   * Associated tool identifier
   */
  toolId?: string | undefined;
  /**
   * UI configuration as JSON or null
   */
  uiConfig?: Record<string, any | undefined> | null | undefined;
  /**
   * Associated workflow identifier
   */
  workflowId?: string | undefined;
};

/**
 * @internal
 * WorkflowsVersionsGetResponseTasksItem without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsVersionsGetResponseTasksItem = {
  config?: Record<string, any | undefined> | null | undefined;
  created_at?: string | null | undefined;
  description?: string | null | undefined;
  id?: string | undefined;
  name?: string | undefined;
  output_schema?: Record<string, any | undefined> | null | undefined;
  parent_tasks?: Record<string, any | undefined> | undefined;
  tool?: External$WorkflowsVersionsGetResponseTasksItemTool | undefined;
  tool_id?: string | undefined;
  ui_config?: Record<string, any | undefined> | null | undefined;
  workflow_id?: string | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsVersionsGetResponseTasksItem
 */
const SchemaIn$WorkflowsVersionsGetResponseTasksItem: z.ZodType<
  WorkflowsVersionsGetResponseTasksItem, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    config: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    created_at: z.string().nullable().optional(),
    description: z.string().nullable().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    output_schema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    parent_tasks: z.record(z.string(), zodRequiredAny.optional()).optional(),
    tool: Schemas$WorkflowsVersionsGetResponseTasksItemTool.in.optional(),
    tool_id: z.string().optional(),
    ui_config: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    workflow_id: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      created_at: "createdAt",
      description: "description",
      id: "id",
      name: "name",
      output_schema: "outputSchema",
      parent_tasks: "parentTasks",
      tool: "tool",
      tool_id: "toolId",
      ui_config: "uiConfig",
      workflow_id: "workflowId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsVersionsGetResponseTasksItem
 */
const SchemaOut$WorkflowsVersionsGetResponseTasksItem: z.ZodType<
  External$WorkflowsVersionsGetResponseTasksItem, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsVersionsGetResponseTasksItem // the object to be transformed
> = z
  .object({
    config: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    createdAt: z.string().nullable().optional(),
    description: z.string().nullable().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    outputSchema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    parentTasks: z.record(z.string(), zodRequiredAny.optional()).optional(),
    tool: Schemas$WorkflowsVersionsGetResponseTasksItemTool.out.optional(),
    toolId: z.string().optional(),
    uiConfig: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    workflowId: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      createdAt: "created_at",
      description: "description",
      id: "id",
      name: "name",
      outputSchema: "output_schema",
      parentTasks: "parent_tasks",
      tool: "tool",
      toolId: "tool_id",
      uiConfig: "ui_config",
      workflowId: "workflow_id",
    });
  });

export const Schemas$WorkflowsVersionsGetResponseTasksItem = {
  in: SchemaIn$WorkflowsVersionsGetResponseTasksItem,
  out: SchemaOut$WorkflowsVersionsGetResponseTasksItem,
};
