/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkflowsRunsDispatchCreateResponse
 */
export type WorkflowsRunsDispatchCreateResponse = {
  /**
   * The workflow run ID
   */
  id: string;
  /**
   * The updated run status
   */
  status: string;
};

/**
 * @internal
 * WorkflowsRunsDispatchCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsRunsDispatchCreateResponse = {
  id: string;
  status: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsRunsDispatchCreateResponse
 */
const SchemaIn$WorkflowsRunsDispatchCreateResponse: z.ZodType<
  WorkflowsRunsDispatchCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    id: z.string(),
    status: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      id: "id",
      status: "status",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsRunsDispatchCreateResponse
 */
const SchemaOut$WorkflowsRunsDispatchCreateResponse: z.ZodType<
  External$WorkflowsRunsDispatchCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsRunsDispatchCreateResponse // the object to be transformed
> = z
  .object({
    id: z.string(),
    status: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      id: "id",
      status: "status",
    });
  });

export const Schemas$WorkflowsRunsDispatchCreateResponse = {
  in: SchemaIn$WorkflowsRunsDispatchCreateResponse,
  out: SchemaOut$WorkflowsRunsDispatchCreateResponse,
};
