/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkspaceVariablesPatchBody
 */
export type WorkspaceVariablesPatchBody = {
  apiId?: string | null | undefined;
  description?: string | null | undefined;
  id: string;
  isSecret?: boolean | undefined;
  name?: string | undefined;
  originId?: string | null | undefined;
  value?: string | null | undefined;
};

/**
 * @internal
 * WorkspaceVariablesPatchBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkspaceVariablesPatchBody = {
  api_id?: string | null | undefined;
  description?: string | null | undefined;
  id: string;
  is_secret?: boolean | undefined;
  name?: string | undefined;
  origin_id?: string | null | undefined;
  value?: string | null | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkspaceVariablesPatchBody
 */
const SchemaIn$WorkspaceVariablesPatchBody: z.ZodType<
  WorkspaceVariablesPatchBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    api_id: z.string().nullable().optional(),
    description: z.string().nullable().optional(),
    id: z.string(),
    is_secret: z.boolean().optional(),
    name: z.string().optional(),
    origin_id: z.string().nullable().optional(),
    value: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      api_id: "apiId",
      description: "description",
      id: "id",
      is_secret: "isSecret",
      name: "name",
      origin_id: "originId",
      value: "value",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkspaceVariablesPatchBody
 */
const SchemaOut$WorkspaceVariablesPatchBody: z.ZodType<
  External$WorkspaceVariablesPatchBody, // output type of this zod object
  z.ZodTypeDef,
  WorkspaceVariablesPatchBody // the object to be transformed
> = z
  .object({
    apiId: z.string().nullable().optional(),
    description: z.string().nullable().optional(),
    id: z.string(),
    isSecret: z.boolean().optional(),
    name: z.string().optional(),
    originId: z.string().nullable().optional(),
    value: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      apiId: "api_id",
      description: "description",
      id: "id",
      isSecret: "is_secret",
      name: "name",
      originId: "origin_id",
      value: "value",
    });
  });

export const Schemas$WorkspaceVariablesPatchBody = {
  in: SchemaIn$WorkspaceVariablesPatchBody,
  out: SchemaOut$WorkspaceVariablesPatchBody,
};
