/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkflowsInvokeCreateBody
 */
export type WorkflowsInvokeCreateBody = {
  /**
   * The input for the workflow run
   */
  input: Record<string, any | undefined>;
  /**
   * The inputs for the workflow run (deprecated, use input instead)
   */
  inputs?: Record<string, any | undefined> | undefined;
  /**
   * Optional: The ID of the workflow run to invoke. Used for re-invoking a workflow run.
   */
  runId?: string | undefined;
  /**
   * Optional: The ID of the task to invoke. Used for re-invoking a workflow run from a specific task.
   */
  taskId?: string | undefined;
};

/**
 * @internal
 * WorkflowsInvokeCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsInvokeCreateBody = {
  input: Record<string, any | undefined>;
  inputs?: Record<string, any | undefined> | undefined;
  run_id?: string | undefined;
  task_id?: string | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsInvokeCreateBody
 */
const SchemaIn$WorkflowsInvokeCreateBody: z.ZodType<
  WorkflowsInvokeCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    input: z.record(z.string(), zodRequiredAny.optional()),
    inputs: z.record(z.string(), zodRequiredAny.optional()).optional(),
    run_id: z.string().optional(),
    task_id: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      input: "input",
      inputs: "inputs",
      run_id: "runId",
      task_id: "taskId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsInvokeCreateBody
 */
const SchemaOut$WorkflowsInvokeCreateBody: z.ZodType<
  External$WorkflowsInvokeCreateBody, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsInvokeCreateBody // the object to be transformed
> = z
  .object({
    input: z.record(z.string(), zodRequiredAny.optional()),
    inputs: z.record(z.string(), zodRequiredAny.optional()).optional(),
    runId: z.string().optional(),
    taskId: z.string().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      input: "input",
      inputs: "inputs",
      runId: "run_id",
      taskId: "task_id",
    });
  });

export const Schemas$WorkflowsInvokeCreateBody = {
  in: SchemaIn$WorkflowsInvokeCreateBody,
  out: SchemaOut$WorkflowsInvokeCreateBody,
};
