/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkflowsDispatchCreateBody
 */
export type WorkflowsDispatchCreateBody = {
  input: Record<string, any | undefined>;
};

/**
 * @internal
 * WorkflowsDispatchCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsDispatchCreateBody = {
  input: Record<string, any | undefined>;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsDispatchCreateBody
 */
const SchemaIn$WorkflowsDispatchCreateBody: z.ZodType<
  WorkflowsDispatchCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    input: z.record(z.string(), zodRequiredAny.optional()),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      input: "input",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsDispatchCreateBody
 */
const SchemaOut$WorkflowsDispatchCreateBody: z.ZodType<
  External$WorkflowsDispatchCreateBody, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsDispatchCreateBody // the object to be transformed
> = z
  .object({
    input: z.record(z.string(), zodRequiredAny.optional()),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      input: "input",
    });
  });

export const Schemas$WorkflowsDispatchCreateBody = {
  in: SchemaIn$WorkflowsDispatchCreateBody,
  out: SchemaOut$WorkflowsDispatchCreateBody,
};
