/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkflowsDispatchCreateResponse
 */
export type WorkflowsDispatchCreateResponse = {
  /**
   * The workflow run ID
   */
  id: string;
};

/**
 * @internal
 * WorkflowsDispatchCreateResponse without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsDispatchCreateResponse = {
  id: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsDispatchCreateResponse
 */
const SchemaIn$WorkflowsDispatchCreateResponse: z.ZodType<
  WorkflowsDispatchCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    id: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      id: "id",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsDispatchCreateResponse
 */
const SchemaOut$WorkflowsDispatchCreateResponse: z.ZodType<
  External$WorkflowsDispatchCreateResponse, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsDispatchCreateResponse // the object to be transformed
> = z
  .object({
    id: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      id: "id",
    });
  });

export const Schemas$WorkflowsDispatchCreateResponse = {
  in: SchemaIn$WorkflowsDispatchCreateResponse,
  out: SchemaOut$WorkflowsDispatchCreateResponse,
};
