/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * WorkflowsPatchBody
 */
export type WorkflowsPatchBody = {
  /**
   * Updated description of the workflow
   */
  description?: string | undefined;
  /**
   * Updated name of the workflow
   */
  name?: string | undefined;
  /**
   * Updated active workflow version ID
   */
  workflowId?: string | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (string | undefined)
    | (string | undefined)
    | (string | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * WorkflowsPatchBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$WorkflowsPatchBody = {
  description?: string | undefined;
  name?: string | undefined;
  workflow_id?: string | undefined;

  [additionalProperty: string]:
    | (string | undefined)
    | (string | undefined)
    | (string | undefined)
    | External$WorkflowsPatchBody
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object WorkflowsPatchBody
 */
const SchemaIn$WorkflowsPatchBody: z.ZodType<
  WorkflowsPatchBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    description: z.string().optional(),
    name: z.string().optional(),
    workflow_id: z.string().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      name: "name",
      workflow_id: "workflowId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$WorkflowsPatchBody
 */
const SchemaOut$WorkflowsPatchBody: z.ZodType<
  External$WorkflowsPatchBody, // output type of this zod object
  z.ZodTypeDef,
  WorkflowsPatchBody // the object to be transformed
> = z
  .object({
    description: z.string().optional(),
    name: z.string().optional(),
    workflowId: z.string().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      description: "description",
      name: "name",
      workflowId: "workflow_id",
    });
  });

export const Schemas$WorkflowsPatchBody = {
  in: SchemaIn$WorkflowsPatchBody,
  out: SchemaOut$WorkflowsPatchBody,
};
