/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";

import * as requests from "api_ts/resources/workflow/run/trigger/request-types";
import * as types from "api_ts/types";
import { Schemas$WorkflowRunTriggerCreateBody } from "api_ts/types/workflow-run-trigger-create-body";
import { Schemas$WorkflowRunTriggerCreateResponse } from "api_ts/types/workflow-run-trigger-create-response";

export class TriggerClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Trigger a new workflow run
   *
   * POST /workflow/run/trigger
   */
  create(
    request: requests.CreateRequest = {},
    opts?: RequestOptions,
  ): ApiPromise<types.WorkflowRunTriggerCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: "/workflow/run/trigger",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: request.data
        ? Schemas$WorkflowRunTriggerCreateBody.out.parse(request.data)
        : undefined,
      responseSchema: Schemas$WorkflowRunTriggerCreateResponse.in,
      opts,
    });
  }
}
