/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

import {
  External$ToolsStructuredOutputCreateBodyParams,
  Schemas$ToolsStructuredOutputCreateBodyParams,
  ToolsStructuredOutputCreateBodyParams,
} from "api_ts/types/tools-structured-output-create-body-params";

/**
 * CreateRequest
 */
export type CreateRequest = {
  /**
   * the unstructured data to format
   */
  input: string;
  params?: ToolsStructuredOutputCreateBodyParams | undefined;
  schema: Record<string, any | undefined> | any[];
  /**
   * Whether to validate the schema against the input
   */
  validate?: boolean | undefined;
};

/**
 * @internal
 * CreateRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$CreateRequest = {
  input: string;
  params?: External$ToolsStructuredOutputCreateBodyParams | undefined;
  schema: Record<string, any | undefined> | any[];
  validate?: boolean | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object CreateRequest
 */
const SchemaIn$CreateRequest: z.ZodType<
  CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    input: z.string(),
    params: Schemas$ToolsStructuredOutputCreateBodyParams.in.optional(),
    schema: z.union([
      z.record(z.string(), zodRequiredAny.optional()),
      z.array(zodRequiredAny),
    ]),
    validate: z.boolean().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      input: "input",
      params: "params",
      schema: "schema",
      validate: "validate",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$CreateRequest
 */
const SchemaOut$CreateRequest: z.ZodType<
  External$CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  CreateRequest // the object to be transformed
> = z
  .object({
    input: z.string(),
    params: Schemas$ToolsStructuredOutputCreateBodyParams.out.optional(),
    schema: z.union([
      z.record(z.string(), zodRequiredAny.optional()),
      z.array(zodRequiredAny),
    ]),
    validate: z.boolean().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      input: "input",
      params: "params",
      schema: "schema",
      validate: "validate",
    });
  });

export const Schemas$CreateRequest = {
  in: SchemaIn$CreateRequest,
  out: SchemaOut$CreateRequest,
};
