/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  CoreClient,
  CoreResourceClient,
  ResourceClientOptions,
} from "make-api-request-js";

import { ApiClient } from "api_ts/resources/integrations/api";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class IntegrationsClient extends CoreResourceClient {
  private _apiLazy?: ApiClient; // lazy-loading cache

  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
    if (this._opts.lazyLoad === false) {
      this.api;
    }
  }

  get api(): ApiClient {
    return (
      this._apiLazy ??
      (this._apiLazy = new (require("./api").ApiClient)(
        this._client,
        this._opts,
      ))
    );
  }
}
