/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * CreateRequest
 */
export type CreateRequest = {
  /**
   * The source code snippet to be executed.
   */
  code: string;
  /**
   * An object of key-value pairs to be passed as context to the code.
   */
  context?: Record<string, any | undefined> | undefined;
  /**
   * An object of key-value pairs to be passed as inputs to the code.
   */
  inputs: Record<string, any | undefined>;
  /**
   * The programming language of the code.
   */
  language: "javascript" | "python" | "typescript";
  /**
   * An optional list of external libraries or packages used by the code.
   */
  libraries?: string[] | undefined;
  /**
   * The ID of the Workflow Task Output associated with the code execution
   */
  outputId?: string | undefined;
  /**
   * The ID of the Workflow Task associated with the code execution
   */
  taskId?: string | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | (Record<string, any | undefined> | undefined)
    | Record<string, any | undefined>
    | ("javascript" | "python" | "typescript")
    | (string[] | undefined)
    | (string | undefined)
    | (string | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * CreateRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$CreateRequest = {
  code: string;
  context?: Record<string, any | undefined> | undefined;
  inputs: Record<string, any | undefined>;
  language: "javascript" | "python" | "typescript";
  libraries?: string[] | undefined;
  output_id?: string | undefined;
  task_id?: string | undefined;

  [additionalProperty: string]:
    | string
    | (Record<string, any | undefined> | undefined)
    | Record<string, any | undefined>
    | ("javascript" | "python" | "typescript")
    | (string[] | undefined)
    | (string | undefined)
    | (string | undefined)
    | External$CreateRequest
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object CreateRequest
 */
const SchemaIn$CreateRequest: z.ZodType<
  CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    code: z.string(),
    context: z.record(z.string(), zodRequiredAny.optional()).optional(),
    inputs: z.record(z.string(), zodRequiredAny.optional()),
    language: z.enum(["javascript", "python", "typescript"]),
    libraries: z.array(z.string()).optional(),
    output_id: z.string().optional(),
    task_id: z.string().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      code: "code",
      context: "context",
      inputs: "inputs",
      language: "language",
      libraries: "libraries",
      output_id: "outputId",
      task_id: "taskId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$CreateRequest
 */
const SchemaOut$CreateRequest: z.ZodType<
  External$CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  CreateRequest // the object to be transformed
> = z
  .object({
    code: z.string(),
    context: z.record(z.string(), zodRequiredAny.optional()).optional(),
    inputs: z.record(z.string(), zodRequiredAny.optional()),
    language: z.enum(["javascript", "python", "typescript"]),
    libraries: z.array(z.string()).optional(),
    outputId: z.string().optional(),
    taskId: z.string().optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      code: "code",
      context: "context",
      inputs: "inputs",
      language: "language",
      libraries: "libraries",
      outputId: "output_id",
      taskId: "task_id",
    });
  });

export const Schemas$CreateRequest = {
  in: SchemaIn$CreateRequest,
  out: SchemaOut$CreateRequest,
};
