/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";

import * as requests from "api_ts/resources/tools/code-execution/request-types";
import * as types from "api_ts/types";
import { Schemas$ToolsCodeExecutionCreateBody } from "api_ts/types/tools-code-execution-create-body";
import { Schemas$ToolsCodeExecutionCreateResponse } from "api_ts/types/tools-code-execution-create-response";

export class CodeExecutionClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Execute code and return the result
   *
   * POST /tools/code_execution
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.ToolsCodeExecutionCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: "/tools/code_execution",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$ToolsCodeExecutionCreateBody.out.parse(request),
      responseSchema: Schemas$ToolsCodeExecutionCreateResponse.in,
      opts,
    });
  }
}
