/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  CoreClient,
  CoreResourceClient,
  ResourceClientOptions,
} from "make-api-request-js";

import { BuildClient } from "api_ts/resources/agent/build";

export class AgentClient extends CoreResourceClient {
  private _buildLazy?: BuildClient; // lazy-loading cache

  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
    if (this._opts.lazyLoad === false) {
      this.build;
    }
  }

  get build(): BuildClient {
    return (
      this._buildLazy ??
      (this._buildLazy = new (require("./build").BuildClient)(
        this._client,
        this._opts,
      ))
    );
  }
}
