/**
 * Generated by Sideko (sideko.dev)
 **/

import { zodRequiredAny, zodTransform } from "make-api-request-js";
import * as z from "zod";

/**
 * ListRequest
 */
export type ListRequest = {
  /**
   * Maximum number of results to return
   */
  limit?: number | undefined;
  /**
   * Substring match against the datastore name
   */
  search?: string | undefined;
  /**
   * Filter by datastore type
   */
  type?:
    | (
        | "DATABASE_COLUMNAR"
        | "DATABASE_TRADITIONAL"
        | "FILE_STORE"
        | "VECTOR_STORE"
      )
    | undefined;
};

/**
 * @internal
 * ListRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$ListRequest = {
  limit?: number | undefined;
  search?: string | undefined;
  type?:
    | (
        | "DATABASE_COLUMNAR"
        | "DATABASE_TRADITIONAL"
        | "FILE_STORE"
        | "VECTOR_STORE"
      )
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object ListRequest
 */
const SchemaIn$ListRequest: z.ZodType<
  ListRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    limit: z.number().optional(),
    search: z.string().optional(),
    type: z
      .enum([
        "DATABASE_COLUMNAR",
        "DATABASE_TRADITIONAL",
        "FILE_STORE",
        "VECTOR_STORE",
      ])
      .optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      limit: "limit",
      search: "search",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$ListRequest
 */
const SchemaOut$ListRequest: z.ZodType<
  External$ListRequest, // output type of this zod object
  z.ZodTypeDef,
  ListRequest // the object to be transformed
> = z
  .object({
    limit: z.number().optional(),
    search: z.string().optional(),
    type: z
      .enum([
        "DATABASE_COLUMNAR",
        "DATABASE_TRADITIONAL",
        "FILE_STORE",
        "VECTOR_STORE",
      ])
      .optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      limit: "limit",
      search: "search",
      type: "type",
    });
  });

export const Schemas$ListRequest = {
  in: SchemaIn$ListRequest,
  out: SchemaOut$ListRequest,
};

/**
 * GetRequest
 */
export type GetRequest = {
  /**
   * The datastore ID
   */
  id: string;
};

/**
 * @internal
 * GetRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$GetRequest = {
  id: string;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object GetRequest
 */
const SchemaIn$GetRequest: z.ZodType<
  GetRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    id: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      id: "id",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$GetRequest
 */
const SchemaOut$GetRequest: z.ZodType<
  External$GetRequest, // output type of this zod object
  z.ZodTypeDef,
  GetRequest // the object to be transformed
> = z
  .object({
    id: z.string(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      id: "id",
    });
  });

export const Schemas$GetRequest = {
  in: SchemaIn$GetRequest,
  out: SchemaOut$GetRequest,
};

/**
 * CreateRequest
 */
export type CreateRequest = {
  /**
   * Optional config object
   */
  config?: Record<string, any | undefined> | null | undefined;
  /**
   * Description of the datastore
   */
  description: string;
  /**
   * Name of the datastore
   */
  name: string;
  /**
   * JSON Schema (required for DATABASE_* types)
   */
  schema?: Record<string, any | undefined> | null | undefined;
  /**
   * The datastore type
   */
  type:
    | "DATABASE_COLUMNAR"
    | "DATABASE_TRADITIONAL"
    | "FILE_STORE"
    | "VECTOR_STORE";

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (Record<string, any | undefined> | null | undefined)
    | string
    | string
    | (Record<string, any | undefined> | null | undefined)
    | (
        | "DATABASE_COLUMNAR"
        | "DATABASE_TRADITIONAL"
        | "FILE_STORE"
        | "VECTOR_STORE"
      )
    | any
    | null
    | undefined;
};

/**
 * @internal
 * CreateRequest without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$CreateRequest = {
  config?: Record<string, any | undefined> | null | undefined;
  description: string;
  name: string;
  schema?: Record<string, any | undefined> | null | undefined;
  type:
    | "DATABASE_COLUMNAR"
    | "DATABASE_TRADITIONAL"
    | "FILE_STORE"
    | "VECTOR_STORE";

  [additionalProperty: string]:
    | (Record<string, any | undefined> | null | undefined)
    | string
    | string
    | (Record<string, any | undefined> | null | undefined)
    | (
        | "DATABASE_COLUMNAR"
        | "DATABASE_TRADITIONAL"
        | "FILE_STORE"
        | "VECTOR_STORE"
      )
    | External$CreateRequest
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object CreateRequest
 */
const SchemaIn$CreateRequest: z.ZodType<
  CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    config: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    description: z.string(),
    name: z.string(),
    schema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    type: z.enum([
      "DATABASE_COLUMNAR",
      "DATABASE_TRADITIONAL",
      "FILE_STORE",
      "VECTOR_STORE",
    ]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      description: "description",
      name: "name",
      schema: "schema",
      type: "type",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$CreateRequest
 */
const SchemaOut$CreateRequest: z.ZodType<
  External$CreateRequest, // output type of this zod object
  z.ZodTypeDef,
  CreateRequest // the object to be transformed
> = z
  .object({
    config: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    description: z.string(),
    name: z.string(),
    schema: z
      .record(z.string(), zodRequiredAny.optional())
      .nullable()
      .optional(),
    type: z.enum([
      "DATABASE_COLUMNAR",
      "DATABASE_TRADITIONAL",
      "FILE_STORE",
      "VECTOR_STORE",
    ]),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      config: "config",
      description: "description",
      name: "name",
      schema: "schema",
      type: "type",
    });
  });

export const Schemas$CreateRequest = {
  in: SchemaIn$CreateRequest,
  out: SchemaOut$CreateRequest,
};
