/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
  encodeQueryParam,
} from "make-api-request-js";
import * as z from "zod";

import { ItemsClient } from "api_ts/resources/datastore/items";
import { QueryClient } from "api_ts/resources/datastore/query";
import * as requests from "api_ts/resources/datastore/request-types";
import * as types from "api_ts/types";
import { Schemas$DatastoreCreateBody } from "api_ts/types/datastore-create-body";
import { Schemas$DatastoreCreateResponse } from "api_ts/types/datastore-create-response";
import { Schemas$DatastoreGetResponse } from "api_ts/types/datastore-get-response";
import { Schemas$DatastoreListResponseItem } from "api_ts/types/datastore-list-response-item";

export class DatastoreClient extends CoreResourceClient {
  private _queryLazy?: QueryClient; // lazy-loading cache
  private _itemsLazy?: ItemsClient; // lazy-loading cache

  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
    if (this._opts.lazyLoad === false) {
      this.items;
      this.query;
    }
  }

  get items(): ItemsClient {
    return (
      this._itemsLazy ??
      (this._itemsLazy = new (require("./items").ItemsClient)(
        this._client,
        this._opts,
      ))
    );
  }

  get query(): QueryClient {
    return (
      this._queryLazy ??
      (this._queryLazy = new (require("./query").QueryClient)(
        this._client,
        this._opts,
      ))
    );
  }

  /**
   * List datastores
   *
   * List datastores owned by the authenticated user, optionally filtered by type or name search.
   *
   * GET /datastore
   */
  list(
    request: requests.ListRequest = {},
    opts?: RequestOptions,
  ): ApiPromise<types.DatastoreListResponseItem[]> {
    return this._client.makeRequest({
      method: "get",
      path: "/datastore",
      auth: ["ApiKeyAuth", "BearerAuth"],
      query: [
        encodeQueryParam({
          name: "limit",
          value: z.number().optional().parse(request.limit),
          style: "form",
          explode: true,
        }),
        encodeQueryParam({
          name: "search",
          value: z.string().optional().parse(request.search),
          style: "form",
          explode: true,
        }),
        encodeQueryParam({
          name: "type",
          value: z
            .enum([
              "DATABASE_COLUMNAR",
              "DATABASE_TRADITIONAL",
              "FILE_STORE",
              "VECTOR_STORE",
            ])
            .optional()
            .parse(request.type),
          style: "form",
          explode: true,
        }),
      ],
      responseSchema: z.array(Schemas$DatastoreListResponseItem.in),
      opts,
    });
  }

  /**
   * Get a datastore
   *
   * Retrieve a single datastore by its ID.
   *
   * GET /datastore/{id}
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.DatastoreGetResponse> {
    return this._client.makeRequest({
      method: "get",
      path: `/datastore/${request.id}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$DatastoreGetResponse.in,
      opts,
    });
  }

  /**
   * Create a datastore
   *
   * Create a new datastore (FileStore, VectorStore, or Database).
   *
   * POST /datastore
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.DatastoreCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: "/datastore",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$DatastoreCreateBody.out.parse(request),
      responseSchema: Schemas$DatastoreCreateResponse.in,
      opts,
    });
  }
}
