/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  CoreClient,
  CoreResourceClient,
  ResourceClientOptions,
} from "make-api-request-js";

import { SearchClient } from "api_ts/resources/feeds/vector/search";

export class VectorClient extends CoreResourceClient {
  private _searchLazy?: SearchClient; // lazy-loading cache

  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
    if (this._opts.lazyLoad === false) {
      this.search;
    }
  }

  get search(): SearchClient {
    return (
      this._searchLazy ??
      (this._searchLazy = new (require("./search").SearchClient)(
        this._client,
        this._opts,
      ))
    );
  }
}
