/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";

import * as requests from "api_ts/resources/datastore/query/request-types";
import * as types from "api_ts/types";
import { Schemas$DatastoreQueryCreateBody } from "api_ts/types/datastore-query-create-body";
import { Schemas$DatastoreQueryCreateResponse } from "api_ts/types/datastore-query-create-response";

export class QueryClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Query a datastore
   *
   * Run a natural language query against a VectorStore, or a SQL query against a Database datastore.
   *
   * POST /datastore/{id}/query
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.DatastoreQueryCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: `/datastore/${request.id}/query`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$DatastoreQueryCreateBody.out.parse(request),
      responseSchema: Schemas$DatastoreQueryCreateResponse.in,
      opts,
    });
  }
}
