/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";

import * as requests from "api_ts/resources/integrations/api/operations/request-types";
import * as types from "api_ts/types";
import { Schemas$IntegrationsApiOperationsCreateBody } from "api_ts/types/integrations-api-operations-create-body";
import { Schemas$IntegrationsApiOperationsCreateResponse } from "api_ts/types/integrations-api-operations-create-response";
import { Schemas$IntegrationsApiOperationsDeleteResponse } from "api_ts/types/integrations-api-operations-delete-response";
import { Schemas$IntegrationsApiOperationsGetResponse } from "api_ts/types/integrations-api-operations-get-response";
import { Schemas$IntegrationsApiOperationsPatchBody } from "api_ts/types/integrations-api-operations-patch-body";
import { Schemas$IntegrationsApiOperationsPatchResponse } from "api_ts/types/integrations-api-operations-patch-response";

export class OperationsClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Delete an API operation
   *
   * DELETE /integrations/api/{id}/operations/{operationId}
   */
  delete(
    request: requests.DeleteRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.IntegrationsApiOperationsDeleteResponse> {
    return this._client.makeRequest({
      method: "delete",
      path: `/integrations/api/${request.id}/operations/${request.operationId}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$IntegrationsApiOperationsDeleteResponse.in,
      opts,
    });
  }

  /**
   * Get an API operation by ID
   *
   * GET /integrations/api/{id}/operations/{operationId}
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.IntegrationsApiOperationsGetResponse> {
    return this._client.makeRequest({
      method: "get",
      path: `/integrations/api/${request.id}/operations/${request.operationId}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$IntegrationsApiOperationsGetResponse.in,
      opts,
    });
  }

  /**
   * Update an API operation
   *
   * PATCH /integrations/api/{id}/operations/{operationId}
   */
  patch(
    request: requests.PatchRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.IntegrationsApiOperationsPatchResponse> {
    return this._client.makeRequest({
      method: "patch",
      path: `/integrations/api/${request.id}/operations/${request.operationId}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: request.data
        ? Schemas$IntegrationsApiOperationsPatchBody.out.parse(request.data)
        : undefined,
      responseSchema: Schemas$IntegrationsApiOperationsPatchResponse.in,
      opts,
    });
  }

  /**
   * Create a new API operation
   *
   * POST /integrations/api/{id}/operations
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.IntegrationsApiOperationsCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: `/integrations/api/${request.id}/operations`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: request.data
        ? Schemas$IntegrationsApiOperationsCreateBody.out.parse(request.data)
        : undefined,
      responseSchema: Schemas$IntegrationsApiOperationsCreateResponse.in,
      opts,
    });
  }
}
