/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  AuthBearer,
  AuthKey,
  CoreClient,
  ResourceClientOptions,
} from "make-api-request-js";

import { Environment } from "api_ts/environment";
import { AgentClient } from "api_ts/resources/agent";
import { AuthClient } from "api_ts/resources/auth";
import { ChatsClient } from "api_ts/resources/chats";
import { FeedsClient } from "api_ts/resources/feeds";
import { IntegrationsClient } from "api_ts/resources/integrations";
import { SearchGroupsClient } from "api_ts/resources/search-groups";
import { ToolsClient } from "api_ts/resources/tools";
import { WorkflowClient } from "api_ts/resources/workflow";
import { WorkflowsClient } from "api_ts/resources/workflows";

/**
 * Generated by Sideko (sideko.dev)
 **/

export interface ClientOptions extends ResourceClientOptions {
  baseUrl?: string;
  environment?: Environment;
  timeout?: number;
  lazyLoad?: boolean;
  apiKey?: string;
  token?: string;
}

export class Client {
  private _workflowsLazy?: WorkflowsClient; // lazy-loading cache
  private _workflowLazy?: WorkflowClient; // lazy-loading cache
  private _toolsLazy?: ToolsClient; // lazy-loading cache
  private _searchGroupsLazy?: SearchGroupsClient; // lazy-loading cache
  private _integrationsLazy?: IntegrationsClient; // lazy-loading cache
  private _feedsLazy?: FeedsClient; // lazy-loading cache
  private _chatsLazy?: ChatsClient; // lazy-loading cache
  private _authLazy?: AuthClient; // lazy-loading cache
  private _agentLazy?: AgentClient; // lazy-loading cache

  protected _client: CoreClient;
  protected _opts: ResourceClientOptions;

  constructor(opts?: ClientOptions) {
    this._client = new CoreClient({
      baseUrl: opts?.baseUrl ?? opts?.environment ?? Environment.Default,
      timeout: opts?.timeout,
      auths: {
        ApiKeyAuth: new AuthKey("x-api-key", "header", opts?.apiKey),
        BearerAuth: new AuthBearer(opts?.token),
      },
    });
    this._opts = opts ?? {};
    if (this._opts.lazyLoad === false) {
      this.agent;
      this.auth;
      this.chats;
      this.feeds;
      this.integrations;
      this.searchGroups;
      this.tools;
      this.workflow;
      this.workflows;
    }
  }

  get agent(): AgentClient {
    return (
      this._agentLazy ??
      (this._agentLazy = new (require("./resources/agent").AgentClient)(
        this._client,
        this._opts,
      ))
    );
  }

  get auth(): AuthClient {
    return (
      this._authLazy ??
      (this._authLazy = new (require("./resources/auth").AuthClient)(
        this._client,
        this._opts,
      ))
    );
  }

  get chats(): ChatsClient {
    return (
      this._chatsLazy ??
      (this._chatsLazy = new (require("./resources/chats").ChatsClient)(
        this._client,
        this._opts,
      ))
    );
  }

  get feeds(): FeedsClient {
    return (
      this._feedsLazy ??
      (this._feedsLazy = new (require("./resources/feeds").FeedsClient)(
        this._client,
        this._opts,
      ))
    );
  }

  get integrations(): IntegrationsClient {
    return (
      this._integrationsLazy ??
      (this._integrationsLazy =
        new (require("./resources/integrations").IntegrationsClient)(
          this._client,
          this._opts,
        ))
    );
  }

  get searchGroups(): SearchGroupsClient {
    return (
      this._searchGroupsLazy ??
      (this._searchGroupsLazy =
        new (require("./resources/search-groups").SearchGroupsClient)(
          this._client,
          this._opts,
        ))
    );
  }

  get tools(): ToolsClient {
    return (
      this._toolsLazy ??
      (this._toolsLazy = new (require("./resources/tools").ToolsClient)(
        this._client,
        this._opts,
      ))
    );
  }

  get workflow(): WorkflowClient {
    return (
      this._workflowLazy ??
      (this._workflowLazy =
        new (require("./resources/workflow").WorkflowClient)(
          this._client,
          this._opts,
        ))
    );
  }

  get workflows(): WorkflowsClient {
    return (
      this._workflowsLazy ??
      (this._workflowsLazy =
        new (require("./resources/workflows").WorkflowsClient)(
          this._client,
          this._opts,
        ))
    );
  }
}
