/**
 * Generated by Sideko (sideko.dev)
 **/

export enum Environment {
  Default = "http://localhost",
  DefaultTemplate = "{protocol}://{host}",
  MockServer = "https://api.sideko.dev/v1/mock/human2human/api/0.1.0",
}

/**
 * Variables for formatting DefaultTemplate
 */
export interface DefaultTemplateVariables {
  protocol: string | number;
  host: string | number;
}

/**
 * Format the DefaultTemplate URL with the given variables
 * @param vars The variables to insert into the template
 * @returns Formatted URL string
 */
export function formatDefaultTemplate(vars: DefaultTemplateVariables): string {
  let result = Environment.DefaultTemplate.toString();
  for (const [key, value] of Object.entries(vars)) {
    result = result.replace(`{${key}}`, value.toString());
  }
  return result;
}

/**
 * Format any template environment URL with the given variables
 * @param env The environment URL template to format
 * @param vars The variables to insert into the template
 * @returns Formatted URL string
 */
export function formatServerTemplate(
  env: Environment,
  vars: Record<string, string | number>,
): string {
  let result = env.toString();
  for (const [key, value] of Object.entries(vars)) {
    result = result.replace(`{${key}}`, value.toString());
  }
  return result;
}
