/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";
import * as z from "zod";

import * as requests from "api_ts/resources/tools/dictionary-search/request-types";
import * as types from "api_ts/types";
import { Schemas$ToolsDictionarySearchCreateBody } from "api_ts/types/tools-dictionary-search-create-body";
import { Schemas$ToolsDictionarySearchCreateResponseItem } from "api_ts/types/tools-dictionary-search-create-response-item";

/**
 * Generated by Sideko (sideko.dev)
 **/

export class DictionarySearchClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * Search for dictionary definitions related to a feed item
   *
   * POST /tools/dictionary_search
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.ToolsDictionarySearchCreateResponseItem[]> {
    return this._client.makeRequest({
      method: "post",
      path: "/tools/dictionary_search",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: Schemas$ToolsDictionarySearchCreateBody.out.parse(request),
      responseSchema: z.array(
        Schemas$ToolsDictionarySearchCreateResponseItem.in,
      ),
      opts,
    });
  }
}
