/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
  encodeQueryParam,
} from "make-api-request-js";
import * as z from "zod";

import * as requests from "api_ts/resources/agent/history/request-types";
import * as types from "api_ts/types";
import { Schemas$AgentHistoryListResponse } from "api_ts/types/agent-history-list-response";

export class HistoryClient extends CoreResourceClient {
  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
  }

  /**
   * List agent chat history
   *
   * Retrieve a paginated list of chat sessions for the authenticated user, ordered by most recent first.
   *
   * GET /agent/history
   */
  list(
    request: requests.ListRequest = {},
    opts?: RequestOptions,
  ): ApiPromise<types.AgentHistoryListResponse> {
    return this._client.makeRequest({
      method: "get",
      path: "/agent/history",
      auth: ["ApiKeyAuth", "BearerAuth"],
      query: [
        encodeQueryParam({
          name: "limit",
          value: z.number().optional().parse(request.limit),
          style: "form",
          explode: true,
        }),
        encodeQueryParam({
          name: "offset",
          value: z.number().optional().parse(request.offset),
          style: "form",
          explode: true,
        }),
      ],
      responseSchema: Schemas$AgentHistoryListResponse.in,
      opts,
    });
  }
}
