/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  ApiPromise,
  CoreClient,
  CoreResourceClient,
  RequestOptions,
  ResourceClientOptions,
} from "make-api-request-js";

import { OperationsClient } from "api_ts/resources/integrations/api/operations";
import * as requests from "api_ts/resources/integrations/api/request-types";
import { SecretsClient } from "api_ts/resources/integrations/api/secrets";
import * as types from "api_ts/types";
import { Schemas$IntegrationsApiCreateBody } from "api_ts/types/integrations-api-create-body";
import { Schemas$IntegrationsApiCreateResponse } from "api_ts/types/integrations-api-create-response";
import { Schemas$IntegrationsApiDeleteResponse } from "api_ts/types/integrations-api-delete-response";
import { Schemas$IntegrationsApiGetResponse } from "api_ts/types/integrations-api-get-response";

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Generated by Sideko (sideko.dev)
 **/

export class ApiClient extends CoreResourceClient {
  private _secretsLazy?: SecretsClient; // lazy-loading cache
  private _operationsLazy?: OperationsClient; // lazy-loading cache

  constructor(coreClient: CoreClient, opts: ResourceClientOptions) {
    super(coreClient, opts);
    if (this._opts.lazyLoad === false) {
      this.operations;
      this.secrets;
    }
  }

  get operations(): OperationsClient {
    return (
      this._operationsLazy ??
      (this._operationsLazy = new (require("./operations").OperationsClient)(
        this._client,
        this._opts,
      ))
    );
  }

  get secrets(): SecretsClient {
    return (
      this._secretsLazy ??
      (this._secretsLazy = new (require("./secrets").SecretsClient)(
        this._client,
        this._opts,
      ))
    );
  }

  /**
   * Delete an API integration
   *
   * Delete an API integration by its ID.
   *
   * DELETE /integrations/api/{id}
   */
  delete(
    request: requests.DeleteRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.IntegrationsApiDeleteResponse> {
    return this._client.makeRequest({
      method: "delete",
      path: `/integrations/api/${request.id}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$IntegrationsApiDeleteResponse.in,
      opts,
    });
  }

  /**
   * Get an API integration by ID
   *
   * Retrieve a single API integration by its ID.
   *
   * GET /integrations/api/{id}
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.IntegrationsApiGetResponse> {
    return this._client.makeRequest({
      method: "get",
      path: `/integrations/api/${request.id}`,
      auth: ["ApiKeyAuth", "BearerAuth"],
      responseSchema: Schemas$IntegrationsApiGetResponse.in,
      opts,
    });
  }

  /**
   * Create a new API integration
   *
   * Create a new API integration for the authenticated user.
   *
   * POST /integrations/api
   */
  create(
    request: requests.CreateRequest = {},
    opts?: RequestOptions,
  ): ApiPromise<types.IntegrationsApiCreateResponse> {
    return this._client.makeRequest({
      method: "post",
      path: "/integrations/api",
      auth: ["ApiKeyAuth", "BearerAuth"],
      contentType: "application/json",
      body: request.data
        ? Schemas$IntegrationsApiCreateBody.out.parse(request.data)
        : undefined,
      responseSchema: Schemas$IntegrationsApiCreateResponse.in,
      opts,
    });
  }
}
